package com.tansun.eam2.jiekou.erp.model.bo;

import com.tansun.rdp4j.common.web.vo.CommonBO;

/**
 * ErpBxmx generated by MyEclipse Persistence Tools
 */

public class ErpBxmx extends CommonBO implements java.io.Serializable {

	// Fields

	private Long id;
	private String eampk;
	private String erppk;
	private String billcode;
	private String erpbillpk;
	private String erpbillcode;
	private Double money;
	private String sfwb;
	private String backup1;
	private String backup2;
	private String backup3;
	private String backup4;
	private String backup5;
	private String backup6;
	private String backup7;
	private String backup8;
	private String backup9;

	// Constructors

	/** default constructor */
	public ErpBxmx() {
	}

	/** full constructor */
	public ErpBxmx(String eampk, String erppk, String billcode,
			String erpbillpk, String erpbillcode, Double money, String sfwb,
			String backup1, String backup2, String backup3, String backup4,
			String backup5, String backup6, String backup7, String backup8,
			String backup9) {
		this.eampk = eampk;
		this.erppk = erppk;
		this.billcode = billcode;
		this.erpbillpk = erpbillpk;
		this.erpbillcode = erpbillcode;
		this.money = money;
		this.sfwb = sfwb;
		this.backup1 = backup1;
		this.backup2 = backup2;
		this.backup3 = backup3;
		this.backup4 = backup4;
		this.backup5 = backup5;
		this.backup6 = backup6;
		this.backup7 = backup7;
		this.backup8 = backup8;
		this.backup9 = backup9;
	}

	// Property accessors

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public String getEampk() {
		return this.eampk;
	}

	public void setEampk(String eampk) {
		this.eampk = eampk;
	}

	public String getErppk() {
		return this.erppk;
	}

	public void setErppk(String erppk) {
		this.erppk = erppk;
	}

	public String getBillcode() {
		return this.billcode;
	}

	public void setBillcode(String billcode) {
		this.billcode = billcode;
	}

	public String getErpbillpk() {
		return this.erpbillpk;
	}

	public void setErpbillpk(String erpbillpk) {
		this.erpbillpk = erpbillpk;
	}

	public String getErpbillcode() {
		return this.erpbillcode;
	}

	public void setErpbillcode(String erpbillcode) {
		this.erpbillcode = erpbillcode;
	}

	public Double getMoney() {
		return this.money;
	}

	public void setMoney(Double money) {
		this.money = money;
	}

	public String getSfwb() {
		return this.sfwb;
	}

	public void setSfwb(String sfwb) {
		this.sfwb = sfwb;
	}

	public String getBackup1() {
		return this.backup1;
	}

	public void setBackup1(String backup1) {
		this.backup1 = backup1;
	}

	public String getBackup2() {
		return this.backup2;
	}

	public void setBackup2(String backup2) {
		this.backup2 = backup2;
	}

	public String getBackup3() {
		return this.backup3;
	}

	public void setBackup3(String backup3) {
		this.backup3 = backup3;
	}

	public String getBackup4() {
		return this.backup4;
	}

	public void setBackup4(String backup4) {
		this.backup4 = backup4;
	}

	public String getBackup5() {
		return this.backup5;
	}

	public void setBackup5(String backup5) {
		this.backup5 = backup5;
	}

	public String getBackup6() {
		return this.backup6;
	}

	public void setBackup6(String backup6) {
		this.backup6 = backup6;
	}

	public String getBackup7() {
		return this.backup7;
	}

	public void setBackup7(String backup7) {
		this.backup7 = backup7;
	}

	public String getBackup8() {
		return this.backup8;
	}

	public void setBackup8(String backup8) {
		this.backup8 = backup8;
	}

	public String getBackup9() {
		return this.backup9;
	}

	public void setBackup9(String backup9) {
		this.backup9 = backup9;
	}

	@Override
	public String getMid() {
		// TODO Auto-generated method stub
		return null;
	}

}