package com.tansun.eam2.jiekou.erp.model.bo;

import com.tansun.rdp4j.common.web.vo.CommonBO;

/**
 * ErpCardhbsend generated by MyEclipse Persistence Tools
 */

public class ErpCardhbsend extends CommonBO implements java.io.Serializable {

	// Fields

	private Long id;
	private String eamcodepk;
	private String eamcode;
	private String acardcode;
	private String azccode;
	private String bcardcode;
	private String bcardcodepk;
	private String bzccode;
	private String billcode;
	private String billcodepk;
	private String sfbh;
	private String sftg;
	private String bhnotice;
	private String status;
	private String backup1;
	private String backup2;
	private String backup3;

	// Constructors

	/** default constructor */
	public ErpCardhbsend() {
	}

	/** full constructor */
	public ErpCardhbsend(String eamcodepk, String eamcode, String acardcode,
			String azccode, String bcardcode, String bcardcodepk,
			String bzccode, String billcode, String billcodepk, String sfbh,
			String sftg, String bhnotice, String status, String backup1,
			String backup2, String backup3) {
		this.eamcodepk = eamcodepk;
		this.eamcode = eamcode;
		this.acardcode = acardcode;
		this.azccode = azccode;
		this.bcardcode = bcardcode;
		this.bcardcodepk = bcardcodepk;
		this.bzccode = bzccode;
		this.billcode = billcode;
		this.billcodepk = billcodepk;
		this.sfbh = sfbh;
		this.sftg = sftg;
		this.bhnotice = bhnotice;
		this.status = status;
		this.backup1 = backup1;
		this.backup2 = backup2;
		this.backup3 = backup3;
	}

	// Property accessors

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public String getEamcodepk() {
		return this.eamcodepk;
	}

	public void setEamcodepk(String eamcodepk) {
		this.eamcodepk = eamcodepk;
	}

	public String getEamcode() {
		return this.eamcode;
	}

	public void setEamcode(String eamcode) {
		this.eamcode = eamcode;
	}

	public String getAcardcode() {
		return this.acardcode;
	}

	public void setAcardcode(String acardcode) {
		this.acardcode = acardcode;
	}

	public String getAzccode() {
		return this.azccode;
	}

	public void setAzccode(String azccode) {
		this.azccode = azccode;
	}

	public String getBcardcode() {
		return this.bcardcode;
	}

	public void setBcardcode(String bcardcode) {
		this.bcardcode = bcardcode;
	}

	public String getBcardcodepk() {
		return this.bcardcodepk;
	}

	public void setBcardcodepk(String bcardcodepk) {
		this.bcardcodepk = bcardcodepk;
	}

	public String getBzccode() {
		return this.bzccode;
	}

	public void setBzccode(String bzccode) {
		this.bzccode = bzccode;
	}

	public String getBillcode() {
		return this.billcode;
	}

	public void setBillcode(String billcode) {
		this.billcode = billcode;
	}

	public String getBillcodepk() {
		return this.billcodepk;
	}

	public void setBillcodepk(String billcodepk) {
		this.billcodepk = billcodepk;
	}

	public String getSfbh() {
		return this.sfbh;
	}

	public void setSfbh(String sfbh) {
		this.sfbh = sfbh;
	}

	public String getSftg() {
		return this.sftg;
	}

	public void setSftg(String sftg) {
		this.sftg = sftg;
	}

	public String getBhnotice() {
		return this.bhnotice;
	}

	public void setBhnotice(String bhnotice) {
		this.bhnotice = bhnotice;
	}

	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public String getBackup1() {
		return this.backup1;
	}

	public void setBackup1(String backup1) {
		this.backup1 = backup1;
	}

	public String getBackup2() {
		return this.backup2;
	}

	public void setBackup2(String backup2) {
		this.backup2 = backup2;
	}

	public String getBackup3() {
		return this.backup3;
	}

	public void setBackup3(String backup3) {
		this.backup3 = backup3;
	}

	@Override
	public String getMid() {
		// TODO Auto-generated method stub
		return null;
	}

}