package com.tansun.eam2.jiekou.erp.model.bo;

import com.tansun.rdp4j.common.web.vo.CommonBO;

/**
 * ErpCardreducesend generated by MyEclipse Persistence Tools
 */

public class ErpCardreducesend extends CommonBO implements java.io.Serializable {

	// Fields

	private Long id;
	private String erppk;
	private String erpcodepk;
	private String erpdjh;
	private String eampk;
	private String eamdjh;
	private String eamspyj;
	private String jgdm;
	private String cwxx;
	private String kpbm;
	private String zcbm;
	private String zcmc;
	private String zclb;
	private String ggxh;
	private String jsfs;
	private String jsyy;
	private String syzk;
	private String glbm;
	private String sybm;
	private String syr;
	private String kssyrq;
	private String synx;
	private String sksynx;
	private String yjtzjyf;
	private String ybyz;
	private String fbyz;
	private String ljzj;
	private String jz;
	private String jzzb;
	private String je;
	private String jcz;
	private String bz;
	private String zdrid;
	private String zdrq;

	// Constructors

	/** default constructor */
	public ErpCardreducesend() {
	}

	/** full constructor */
	public ErpCardreducesend(String erppk, String erpcodepk, String erpdjh,
			String eampk, String eamdjh, String eamspyj, String jgdm,
			String cwxx, String kpbm, String zcbm, String zcmc, String zclb,
			String ggxh, String jsfs, String jsyy, String syzk, String glbm,
			String sybm, String syr, String kssyrq, String synx, String sksynx,
			String yjtzjyf, String ybyz, String fbyz, String ljzj, String jz,
			String jzzb, String je, String jcz, String bz, String zdrid,
			String zdrq) {
		this.erppk = erppk;
		this.erpcodepk = erpcodepk;
		this.erpdjh = erpdjh;
		this.eampk = eampk;
		this.eamdjh = eamdjh;
		this.eamspyj = eamspyj;
		this.jgdm = jgdm;
		this.cwxx = cwxx;
		this.kpbm = kpbm;
		this.zcbm = zcbm;
		this.zcmc = zcmc;
		this.zclb = zclb;
		this.ggxh = ggxh;
		this.jsfs = jsfs;
		this.jsyy = jsyy;
		this.syzk = syzk;
		this.glbm = glbm;
		this.sybm = sybm;
		this.syr = syr;
		this.kssyrq = kssyrq;
		this.synx = synx;
		this.sksynx = sksynx;
		this.yjtzjyf = yjtzjyf;
		this.ybyz = ybyz;
		this.fbyz = fbyz;
		this.ljzj = ljzj;
		this.jz = jz;
		this.jzzb = jzzb;
		this.je = je;
		this.jcz = jcz;
		this.bz = bz;
		this.zdrid = zdrid;
		this.zdrq = zdrq;
	}

	// Property accessors

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public String getErppk() {
		return this.erppk;
	}

	public void setErppk(String erppk) {
		this.erppk = erppk;
	}

	public String getErpcodepk() {
		return this.erpcodepk;
	}

	public void setErpcodepk(String erpcodepk) {
		this.erpcodepk = erpcodepk;
	}

	public String getErpdjh() {
		return this.erpdjh;
	}

	public void setErpdjh(String erpdjh) {
		this.erpdjh = erpdjh;
	}

	public String getEampk() {
		return this.eampk;
	}

	public void setEampk(String eampk) {
		this.eampk = eampk;
	}

	public String getEamdjh() {
		return this.eamdjh;
	}

	public void setEamdjh(String eamdjh) {
		this.eamdjh = eamdjh;
	}

	public String getEamspyj() {
		return this.eamspyj;
	}

	public void setEamspyj(String eamspyj) {
		this.eamspyj = eamspyj;
	}

	public String getJgdm() {
		return this.jgdm;
	}

	public void setJgdm(String jgdm) {
		this.jgdm = jgdm;
	}

	public String getCwxx() {
		return this.cwxx;
	}

	public void setCwxx(String cwxx) {
		this.cwxx = cwxx;
	}

	public String getKpbm() {
		return this.kpbm;
	}

	public void setKpbm(String kpbm) {
		this.kpbm = kpbm;
	}

	public String getZcbm() {
		return this.zcbm;
	}

	public void setZcbm(String zcbm) {
		this.zcbm = zcbm;
	}

	public String getZcmc() {
		return this.zcmc;
	}

	public void setZcmc(String zcmc) {
		this.zcmc = zcmc;
	}

	public String getZclb() {
		return this.zclb;
	}

	public void setZclb(String zclb) {
		this.zclb = zclb;
	}

	public String getGgxh() {
		return this.ggxh;
	}

	public void setGgxh(String ggxh) {
		this.ggxh = ggxh;
	}

	public String getJsfs() {
		return this.jsfs;
	}

	public void setJsfs(String jsfs) {
		this.jsfs = jsfs;
	}

	public String getJsyy() {
		return this.jsyy;
	}

	public void setJsyy(String jsyy) {
		this.jsyy = jsyy;
	}

	public String getSyzk() {
		return this.syzk;
	}

	public void setSyzk(String syzk) {
		this.syzk = syzk;
	}

	public String getGlbm() {
		return this.glbm;
	}

	public void setGlbm(String glbm) {
		this.glbm = glbm;
	}

	public String getSybm() {
		return this.sybm;
	}

	public void setSybm(String sybm) {
		this.sybm = sybm;
	}

	public String getSyr() {
		return this.syr;
	}

	public void setSyr(String syr) {
		this.syr = syr;
	}

	public String getKssyrq() {
		return this.kssyrq;
	}

	public void setKssyrq(String kssyrq) {
		this.kssyrq = kssyrq;
	}

	public String getSynx() {
		return this.synx;
	}

	public void setSynx(String synx) {
		this.synx = synx;
	}

	public String getSksynx() {
		return this.sksynx;
	}

	public void setSksynx(String sksynx) {
		this.sksynx = sksynx;
	}

	public String getYjtzjyf() {
		return this.yjtzjyf;
	}

	public void setYjtzjyf(String yjtzjyf) {
		this.yjtzjyf = yjtzjyf;
	}

	public String getYbyz() {
		return this.ybyz;
	}

	public void setYbyz(String ybyz) {
		this.ybyz = ybyz;
	}

	public String getFbyz() {
		return this.fbyz;
	}

	public void setFbyz(String fbyz) {
		this.fbyz = fbyz;
	}

	public String getLjzj() {
		return this.ljzj;
	}

	public void setLjzj(String ljzj) {
		this.ljzj = ljzj;
	}

	public String getJz() {
		return this.jz;
	}

	public void setJz(String jz) {
		this.jz = jz;
	}

	public String getJzzb() {
		return this.jzzb;
	}

	public void setJzzb(String jzzb) {
		this.jzzb = jzzb;
	}

	public String getJe() {
		return this.je;
	}

	public void setJe(String je) {
		this.je = je;
	}

	public String getJcz() {
		return this.jcz;
	}

	public void setJcz(String jcz) {
		this.jcz = jcz;
	}

	public String getBz() {
		return this.bz;
	}

	public void setBz(String bz) {
		this.bz = bz;
	}

	public String getZdrid() {
		return this.zdrid;
	}

	public void setZdrid(String zdrid) {
		this.zdrid = zdrid;
	}

	public String getZdrq() {
		return this.zdrq;
	}

	public void setZdrq(String zdrq) {
		this.zdrq = zdrq;
	}

	@Override
	public String getMid() {
		// TODO Auto-generated method stub
		return null;
	}

}