package com.tansun.eam2.jiekou.erp.model.bo;

import com.tansun.rdp4j.common.web.vo.CommonBO;

/**
 * ErpCardjz generated by MyEclipse Persistence Tools
 */

public class ErpCardjz extends CommonBO implements java.io.Serializable {

	// Fields

	private Long id;
	private String sfjs;
	private String lccode;
	private String eamcode;
	private String eampk;
	private String erpcode;
	private String erpcodepk;
	private String erppk;
	private String cardcode;

	// Constructors

	/** default constructor */
	public ErpCardjz() {
	}

	/** full constructor */
	public ErpCardjz(String sfjs, String lccode, String eamcode, String eampk,
			String erpcode, String erpcodepk, String erppk, String cardcode) {
		this.sfjs = sfjs;
		this.lccode = lccode;
		this.eamcode = eamcode;
		this.eampk = eampk;
		this.erpcode = erpcode;
		this.erpcodepk = erpcodepk;
		this.erppk = erppk;
		this.cardcode = cardcode;
	}

	// Property accessors

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public String getSfjs() {
		return this.sfjs;
	}

	public void setSfjs(String sfjs) {
		this.sfjs = sfjs;
	}

	public String getLccode() {
		return this.lccode;
	}

	public void setLccode(String lccode) {
		this.lccode = lccode;
	}

	public String getEamcode() {
		return this.eamcode;
	}

	public void setEamcode(String eamcode) {
		this.eamcode = eamcode;
	}

	public String getEampk() {
		return this.eampk;
	}

	public void setEampk(String eampk) {
		this.eampk = eampk;
	}

	public String getErpcode() {
		return this.erpcode;
	}

	public void setErpcode(String erpcode) {
		this.erpcode = erpcode;
	}

	public String getErpcodepk() {
		return this.erpcodepk;
	}

	public void setErpcodepk(String erpcodepk) {
		this.erpcodepk = erpcodepk;
	}

	public String getErppk() {
		return this.erppk;
	}

	public void setErppk(String erppk) {
		this.erppk = erppk;
	}

	public String getCardcode() {
		return this.cardcode;
	}

	public void setCardcode(String cardcode) {
		this.cardcode = cardcode;
	}

	@Override
	public String getMid() {
		// TODO Auto-generated method stub
		return null;
	}

}