package com.tansun.eam2.jiekou.erp.model.bo;

import com.tansun.rdp4j.common.web.vo.CommonBO;

/**
 * ErpCardcfsend generated by MyEclipse Persistence Tools
 */

public class ErpCardcfsend extends CommonBO implements java.io.Serializable {

	// Fields

	private Long id;
	private String eamcode;
	private String eampk;
	private String eamnotice;
	private String erpcodepk;
	private String erpcode;
	private String erppk;
	private String returncode;
	private String errorinfo;
	private String ifbh;
	private String cardid;
	private String sfcode;
	private String typecode;
	private String jstype;
	private String zccode;
	private String bbyz;
	private String fbyz;
	private String glbm;
	private String glbmid;
	private String jzzb;
	private String jcz;
	private String jczl;
	private String je;
	private String jz;
	private String cardcode;
	private String startdate;
	private String ljzj;
	private String sybmid;
	private String syzkid;
	private String num;
	private String ybyz;
	private String zjfsid;
	private String zjcdbm;
	private String zjffid;
	private String zclbid;
	private String zcname;
	private String zdr;
	private String zdrq;
	private String bhly;

	// Constructors

	/** default constructor */
	public ErpCardcfsend() {
	}

	/** full constructor */
	public ErpCardcfsend(String eamcode, String eampk, String eamnotice,
			String erpcodepk, String erpcode, String erppk, String returncode,
			String errorinfo, String ifbh, String cardid, String sfcode,
			String typecode, String jstype, String zccode, String bbyz,
			String fbyz, String glbm, String glbmid, String jzzb, String jcz,
			String jczl, String je, String jz, String cardcode,
			String startdate, String ljzj, String sybmid, String syzkid,
			String num, String ybyz, String zjfsid, String zjcdbm,
			String zjffid, String zclbid, String zcname, String zdr,
			String zdrq, String bhly) {
		this.eamcode = eamcode;
		this.eampk = eampk;
		this.eamnotice = eamnotice;
		this.erpcodepk = erpcodepk;
		this.erpcode = erpcode;
		this.erppk = erppk;
		this.returncode = returncode;
		this.errorinfo = errorinfo;
		this.ifbh = ifbh;
		this.cardid = cardid;
		this.sfcode = sfcode;
		this.typecode = typecode;
		this.jstype = jstype;
		this.zccode = zccode;
		this.bbyz = bbyz;
		this.fbyz = fbyz;
		this.glbm = glbm;
		this.glbmid = glbmid;
		this.jzzb = jzzb;
		this.jcz = jcz;
		this.jczl = jczl;
		this.je = je;
		this.jz = jz;
		this.cardcode = cardcode;
		this.startdate = startdate;
		this.ljzj = ljzj;
		this.sybmid = sybmid;
		this.syzkid = syzkid;
		this.num = num;
		this.ybyz = ybyz;
		this.zjfsid = zjfsid;
		this.zjcdbm = zjcdbm;
		this.zjffid = zjffid;
		this.zclbid = zclbid;
		this.zcname = zcname;
		this.zdr = zdr;
		this.zdrq = zdrq;
		this.bhly = bhly;
	}

	// Property accessors

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public String getEamcode() {
		return this.eamcode;
	}

	public void setEamcode(String eamcode) {
		this.eamcode = eamcode;
	}

	public String getEampk() {
		return this.eampk;
	}

	public void setEampk(String eampk) {
		this.eampk = eampk;
	}

	public String getEamnotice() {
		return this.eamnotice;
	}

	public void setEamnotice(String eamnotice) {
		this.eamnotice = eamnotice;
	}

	public String getErpcodepk() {
		return this.erpcodepk;
	}

	public void setErpcodepk(String erpcodepk) {
		this.erpcodepk = erpcodepk;
	}

	public String getErpcode() {
		return this.erpcode;
	}

	public void setErpcode(String erpcode) {
		this.erpcode = erpcode;
	}

	public String getErppk() {
		return this.erppk;
	}

	public void setErppk(String erppk) {
		this.erppk = erppk;
	}

	public String getReturncode() {
		return this.returncode;
	}

	public void setReturncode(String returncode) {
		this.returncode = returncode;
	}

	public String getErrorinfo() {
		return this.errorinfo;
	}

	public void setErrorinfo(String errorinfo) {
		this.errorinfo = errorinfo;
	}

	public String getIfbh() {
		return this.ifbh;
	}

	public void setIfbh(String ifbh) {
		this.ifbh = ifbh;
	}

	public String getCardid() {
		return this.cardid;
	}

	public void setCardid(String cardid) {
		this.cardid = cardid;
	}

	public String getSfcode() {
		return this.sfcode;
	}

	public void setSfcode(String sfcode) {
		this.sfcode = sfcode;
	}

	public String getTypecode() {
		return this.typecode;
	}

	public void setTypecode(String typecode) {
		this.typecode = typecode;
	}

	public String getJstype() {
		return this.jstype;
	}

	public void setJstype(String jstype) {
		this.jstype = jstype;
	}

	public String getZccode() {
		return this.zccode;
	}

	public void setZccode(String zccode) {
		this.zccode = zccode;
	}

	public String getBbyz() {
		return this.bbyz;
	}

	public void setBbyz(String bbyz) {
		this.bbyz = bbyz;
	}

	public String getFbyz() {
		return this.fbyz;
	}

	public void setFbyz(String fbyz) {
		this.fbyz = fbyz;
	}

	public String getGlbm() {
		return this.glbm;
	}

	public void setGlbm(String glbm) {
		this.glbm = glbm;
	}

	public String getGlbmid() {
		return this.glbmid;
	}

	public void setGlbmid(String glbmid) {
		this.glbmid = glbmid;
	}

	public String getJzzb() {
		return this.jzzb;
	}

	public void setJzzb(String jzzb) {
		this.jzzb = jzzb;
	}

	public String getJcz() {
		return this.jcz;
	}

	public void setJcz(String jcz) {
		this.jcz = jcz;
	}

	public String getJczl() {
		return this.jczl;
	}

	public void setJczl(String jczl) {
		this.jczl = jczl;
	}

	public String getJe() {
		return this.je;
	}

	public void setJe(String je) {
		this.je = je;
	}

	public String getJz() {
		return this.jz;
	}

	public void setJz(String jz) {
		this.jz = jz;
	}

	public String getCardcode() {
		return this.cardcode;
	}

	public void setCardcode(String cardcode) {
		this.cardcode = cardcode;
	}

	public String getStartdate() {
		return this.startdate;
	}

	public void setStartdate(String startdate) {
		this.startdate = startdate;
	}

	public String getLjzj() {
		return this.ljzj;
	}

	public void setLjzj(String ljzj) {
		this.ljzj = ljzj;
	}

	public String getSybmid() {
		return this.sybmid;
	}

	public void setSybmid(String sybmid) {
		this.sybmid = sybmid;
	}

	public String getSyzkid() {
		return this.syzkid;
	}

	public void setSyzkid(String syzkid) {
		this.syzkid = syzkid;
	}

	public String getNum() {
		return this.num;
	}

	public void setNum(String num) {
		this.num = num;
	}

	public String getYbyz() {
		return this.ybyz;
	}

	public void setYbyz(String ybyz) {
		this.ybyz = ybyz;
	}

	public String getZjfsid() {
		return this.zjfsid;
	}

	public void setZjfsid(String zjfsid) {
		this.zjfsid = zjfsid;
	}

	public String getZjcdbm() {
		return this.zjcdbm;
	}

	public void setZjcdbm(String zjcdbm) {
		this.zjcdbm = zjcdbm;
	}

	public String getZjffid() {
		return this.zjffid;
	}

	public void setZjffid(String zjffid) {
		this.zjffid = zjffid;
	}

	public String getZclbid() {
		return this.zclbid;
	}

	public void setZclbid(String zclbid) {
		this.zclbid = zclbid;
	}

	public String getZcname() {
		return this.zcname;
	}

	public void setZcname(String zcname) {
		this.zcname = zcname;
	}

	public String getZdr() {
		return this.zdr;
	}

	public void setZdr(String zdr) {
		this.zdr = zdr;
	}

	public String getZdrq() {
		return this.zdrq;
	}

	public void setZdrq(String zdrq) {
		this.zdrq = zdrq;
	}

	public String getBhly() {
		return this.bhly;
	}

	public void setBhly(String bhly) {
		this.bhly = bhly;
	}

	@Override
	public String getMid() {
		// TODO Auto-generated method stub
		return null;
	}

}