package com.tansun.eam2.jiekou.erp.model.bo;

import com.tansun.rdp4j.common.web.vo.CommonBO;

/**
 * ErpCardspdaddsend generated by MyEclipse Persistence Tools
 */

public class ErpCardspdaddsend extends CommonBO implements java.io.Serializable {

	// Fields

	private Long id;
	private String bdh;
	private String dypk;
	private String erpzcbm;
	private String erpkpbm;
	private String fhbm;
	private String fhxx;
	private String sfbh;
	private String kpid;
	private String gsbm;
	private String djh;
	private String sqdwbm;
	private String sqbmbm;
	private String sqrq;
	private String sqly;
	private String jbrbm;
	private String zdrbm;
	private String zdrq;
	private String shrbm;
	private String shrq;
	private String je;
	private String sl;
	private String zjfs;
	private String sfcj;
	private String syyx;
	private String syzk;
	private String lbbm;
	private String zcbm;
	private String zcmc;
	private String sybmbm;
	private String ggxh;
	private String cfdd;

	// Constructors

	/** default constructor */
	public ErpCardspdaddsend() {
	}

	/** full constructor */
	public ErpCardspdaddsend(String bdh, String dypk, String erpzcbm,
			String erpkpbm, String fhbm, String fhxx, String sfbh, String kpid,
			String gsbm, String djh, String sqdwbm, String sqbmbm, String sqrq,
			String sqly, String jbrbm, String zdrbm, String zdrq, String shrbm,
			String shrq, String je, String sl, String zjfs, String sfcj,
			String syyx, String syzk, String lbbm, String zcbm, String zcmc,
			String sybmbm, String ggxh, String cfdd) {
		this.bdh = bdh;
		this.dypk = dypk;
		this.erpzcbm = erpzcbm;
		this.erpkpbm = erpkpbm;
		this.fhbm = fhbm;
		this.fhxx = fhxx;
		this.sfbh = sfbh;
		this.kpid = kpid;
		this.gsbm = gsbm;
		this.djh = djh;
		this.sqdwbm = sqdwbm;
		this.sqbmbm = sqbmbm;
		this.sqrq = sqrq;
		this.sqly = sqly;
		this.jbrbm = jbrbm;
		this.zdrbm = zdrbm;
		this.zdrq = zdrq;
		this.shrbm = shrbm;
		this.shrq = shrq;
		this.je = je;
		this.sl = sl;
		this.zjfs = zjfs;
		this.sfcj = sfcj;
		this.syyx = syyx;
		this.syzk = syzk;
		this.lbbm = lbbm;
		this.zcbm = zcbm;
		this.zcmc = zcmc;
		this.sybmbm = sybmbm;
		this.ggxh = ggxh;
		this.cfdd = cfdd;
	}

	// Property accessors

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public String getBdh() {
		return this.bdh;
	}

	public void setBdh(String bdh) {
		this.bdh = bdh;
	}

	public String getDypk() {
		return this.dypk;
	}

	public void setDypk(String dypk) {
		this.dypk = dypk;
	}

	public String getErpzcbm() {
		return this.erpzcbm;
	}

	public void setErpzcbm(String erpzcbm) {
		this.erpzcbm = erpzcbm;
	}

	public String getErpkpbm() {
		return this.erpkpbm;
	}

	public void setErpkpbm(String erpkpbm) {
		this.erpkpbm = erpkpbm;
	}

	public String getFhbm() {
		return this.fhbm;
	}

	public void setFhbm(String fhbm) {
		this.fhbm = fhbm;
	}

	public String getFhxx() {
		return this.fhxx;
	}

	public void setFhxx(String fhxx) {
		this.fhxx = fhxx;
	}

	public String getSfbh() {
		return this.sfbh;
	}

	public void setSfbh(String sfbh) {
		this.sfbh = sfbh;
	}

	public String getKpid() {
		return this.kpid;
	}

	public void setKpid(String kpid) {
		this.kpid = kpid;
	}

	public String getGsbm() {
		return this.gsbm;
	}

	public void setGsbm(String gsbm) {
		this.gsbm = gsbm;
	}

	public String getDjh() {
		return this.djh;
	}

	public void setDjh(String djh) {
		this.djh = djh;
	}

	public String getSqdwbm() {
		return this.sqdwbm;
	}

	public void setSqdwbm(String sqdwbm) {
		this.sqdwbm = sqdwbm;
	}

	public String getSqbmbm() {
		return this.sqbmbm;
	}

	public void setSqbmbm(String sqbmbm) {
		this.sqbmbm = sqbmbm;
	}

	public String getSqrq() {
		return this.sqrq;
	}

	public void setSqrq(String sqrq) {
		this.sqrq = sqrq;
	}

	public String getSqly() {
		return this.sqly;
	}

	public void setSqly(String sqly) {
		this.sqly = sqly;
	}

	public String getJbrbm() {
		return this.jbrbm;
	}

	public void setJbrbm(String jbrbm) {
		this.jbrbm = jbrbm;
	}

	public String getZdrbm() {
		return this.zdrbm;
	}

	public void setZdrbm(String zdrbm) {
		this.zdrbm = zdrbm;
	}

	public String getZdrq() {
		return this.zdrq;
	}

	public void setZdrq(String zdrq) {
		this.zdrq = zdrq;
	}

	public String getShrbm() {
		return this.shrbm;
	}

	public void setShrbm(String shrbm) {
		this.shrbm = shrbm;
	}

	public String getShrq() {
		return this.shrq;
	}

	public void setShrq(String shrq) {
		this.shrq = shrq;
	}

	public String getJe() {
		return this.je;
	}

	public void setJe(String je) {
		this.je = je;
	}

	public String getSl() {
		return this.sl;
	}

	public void setSl(String sl) {
		this.sl = sl;
	}

	public String getZjfs() {
		return this.zjfs;
	}

	public void setZjfs(String zjfs) {
		this.zjfs = zjfs;
	}

	public String getSfcj() {
		return this.sfcj;
	}

	public void setSfcj(String sfcj) {
		this.sfcj = sfcj;
	}

	public String getSyyx() {
		return this.syyx;
	}

	public void setSyyx(String syyx) {
		this.syyx = syyx;
	}

	public String getSyzk() {
		return this.syzk;
	}

	public void setSyzk(String syzk) {
		this.syzk = syzk;
	}

	public String getLbbm() {
		return this.lbbm;
	}

	public void setLbbm(String lbbm) {
		this.lbbm = lbbm;
	}

	public String getZcbm() {
		return this.zcbm;
	}

	public void setZcbm(String zcbm) {
		this.zcbm = zcbm;
	}

	public String getZcmc() {
		return this.zcmc;
	}

	public void setZcmc(String zcmc) {
		this.zcmc = zcmc;
	}

	public String getSybmbm() {
		return this.sybmbm;
	}

	public void setSybmbm(String sybmbm) {
		this.sybmbm = sybmbm;
	}

	public String getGgxh() {
		return this.ggxh;
	}

	public void setGgxh(String ggxh) {
		this.ggxh = ggxh;
	}

	public String getCfdd() {
		return this.cfdd;
	}

	public void setCfdd(String cfdd) {
		this.cfdd = cfdd;
	}

	@Override
	public String getMid() {
		// TODO Auto-generated method stub
		return null;
	}

}