package com.tansun.eam2.jiekou.erp.model.bo;

import com.tansun.rdp4j.common.web.vo.CommonBO;

/**
 * ErpCardaddsend generated by MyEclipse Persistence Tools
 */

public class ErpCardaddsend extends CommonBO implements java.io.Serializable {

	// Fields

	private Long id;
	private String bdh;
	private String dypk;
	private String fhxx;
	private String erpzcbm;
	private String sfbh;
	private String erpkpbm;
	private String fhbm;
	private String kpid;
	private String gsbm;
	private String zibm;
	private String zcmc;
	private String kssyrq;
	private String bzmc;
	private String bzcw;
	private String lrrmc;
	private String lrrq;
	private String syrbm;
	private String ggxh;
	private String cfdd;
	private String gzldw;
	private String zjfsbm;
	private String zcth;
	private String sybmbm;
	private String glbmbm;
	private String zjcdbm;
	private String hjn;
	private String hjy;
	private String ybyz;
	private String bbyz;
	private String fbyz;
	private String gzzl;
	private String syyx;
	private String ljzj;
	private String ljgzl;
	private String jzzb;
	private String yjtyf;
	private String ygzl;
	private String dwzj;
	private String jczl;
	private String jcz;
	private String yzkpbj;
	private String zclbbm;
	private String syzkbm;
	private String jzfabm;
	private String xmdabm;
	private String gysbm;
	private String ly;
	private String yrje;
	private String yrljzj;
	private String yryz;
	private String cpuxh;
	private String bxq;
	private String bz;
	private String clpzh;
	private String dytdzsyqr;
	private String fdjhm;
	private String fczhm;
	private String jjmj;
	private String je;
	private String jz;
	private String jkpbh;
	private String lbbm;
	private String lbmc;
	private String nc;
	private String nzyp;
	private String pgqljzj;
	private String pgqyz;
	private String qyrq;
	private String qszm;
	private String qzsyz;
	private String smbxq;
	private String sbxlh;
	private String sfjc;
	private String sxbxq;
	private String tdzhm;
	private String wzyp;
	private String xtxsq;
	private String ywdytd;
	private String yxtrry;
	private String yzje;
	private String yzjl;
	private String zyzt;
	private String zdmj;
	private String zyyt;
	private String zxrq;
	private String zxmj;

	// Constructors

	/** default constructor */
	public ErpCardaddsend() {
	}

	/** full constructor */
	public ErpCardaddsend(String bdh, String dypk, String fhxx, String erpzcbm,
			String sfbh, String erpkpbm, String fhbm, String kpid, String gsbm,
			String zibm, String zcmc, String kssyrq, String bzmc, String bzcw,
			String lrrmc, String lrrq, String syrbm, String ggxh, String cfdd,
			String gzldw, String zjfsbm, String zcth, String sybmbm,
			String glbmbm, String zjcdbm, String hjn, String hjy, String ybyz,
			String bbyz, String fbyz, String gzzl, String syyx, String ljzj,
			String ljgzl, String jzzb, String yjtyf, String ygzl, String dwzj,
			String jczl, String jcz, String yzkpbj, String zclbbm,
			String syzkbm, String jzfabm, String xmdabm, String gysbm,
			String ly, String yrje, String yrljzj, String yryz, String cpuxh,
			String bxq, String bz, String clpzh, String dytdzsyqr,
			String fdjhm, String fczhm, String jjmj, String je, String jz,
			String jkpbh, String lbbm, String lbmc, String nc, String nzyp,
			String pgqljzj, String pgqyz, String qyrq, String qszm,
			String qzsyz, String smbxq, String sbxlh, String sfjc,
			String sxbxq, String tdzhm, String wzyp, String xtxsq,
			String ywdytd, String yxtrry, String yzje, String yzjl,
			String zyzt, String zdmj, String zyyt, String zxrq, String zxmj) {
		this.bdh = bdh;
		this.dypk = dypk;
		this.fhxx = fhxx;
		this.erpzcbm = erpzcbm;
		this.sfbh = sfbh;
		this.erpkpbm = erpkpbm;
		this.fhbm = fhbm;
		this.kpid = kpid;
		this.gsbm = gsbm;
		this.zibm = zibm;
		this.zcmc = zcmc;
		this.kssyrq = kssyrq;
		this.bzmc = bzmc;
		this.bzcw = bzcw;
		this.lrrmc = lrrmc;
		this.lrrq = lrrq;
		this.syrbm = syrbm;
		this.ggxh = ggxh;
		this.cfdd = cfdd;
		this.gzldw = gzldw;
		this.zjfsbm = zjfsbm;
		this.zcth = zcth;
		this.sybmbm = sybmbm;
		this.glbmbm = glbmbm;
		this.zjcdbm = zjcdbm;
		this.hjn = hjn;
		this.hjy = hjy;
		this.ybyz = ybyz;
		this.bbyz = bbyz;
		this.fbyz = fbyz;
		this.gzzl = gzzl;
		this.syyx = syyx;
		this.ljzj = ljzj;
		this.ljgzl = ljgzl;
		this.jzzb = jzzb;
		this.yjtyf = yjtyf;
		this.ygzl = ygzl;
		this.dwzj = dwzj;
		this.jczl = jczl;
		this.jcz = jcz;
		this.yzkpbj = yzkpbj;
		this.zclbbm = zclbbm;
		this.syzkbm = syzkbm;
		this.jzfabm = jzfabm;
		this.xmdabm = xmdabm;
		this.gysbm = gysbm;
		this.ly = ly;
		this.yrje = yrje;
		this.yrljzj = yrljzj;
		this.yryz = yryz;
		this.cpuxh = cpuxh;
		this.bxq = bxq;
		this.bz = bz;
		this.clpzh = clpzh;
		this.dytdzsyqr = dytdzsyqr;
		this.fdjhm = fdjhm;
		this.fczhm = fczhm;
		this.jjmj = jjmj;
		this.je = je;
		this.jz = jz;
		this.jkpbh = jkpbh;
		this.lbbm = lbbm;
		this.lbmc = lbmc;
		this.nc = nc;
		this.nzyp = nzyp;
		this.pgqljzj = pgqljzj;
		this.pgqyz = pgqyz;
		this.qyrq = qyrq;
		this.qszm = qszm;
		this.qzsyz = qzsyz;
		this.smbxq = smbxq;
		this.sbxlh = sbxlh;
		this.sfjc = sfjc;
		this.sxbxq = sxbxq;
		this.tdzhm = tdzhm;
		this.wzyp = wzyp;
		this.xtxsq = xtxsq;
		this.ywdytd = ywdytd;
		this.yxtrry = yxtrry;
		this.yzje = yzje;
		this.yzjl = yzjl;
		this.zyzt = zyzt;
		this.zdmj = zdmj;
		this.zyyt = zyyt;
		this.zxrq = zxrq;
		this.zxmj = zxmj;
	}

	// Property accessors

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public String getBdh() {
		return this.bdh;
	}

	public void setBdh(String bdh) {
		this.bdh = bdh;
	}

	public String getDypk() {
		return this.dypk;
	}

	public void setDypk(String dypk) {
		this.dypk = dypk;
	}

	public String getFhxx() {
		return this.fhxx;
	}

	public void setFhxx(String fhxx) {
		this.fhxx = fhxx;
	}

	public String getErpzcbm() {
		return this.erpzcbm;
	}

	public void setErpzcbm(String erpzcbm) {
		this.erpzcbm = erpzcbm;
	}

	public String getSfbh() {
		return this.sfbh;
	}

	public void setSfbh(String sfbh) {
		this.sfbh = sfbh;
	}

	public String getErpkpbm() {
		return this.erpkpbm;
	}

	public void setErpkpbm(String erpkpbm) {
		this.erpkpbm = erpkpbm;
	}

	public String getFhbm() {
		return this.fhbm;
	}

	public void setFhbm(String fhbm) {
		this.fhbm = fhbm;
	}

	public String getKpid() {
		return this.kpid;
	}

	public void setKpid(String kpid) {
		this.kpid = kpid;
	}

	public String getGsbm() {
		return this.gsbm;
	}

	public void setGsbm(String gsbm) {
		this.gsbm = gsbm;
	}

	public String getZibm() {
		return this.zibm;
	}

	public void setZibm(String zibm) {
		this.zibm = zibm;
	}

	public String getZcmc() {
		return this.zcmc;
	}

	public void setZcmc(String zcmc) {
		this.zcmc = zcmc;
	}

	public String getKssyrq() {
		return this.kssyrq;
	}

	public void setKssyrq(String kssyrq) {
		this.kssyrq = kssyrq;
	}

	public String getBzmc() {
		return this.bzmc;
	}

	public void setBzmc(String bzmc) {
		this.bzmc = bzmc;
	}

	public String getBzcw() {
		return this.bzcw;
	}

	public void setBzcw(String bzcw) {
		this.bzcw = bzcw;
	}

	public String getLrrmc() {
		return this.lrrmc;
	}

	public void setLrrmc(String lrrmc) {
		this.lrrmc = lrrmc;
	}

	public String getLrrq() {
		return this.lrrq;
	}

	public void setLrrq(String lrrq) {
		this.lrrq = lrrq;
	}

	public String getSyrbm() {
		return this.syrbm;
	}

	public void setSyrbm(String syrbm) {
		this.syrbm = syrbm;
	}

	public String getGgxh() {
		return this.ggxh;
	}

	public void setGgxh(String ggxh) {
		this.ggxh = ggxh;
	}

	public String getCfdd() {
		return this.cfdd;
	}

	public void setCfdd(String cfdd) {
		this.cfdd = cfdd;
	}

	public String getGzldw() {
		return this.gzldw;
	}

	public void setGzldw(String gzldw) {
		this.gzldw = gzldw;
	}

	public String getZjfsbm() {
		return this.zjfsbm;
	}

	public void setZjfsbm(String zjfsbm) {
		this.zjfsbm = zjfsbm;
	}

	public String getZcth() {
		return this.zcth;
	}

	public void setZcth(String zcth) {
		this.zcth = zcth;
	}

	public String getSybmbm() {
		return this.sybmbm;
	}

	public void setSybmbm(String sybmbm) {
		this.sybmbm = sybmbm;
	}

	public String getGlbmbm() {
		return this.glbmbm;
	}

	public void setGlbmbm(String glbmbm) {
		this.glbmbm = glbmbm;
	}

	public String getZjcdbm() {
		return this.zjcdbm;
	}

	public void setZjcdbm(String zjcdbm) {
		this.zjcdbm = zjcdbm;
	}

	public String getHjn() {
		return this.hjn;
	}

	public void setHjn(String hjn) {
		this.hjn = hjn;
	}

	public String getHjy() {
		return this.hjy;
	}

	public void setHjy(String hjy) {
		this.hjy = hjy;
	}

	public String getYbyz() {
		return this.ybyz;
	}

	public void setYbyz(String ybyz) {
		this.ybyz = ybyz;
	}

	public String getBbyz() {
		return this.bbyz;
	}

	public void setBbyz(String bbyz) {
		this.bbyz = bbyz;
	}

	public String getFbyz() {
		return this.fbyz;
	}

	public void setFbyz(String fbyz) {
		this.fbyz = fbyz;
	}

	public String getGzzl() {
		return this.gzzl;
	}

	public void setGzzl(String gzzl) {
		this.gzzl = gzzl;
	}

	public String getSyyx() {
		return this.syyx;
	}

	public void setSyyx(String syyx) {
		this.syyx = syyx;
	}

	public String getLjzj() {
		return this.ljzj;
	}

	public void setLjzj(String ljzj) {
		this.ljzj = ljzj;
	}

	public String getLjgzl() {
		return this.ljgzl;
	}

	public void setLjgzl(String ljgzl) {
		this.ljgzl = ljgzl;
	}

	public String getJzzb() {
		return this.jzzb;
	}

	public void setJzzb(String jzzb) {
		this.jzzb = jzzb;
	}

	public String getYjtyf() {
		return this.yjtyf;
	}

	public void setYjtyf(String yjtyf) {
		this.yjtyf = yjtyf;
	}

	public String getYgzl() {
		return this.ygzl;
	}

	public void setYgzl(String ygzl) {
		this.ygzl = ygzl;
	}

	public String getDwzj() {
		return this.dwzj;
	}

	public void setDwzj(String dwzj) {
		this.dwzj = dwzj;
	}

	public String getJczl() {
		return this.jczl;
	}

	public void setJczl(String jczl) {
		this.jczl = jczl;
	}

	public String getJcz() {
		return this.jcz;
	}

	public void setJcz(String jcz) {
		this.jcz = jcz;
	}

	public String getYzkpbj() {
		return this.yzkpbj;
	}

	public void setYzkpbj(String yzkpbj) {
		this.yzkpbj = yzkpbj;
	}

	public String getZclbbm() {
		return this.zclbbm;
	}

	public void setZclbbm(String zclbbm) {
		this.zclbbm = zclbbm;
	}

	public String getSyzkbm() {
		return this.syzkbm;
	}

	public void setSyzkbm(String syzkbm) {
		this.syzkbm = syzkbm;
	}

	public String getJzfabm() {
		return this.jzfabm;
	}

	public void setJzfabm(String jzfabm) {
		this.jzfabm = jzfabm;
	}

	public String getXmdabm() {
		return this.xmdabm;
	}

	public void setXmdabm(String xmdabm) {
		this.xmdabm = xmdabm;
	}

	public String getGysbm() {
		return this.gysbm;
	}

	public void setGysbm(String gysbm) {
		this.gysbm = gysbm;
	}

	public String getLy() {
		return this.ly;
	}

	public void setLy(String ly) {
		this.ly = ly;
	}

	public String getYrje() {
		return this.yrje;
	}

	public void setYrje(String yrje) {
		this.yrje = yrje;
	}

	public String getYrljzj() {
		return this.yrljzj;
	}

	public void setYrljzj(String yrljzj) {
		this.yrljzj = yrljzj;
	}

	public String getYryz() {
		return this.yryz;
	}

	public void setYryz(String yryz) {
		this.yryz = yryz;
	}

	public String getCpuxh() {
		return this.cpuxh;
	}

	public void setCpuxh(String cpuxh) {
		this.cpuxh = cpuxh;
	}

	public String getBxq() {
		return this.bxq;
	}

	public void setBxq(String bxq) {
		this.bxq = bxq;
	}

	public String getBz() {
		return this.bz;
	}

	public void setBz(String bz) {
		this.bz = bz;
	}

	public String getClpzh() {
		return this.clpzh;
	}

	public void setClpzh(String clpzh) {
		this.clpzh = clpzh;
	}

	public String getDytdzsyqr() {
		return this.dytdzsyqr;
	}

	public void setDytdzsyqr(String dytdzsyqr) {
		this.dytdzsyqr = dytdzsyqr;
	}

	public String getFdjhm() {
		return this.fdjhm;
	}

	public void setFdjhm(String fdjhm) {
		this.fdjhm = fdjhm;
	}

	public String getFczhm() {
		return this.fczhm;
	}

	public void setFczhm(String fczhm) {
		this.fczhm = fczhm;
	}

	public String getJjmj() {
		return this.jjmj;
	}

	public void setJjmj(String jjmj) {
		this.jjmj = jjmj;
	}

	public String getJe() {
		return this.je;
	}

	public void setJe(String je) {
		this.je = je;
	}

	public String getJz() {
		return this.jz;
	}

	public void setJz(String jz) {
		this.jz = jz;
	}

	public String getJkpbh() {
		return this.jkpbh;
	}

	public void setJkpbh(String jkpbh) {
		this.jkpbh = jkpbh;
	}

	public String getLbbm() {
		return this.lbbm;
	}

	public void setLbbm(String lbbm) {
		this.lbbm = lbbm;
	}

	public String getLbmc() {
		return this.lbmc;
	}

	public void setLbmc(String lbmc) {
		this.lbmc = lbmc;
	}

	public String getNc() {
		return this.nc;
	}

	public void setNc(String nc) {
		this.nc = nc;
	}

	public String getNzyp() {
		return this.nzyp;
	}

	public void setNzyp(String nzyp) {
		this.nzyp = nzyp;
	}

	public String getPgqljzj() {
		return this.pgqljzj;
	}

	public void setPgqljzj(String pgqljzj) {
		this.pgqljzj = pgqljzj;
	}

	public String getPgqyz() {
		return this.pgqyz;
	}

	public void setPgqyz(String pgqyz) {
		this.pgqyz = pgqyz;
	}

	public String getQyrq() {
		return this.qyrq;
	}

	public void setQyrq(String qyrq) {
		this.qyrq = qyrq;
	}

	public String getQszm() {
		return this.qszm;
	}

	public void setQszm(String qszm) {
		this.qszm = qszm;
	}

	public String getQzsyz() {
		return this.qzsyz;
	}

	public void setQzsyz(String qzsyz) {
		this.qzsyz = qzsyz;
	}

	public String getSmbxq() {
		return this.smbxq;
	}

	public void setSmbxq(String smbxq) {
		this.smbxq = smbxq;
	}

	public String getSbxlh() {
		return this.sbxlh;
	}

	public void setSbxlh(String sbxlh) {
		this.sbxlh = sbxlh;
	}

	public String getSfjc() {
		return this.sfjc;
	}

	public void setSfjc(String sfjc) {
		this.sfjc = sfjc;
	}

	public String getSxbxq() {
		return this.sxbxq;
	}

	public void setSxbxq(String sxbxq) {
		this.sxbxq = sxbxq;
	}

	public String getTdzhm() {
		return this.tdzhm;
	}

	public void setTdzhm(String tdzhm) {
		this.tdzhm = tdzhm;
	}

	public String getWzyp() {
		return this.wzyp;
	}

	public void setWzyp(String wzyp) {
		this.wzyp = wzyp;
	}

	public String getXtxsq() {
		return this.xtxsq;
	}

	public void setXtxsq(String xtxsq) {
		this.xtxsq = xtxsq;
	}

	public String getYwdytd() {
		return this.ywdytd;
	}

	public void setYwdytd(String ywdytd) {
		this.ywdytd = ywdytd;
	}

	public String getYxtrry() {
		return this.yxtrry;
	}

	public void setYxtrry(String yxtrry) {
		this.yxtrry = yxtrry;
	}

	public String getYzje() {
		return this.yzje;
	}

	public void setYzje(String yzje) {
		this.yzje = yzje;
	}

	public String getYzjl() {
		return this.yzjl;
	}

	public void setYzjl(String yzjl) {
		this.yzjl = yzjl;
	}

	public String getZyzt() {
		return this.zyzt;
	}

	public void setZyzt(String zyzt) {
		this.zyzt = zyzt;
	}

	public String getZdmj() {
		return this.zdmj;
	}

	public void setZdmj(String zdmj) {
		this.zdmj = zdmj;
	}

	public String getZyyt() {
		return this.zyyt;
	}

	public void setZyyt(String zyyt) {
		this.zyyt = zyyt;
	}

	public String getZxrq() {
		return this.zxrq;
	}

	public void setZxrq(String zxrq) {
		this.zxrq = zxrq;
	}

	public String getZxmj() {
		return this.zxmj;
	}

	public void setZxmj(String zxmj) {
		this.zxmj = zxmj;
	}

	@Override
	public String getMid() {
		// TODO Auto-generated method stub
		return null;
	}

}