package com.tansun.eam2.jiekou.erp.model.bo;

import com.tansun.rdp4j.common.web.vo.CommonBO;

/**
 * ErpDateinfo generated by MyEclipse Persistence Tools
 */

public class ErpDateinfo extends CommonBO implements java.io.Serializable {

	// Fields

	private Long id;
	private String tablename;
	private String info;
	private String state;
	private String result;
	private String errordate;

	// Constructors

	/** default constructor */
	public ErpDateinfo() {
	}

	/** full constructor */
	public ErpDateinfo(String tablename, String info, String state,
			String result, String errordate) {
		this.tablename = tablename;
		this.info = info;
		this.state = state;
		this.result = result;
		this.errordate = errordate;
	}

	// Property accessors

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public String getTablename() {
		return this.tablename;
	}

	public void setTablename(String tablename) {
		this.tablename = tablename;
	}

	public String getInfo() {
		return this.info;
	}

	public void setInfo(String info) {
		this.info = info;
	}

	public String getState() {
		return this.state;
	}

	public void setState(String state) {
		this.state = state;
	}

	public String getResult() {
		return this.result;
	}

	public void setResult(String result) {
		this.result = result;
	}

	public String getErrordate() {
		return this.errordate;
	}

	public void setErrordate(String errordate) {
		this.errordate = errordate;
	}

	@Override
	public String getMid() {
		// TODO Auto-generated method stub
		return null;
	}

}