package com.tansun.eam2.jiekou.erp.model.bo;

import com.tansun.rdp4j.common.web.vo.CommonBO;

/**
 * ErpUsermap generated by MyEclipse Persistence Tools
 */

public class ErpUsermap extends CommonBO implements java.io.Serializable {

	// Fields

	private Long id;
	private String eamuser;
	private String erpuser;
	private String eamchina;

	// Constructors

	/** default constructor */
	public ErpUsermap() {
	}

	/** full constructor */
	public ErpUsermap(String eamuser, String erpuser, String eamchina) {
		this.eamuser = eamuser;
		this.erpuser = erpuser;
		this.eamchina = eamchina;
	}

	// Property accessors

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public String getEamuser() {
		return this.eamuser;
	}

	public void setEamuser(String eamuser) {
		this.eamuser = eamuser;
	}

	public String getErpuser() {
		return this.erpuser;
	}

	public void setErpuser(String erpuser) {
		this.erpuser = erpuser;
	}

	public String getEamchina() {
		return this.eamchina;
	}

	public void setEamchina(String eamchina) {
		this.eamchina = eamchina;
	}

	@Override
	public String getMid() {
		// TODO Auto-generated method stub
		return null;
	}

}