<link rel="stylesheet" type="text/css" href="<s:url value="/resource/js/DHtmlLayout/dhtmlxlayout.css" />">
<link rel="stylesheet" type="text/css" href="<s:url value="/resource/js/DHtmlLayout/skins/dhtmlxlayout_dhx_skyblue.css" />">
<script src="<s:url value="/resource/js/DHtmlLayout/dhtmlxcommon.js" />"></script>
<script src="<s:url value="/resource/js/DHtmlLayout/dhtmlxlayout.js" />"></script>
<script src="<s:url value="/resource/js/DHtmlLayout/dhtmlxcontainer.js" />"></script>