<%@page language="java" contentType="text/html;charset=UTF-8"%>
          <form id="exportExcelViaJqGridForm" name="exportExcelViaJqGridForm" action="/eam2/word.jspa?COMMAND=exportExcelViaJqGrid"  method="post">
             <input name="exportExcelTitle" type="hidden" value="" />
             <input name="exportExcelPath" type="hidden" value="" />
             <input name="exportExcelModel" type="hidden" value="" />
             <input name="exportExcelParams" type="hidden" value="" />
             <input name="exportExcelExcludeKeys" type="hidden" value="" />
          </form>