<script type="text/javascript" src="<s:url value="/resource/js/jquery/layout/complex.js" />"></script>
<script type="text/javascript" src="<s:url value="/resource/js/jquery/jquery.js" />"></script>
<script type="text/javascript" src="<s:url value="/resource/js/jquery/common.js" />"></script>
<script type="text/javascript" src="<s:url value="/resource/js/jquery/jquery.layout.js" />"></script>
<script type="text/javascript" src="<s:url value="/resource/js/jquery/layout/jquery.layout.js" />"></script>
<script type="text/javascript" src="<s:url value="/resource/js/jquery/jqueryui/jquery-ui.custom.min.js" />"></script>

<link rel="stylesheet" type="text/css" href="<s:url value="/resource/css/complex.css" />">
<link rel="stylesheet" type="text/css" href="<s:url value="/resource/js/jquery/jqueryui/css/cupertino/jquery-ui.custom.css" />">
<link rel="stylesheet" type="text/css" href="<s:url value="/resource/js/jquery/layout/complex.css" />">