package com.tansun.eam2.jiekou.erp.model;

/**
 * FanjsSenderp generated by MyEclipse Persistence Tools
 */

public class FanjsSenderp implements java.io.Serializable {

	// Fields

	private Long id;

	private String username;

	private String chinaname;

	private String cardname;

	private String wfCode;

	private String cardcode;

	private String saveaddress;

	private String typecode;

	private String managedep;

	private String userdep;

	private String ggboption;

	private String cardsm;

	// Constructors

	/** default constructor */
	public FanjsSenderp() {
	}

	/** full constructor */
	public FanjsSenderp(String username, String chinaname, String cardname,
			String wfCode, String cardcode, String saveaddress,
			String typecode, String managedep, String userdep,
			String ggboption, String cardsm) {
		this.username = username;
		this.chinaname = chinaname;
		this.cardname = cardname;
		this.wfCode = wfCode;
		this.cardcode = cardcode;
		this.saveaddress = saveaddress;
		this.typecode = typecode;
		this.managedep = managedep;
		this.userdep = userdep;
		this.ggboption = ggboption;
		this.cardsm = cardsm;
	}

	// Property accessors

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public String getChinaname() {
		return this.chinaname;
	}

	public void setChinaname(String chinaname) {
		this.chinaname = chinaname;
	}

	public String getCardname() {
		return this.cardname;
	}

	public void setCardname(String cardname) {
		this.cardname = cardname;
	}

	public String getWfCode() {
		return this.wfCode;
	}

	public void setWfCode(String wfCode) {
		this.wfCode = wfCode;
	}

	public String getCardcode() {
		return this.cardcode;
	}

	public void setCardcode(String cardcode) {
		this.cardcode = cardcode;
	}

	public String getSaveaddress() {
		return this.saveaddress;
	}

	public void setSaveaddress(String saveaddress) {
		this.saveaddress = saveaddress;
	}

	public String getTypecode() {
		return this.typecode;
	}

	public void setTypecode(String typecode) {
		this.typecode = typecode;
	}

	public String getManagedep() {
		return this.managedep;
	}

	public void setManagedep(String managedep) {
		this.managedep = managedep;
	}

	public String getUserdep() {
		return this.userdep;
	}

	public void setUserdep(String userdep) {
		this.userdep = userdep;
	}

	public String getGgboption() {
		return this.ggboption;
	}

	public void setGgboption(String ggboption) {
		this.ggboption = ggboption;
	}

	public String getCardsm() {
		return this.cardsm;
	}

	public void setCardsm(String cardsm) {
		this.cardsm = cardsm;
	}

}