package com.tansun.eam2.common.model.orm.bo;

import java.util.Date;

/**
 * CardAssetHistory generated by MyEclipse Persistence Tools
 */

public class CardAssetHistory extends com.tansun.rdp4j.common.web.vo.CommonBO
		implements java.io.Serializable {

	// Fields

	private static final long serialVersionUID = 8455058931110000285L;
	private String id;
	private String kpId;
	private String zcId;
	private Date gjksrq;
	private Date gjjsrq;
	private String dqgjzt;
	private String sfwzkp;
	private Date zkpszksrq;
	private Date zkpszjsrq;
	private String spzt;
	private String zczsbId;

	// Constructors

	/** default constructor */
	public CardAssetHistory() {
	}

	/** full constructor */
	public CardAssetHistory(String kpId, String zcId, Date gjksrq, Date gjjsrq,
			String dqgjzt, String sfwzkp, Date zkpszksrq, Date zkpszjsrq,
			String spzt) {
		this.kpId = kpId;
		this.zcId = zcId;
		this.gjksrq = gjksrq;
		this.gjjsrq = gjjsrq;
		this.dqgjzt = dqgjzt;
		this.sfwzkp = sfwzkp;
		this.zkpszksrq = zkpszksrq;
		this.zkpszjsrq = zkpszjsrq;
		this.spzt = spzt;
	}

	// Property accessors

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getKpId() {
		return this.kpId;
	}

	public void setKpId(String kpId) {
		this.kpId = kpId;
	}

	public String getZcId() {
		return this.zcId;
	}

	public void setZcId(String zcId) {
		this.zcId = zcId;
	}

	public Date getGjksrq() {
		return this.gjksrq;
	}

	public void setGjksrq(Date gjksrq) {
		this.gjksrq = gjksrq;
	}

	public Date getGjjsrq() {
		return this.gjjsrq;
	}

	public void setGjjsrq(Date gjjsrq) {
		this.gjjsrq = gjjsrq;
	}

	public String getDqgjzt() {
		return this.dqgjzt;
	}

	public void setDqgjzt(String dqgjzt) {
		this.dqgjzt = dqgjzt;
	}

	public String getSfwzkp() {
		return this.sfwzkp;
	}

	public void setSfwzkp(String sfwzkp) {
		this.sfwzkp = sfwzkp;
	}

	public Date getZkpszksrq() {
		return this.zkpszksrq;
	}

	public void setZkpszksrq(Date zkpszksrq) {
		this.zkpszksrq = zkpszksrq;
	}

	public Date getZkpszjsrq() {
		return this.zkpszjsrq;
	}

	public void setZkpszjsrq(Date zkpszjsrq) {
		this.zkpszjsrq = zkpszjsrq;
	}

	public String getSpzt() {
		return this.spzt;
	}

	public void setSpzt(String spzt) {
		this.spzt = spzt;
	}

	@Override
	public String getMid() {
		// TODO Auto-generated method stub
		return null;
	}

	public String getZczsbId() {
		return zczsbId;
	}

	public void setZczsbId(String zczsbId) {
		this.zczsbId = zczsbId;
	}

}