package com.tansun.eam2.common.model.orm.bo;

/**
 * Code generated by MyEclipse Persistence Tools
 */

public class Code extends com.tansun.rdp4j.common.web.vo.CommonBO implements
		java.io.Serializable {

	private static final long serialVersionUID = -8162237782895041L;
	private String id;
	private String codeType;
	private String codeName;
	private String codeKey;
	private String codeValue;
	private Long orderNumber;
	private String usable;
	private String codeTag;

	// Constructors

	/** default constructor */
	public Code() {
	}

	/** full constructor */
	public Code(String codeType, String codeName, String codeKey,
			String codeValue, Long orderNumber, String usable, String codeTag) {
		this.codeType = codeType;
		this.codeName = codeName;
		this.codeKey = codeKey;
		this.codeValue = codeValue;
		this.orderNumber = orderNumber;
		this.usable = usable;
		this.codeTag = codeTag;
	}

	// Property accessors

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getCodeType() {
		return this.codeType;
	}

	public void setCodeType(String codeType) {
		this.codeType = codeType;
	}

	public String getCodeName() {
		return this.codeName;
	}

	public void setCodeName(String codeName) {
		this.codeName = codeName;
	}

	public String getCodeKey() {
		return this.codeKey;
	}

	public void setCodeKey(String codeKey) {
		this.codeKey = codeKey;
	}

	public String getCodeValue() {
		return this.codeValue;
	}

	public void setCodeValue(String codeValue) {
		this.codeValue = codeValue;
	}

	public Long getOrderNumber() {
		return this.orderNumber;
	}

	public void setOrderNumber(Long orderNumber) {
		this.orderNumber = orderNumber;
	}

	public String getUsable() {
		return this.usable;
	}

	public void setUsable(String usable) {
		this.usable = usable;
	}

	public String getCodeTag() {
		return this.codeTag;
	}

	public void setCodeTag(String codeTag) {
		this.codeTag = codeTag;
	}

	@Override
	public String getMid() {
		// TODO Auto-generated method stub
		return null;
	}

}