package com.tansun.eam2.common.model.orm.bo;

/**
 * CzHgshXx generated by MyEclipse Persistence Tools
 */

public class CzHgshXx extends com.tansun.rdp4j.common.web.vo.CommonBO implements
		java.io.Serializable {

	private static final long serialVersionUID = -3991904043965351965L;
	private String id;
	private String cldId;
	private String bianhao;
	private String bmldspyj;
	private String pgbgzyxq;
	private String fgldspyj;
	private String wtdwsbwj;
	private String pgbgjshyj;
	private String ayqjxgg;
	private String btgfzq;
	private String gxtxgfzq;
	private String jbryjqxww;
	private String gsgf;
	private String nrqxwz;
	private String xmjbqk;
	private String pgjqsh;
	private String czfajfabj;
	private String czsy;
	private String czfy;
	private String bmyj;
	private String wzgfww;
	private String gsjzszq;
	private String ygyjycfyj;
	private String czfshg;
	private String czdjhg;
	private String czfyhg;
	private String sxfjqq;
	private String fjpgbgjshyj;
	private String ggym;
	private String fjwtdwsbwj;
	private String xmygwj;
	private String fjgsgf;
	private String ggnrgfwz;
	private String ggmzsxyq;
	private String shjl;

	// Constructors

	/** default constructor */
	public CzHgshXx() {
	}

	/** full constructor */
	public CzHgshXx(String cldId, String bianhao, String bmldspyj,
			String pgbgzyxq, String fgldspyj, String wtdwsbwj,
			String pgbgjshyj, String ayqjxgg, String btgfzq, String gxtxgfzq,
			String jbryjqxww, String gsgf, String nrqxwz, String xmjbqk,
			String pgjqsh, String czfajfabj, String czsy, String czfy,
			String bmyj, String wzgfww, String gsjzszq, String ygyjycfyj,
			String czfshg, String czdjhg, String czfyhg, String sxfjqq,
			String fjpgbgjshyj, String ggym, String fjwtdwsbwj, String xmygwj,
			String fjgsgf, String ggnrgfwz, String ggmzsxyq, String shjl) {
		this.cldId = cldId;
		this.bianhao = bianhao;
		this.bmldspyj = bmldspyj;
		this.pgbgzyxq = pgbgzyxq;
		this.fgldspyj = fgldspyj;
		this.wtdwsbwj = wtdwsbwj;
		this.pgbgjshyj = pgbgjshyj;
		this.ayqjxgg = ayqjxgg;
		this.btgfzq = btgfzq;
		this.gxtxgfzq = gxtxgfzq;
		this.jbryjqxww = jbryjqxww;
		this.gsgf = gsgf;
		this.nrqxwz = nrqxwz;
		this.xmjbqk = xmjbqk;
		this.pgjqsh = pgjqsh;
		this.czfajfabj = czfajfabj;
		this.czsy = czsy;
		this.czfy = czfy;
		this.bmyj = bmyj;
		this.wzgfww = wzgfww;
		this.gsjzszq = gsjzszq;
		this.ygyjycfyj = ygyjycfyj;
		this.czfshg = czfshg;
		this.czdjhg = czdjhg;
		this.czfyhg = czfyhg;
		this.sxfjqq = sxfjqq;
		this.fjpgbgjshyj = fjpgbgjshyj;
		this.ggym = ggym;
		this.fjwtdwsbwj = fjwtdwsbwj;
		this.xmygwj = xmygwj;
		this.fjgsgf = fjgsgf;
		this.ggnrgfwz = ggnrgfwz;
		this.ggmzsxyq = ggmzsxyq;
		this.shjl = shjl;
	}

	// Property accessors

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getCldId() {
		return this.cldId;
	}

	public void setCldId(String cldId) {
		this.cldId = cldId;
	}

	public String getBianhao() {
		return this.bianhao;
	}

	public void setBianhao(String bianhao) {
		this.bianhao = bianhao;
	}

	public String getBmldspyj() {
		return this.bmldspyj;
	}

	public void setBmldspyj(String bmldspyj) {
		this.bmldspyj = bmldspyj;
	}

	public String getPgbgzyxq() {
		return this.pgbgzyxq;
	}

	public void setPgbgzyxq(String pgbgzyxq) {
		this.pgbgzyxq = pgbgzyxq;
	}

	public String getFgldspyj() {
		return this.fgldspyj;
	}

	public void setFgldspyj(String fgldspyj) {
		this.fgldspyj = fgldspyj;
	}

	public String getWtdwsbwj() {
		return this.wtdwsbwj;
	}

	public void setWtdwsbwj(String wtdwsbwj) {
		this.wtdwsbwj = wtdwsbwj;
	}

	public String getPgbgjshyj() {
		return this.pgbgjshyj;
	}

	public void setPgbgjshyj(String pgbgjshyj) {
		this.pgbgjshyj = pgbgjshyj;
	}

	public String getAyqjxgg() {
		return this.ayqjxgg;
	}

	public void setAyqjxgg(String ayqjxgg) {
		this.ayqjxgg = ayqjxgg;
	}

	public String getBtgfzq() {
		return this.btgfzq;
	}

	public void setBtgfzq(String btgfzq) {
		this.btgfzq = btgfzq;
	}

	public String getGxtxgfzq() {
		return this.gxtxgfzq;
	}

	public void setGxtxgfzq(String gxtxgfzq) {
		this.gxtxgfzq = gxtxgfzq;
	}

	public String getJbryjqxww() {
		return this.jbryjqxww;
	}

	public void setJbryjqxww(String jbryjqxww) {
		this.jbryjqxww = jbryjqxww;
	}

	public String getGsgf() {
		return this.gsgf;
	}

	public void setGsgf(String gsgf) {
		this.gsgf = gsgf;
	}

	public String getNrqxwz() {
		return this.nrqxwz;
	}

	public void setNrqxwz(String nrqxwz) {
		this.nrqxwz = nrqxwz;
	}

	public String getXmjbqk() {
		return this.xmjbqk;
	}

	public void setXmjbqk(String xmjbqk) {
		this.xmjbqk = xmjbqk;
	}

	public String getPgjqsh() {
		return this.pgjqsh;
	}

	public void setPgjqsh(String pgjqsh) {
		this.pgjqsh = pgjqsh;
	}

	public String getCzfajfabj() {
		return this.czfajfabj;
	}

	public void setCzfajfabj(String czfajfabj) {
		this.czfajfabj = czfajfabj;
	}

	public String getCzsy() {
		return this.czsy;
	}

	public void setCzsy(String czsy) {
		this.czsy = czsy;
	}

	public String getCzfy() {
		return this.czfy;
	}

	public void setCzfy(String czfy) {
		this.czfy = czfy;
	}

	public String getBmyj() {
		return this.bmyj;
	}

	public void setBmyj(String bmyj) {
		this.bmyj = bmyj;
	}

	public String getWzgfww() {
		return this.wzgfww;
	}

	public void setWzgfww(String wzgfww) {
		this.wzgfww = wzgfww;
	}

	public String getGsjzszq() {
		return this.gsjzszq;
	}

	public void setGsjzszq(String gsjzszq) {
		this.gsjzszq = gsjzszq;
	}

	public String getYgyjycfyj() {
		return this.ygyjycfyj;
	}

	public void setYgyjycfyj(String ygyjycfyj) {
		this.ygyjycfyj = ygyjycfyj;
	}

	public String getCzfshg() {
		return this.czfshg;
	}

	public void setCzfshg(String czfshg) {
		this.czfshg = czfshg;
	}

	public String getCzdjhg() {
		return this.czdjhg;
	}

	public void setCzdjhg(String czdjhg) {
		this.czdjhg = czdjhg;
	}

	public String getCzfyhg() {
		return this.czfyhg;
	}

	public void setCzfyhg(String czfyhg) {
		this.czfyhg = czfyhg;
	}

	public String getSxfjqq() {
		return this.sxfjqq;
	}

	public void setSxfjqq(String sxfjqq) {
		this.sxfjqq = sxfjqq;
	}

	public String getFjpgbgjshyj() {
		return this.fjpgbgjshyj;
	}

	public void setFjpgbgjshyj(String fjpgbgjshyj) {
		this.fjpgbgjshyj = fjpgbgjshyj;
	}

	public String getGgym() {
		return this.ggym;
	}

	public void setGgym(String ggym) {
		this.ggym = ggym;
	}

	public String getFjwtdwsbwj() {
		return this.fjwtdwsbwj;
	}

	public void setFjwtdwsbwj(String fjwtdwsbwj) {
		this.fjwtdwsbwj = fjwtdwsbwj;
	}

	public String getXmygwj() {
		return this.xmygwj;
	}

	public void setXmygwj(String xmygwj) {
		this.xmygwj = xmygwj;
	}

	public String getFjgsgf() {
		return this.fjgsgf;
	}

	public void setFjgsgf(String fjgsgf) {
		this.fjgsgf = fjgsgf;
	}

	public String getGgnrgfwz() {
		return this.ggnrgfwz;
	}

	public void setGgnrgfwz(String ggnrgfwz) {
		this.ggnrgfwz = ggnrgfwz;
	}

	public String getGgmzsxyq() {
		return this.ggmzsxyq;
	}

	public void setGgmzsxyq(String ggmzsxyq) {
		this.ggmzsxyq = ggmzsxyq;
	}

	public String getShjl() {
		return this.shjl;
	}

	public void setShjl(String shjl) {
		this.shjl = shjl;
	}

	@Override
	public String getMid() {
		// TODO Auto-generated method stub
		return null;
	}

}