package com.tansun.eam2.common.model.orm.bo;

import java.util.Date;

/**
 * CzHyxx generated by MyEclipse Persistence Tools
 */

public class CzHyxx extends com.tansun.rdp4j.common.web.vo.CommonBO implements
		java.io.Serializable {

	private static final long serialVersionUID = 7742061454427123346L;
	private String id;
	private Date spsj;
	private String CSpfs;
	private String hycs;
	private String spzcr;
	private String zcrxm;
	private String spwy;
	private String hbr;
	private String hbrxm;
	private String hyjyzlr;
	private String hyjyzlrxm;
	private String spzt;
	private String hydd;
	private String lcId;
	private String ngbm;
	private String ngbmmc;
	private String hyjyzlrbmid;
	private String hyjyzlrbmmc;
	private String zcrbmid;
	private String zcrbmmc;
	private String hylx;
	private String sffscl;

	// Constructors

	public String getSffscl() {
		return sffscl;
	}

	public void setSffscl(String sffscl) {
		this.sffscl = sffscl;
	}

	/** default constructor */
	public CzHyxx() {
	}

	/** full constructor */
	public CzHyxx(Date spsj, String CSpfs, String hycs, String spzcr,
			String zcrxm, String spwy, String hbr, String hbrxm,
			String hyjyzlr, String hyjyzlrxm, String spzt, String hydd,
			String lcId, String ngbm, String ngbmmc, String hyjyzlrbmid,
			String hyjyzlrbmmc, String zcrbmid, String zcrbmmc, String hylx) {
		this.spsj = spsj;
		this.CSpfs = CSpfs;
		this.hycs = hycs;
		this.spzcr = spzcr;
		this.zcrxm = zcrxm;
		this.spwy = spwy;
		this.hbr = hbr;
		this.hbrxm = hbrxm;
		this.hyjyzlr = hyjyzlr;
		this.hyjyzlrxm = hyjyzlrxm;
		this.spzt = spzt;
		this.hydd = hydd;
		this.lcId = lcId;
		this.ngbm = ngbm;
		this.ngbmmc = ngbmmc;
		this.hyjyzlrbmid = hyjyzlrbmid;
		this.hyjyzlrbmmc = hyjyzlrbmmc;
		this.zcrbmid = zcrbmid;
		this.zcrbmmc = zcrbmmc;
		this.hylx = hylx;
	}

	// Property accessors

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public Date getSpsj() {
		return this.spsj;
	}

	public void setSpsj(Date spsj) {
		this.spsj = spsj;
	}

	public String getCSpfs() {
		return this.CSpfs;
	}

	public void setCSpfs(String CSpfs) {
		this.CSpfs = CSpfs;
	}

	public String getHycs() {
		return this.hycs;
	}

	public void setHycs(String hycs) {
		this.hycs = hycs;
	}

	public String getSpzcr() {
		return this.spzcr;
	}

	public void setSpzcr(String spzcr) {
		this.spzcr = spzcr;
	}

	public String getZcrxm() {
		return this.zcrxm;
	}

	public void setZcrxm(String zcrxm) {
		this.zcrxm = zcrxm;
	}

	public String getSpwy() {
		return this.spwy;
	}

	public void setSpwy(String spwy) {
		this.spwy = spwy;
	}

	public String getHbr() {
		return this.hbr;
	}

	public void setHbr(String hbr) {
		this.hbr = hbr;
	}

	public String getHbrxm() {
		return this.hbrxm;
	}

	public void setHbrxm(String hbrxm) {
		this.hbrxm = hbrxm;
	}

	public String getHyjyzlr() {
		return this.hyjyzlr;
	}

	public void setHyjyzlr(String hyjyzlr) {
		this.hyjyzlr = hyjyzlr;
	}

	public String getHyjyzlrxm() {
		return this.hyjyzlrxm;
	}

	public void setHyjyzlrxm(String hyjyzlrxm) {
		this.hyjyzlrxm = hyjyzlrxm;
	}

	public String getSpzt() {
		return this.spzt;
	}

	public void setSpzt(String spzt) {
		this.spzt = spzt;
	}

	public String getHydd() {
		return this.hydd;
	}

	public void setHydd(String hydd) {
		this.hydd = hydd;
	}

	public String getLcId() {
		return this.lcId;
	}

	public void setLcId(String lcId) {
		this.lcId = lcId;
	}

	public String getNgbm() {
		return this.ngbm;
	}

	public void setNgbm(String ngbm) {
		this.ngbm = ngbm;
	}

	public String getNgbmmc() {
		return this.ngbmmc;
	}

	public void setNgbmmc(String ngbmmc) {
		this.ngbmmc = ngbmmc;
	}

	public String getHyjyzlrbmid() {
		return this.hyjyzlrbmid;
	}

	public void setHyjyzlrbmid(String hyjyzlrbmid) {
		this.hyjyzlrbmid = hyjyzlrbmid;
	}

	public String getHyjyzlrbmmc() {
		return this.hyjyzlrbmmc;
	}

	public void setHyjyzlrbmmc(String hyjyzlrbmmc) {
		this.hyjyzlrbmmc = hyjyzlrbmmc;
	}

	public String getZcrbmid() {
		return this.zcrbmid;
	}

	public void setZcrbmid(String zcrbmid) {
		this.zcrbmid = zcrbmid;
	}

	public String getZcrbmmc() {
		return this.zcrbmmc;
	}

	public void setZcrbmmc(String zcrbmmc) {
		this.zcrbmmc = zcrbmmc;
	}

	public String getHylx() {
		return this.hylx;
	}

	public void setHylx(String hylx) {
		this.hylx = hylx;
	}

	@Override
	public String getMid() {
		// TODO Auto-generated method stub
		return null;
	}

}