package com.tansun.eam2.common.model.orm.bo;

import java.util.Date;

/**
 * CzPgscZskwhCld generated by MyEclipse Persistence Tools
 */

public class CzPgscZskwhCld extends com.tansun.rdp4j.common.web.vo.CommonBO
		implements java.io.Serializable {

	private static final long serialVersionUID = -2178528719257298982L;
	private String id;
	private String liuchengid;
	private String biaoti;
	private String bianhao;
	private String jhcd;
	private String nigaoren;
	private String nigaorenxm;
	private String ngbm;
	private String ngbmmc;
	private String lxdh;
	private String blbm;
	private String blbmbh;
	private Date ngrq;
	private String CBglx;
	private Long lssccs;
	private String pgjg;
	private Date pgjzr;
	private Double pgzz;
	private Double zczmjz;
	private Double zjz;
	private Double zjfd;
	private Double zczmyz;
	private String pgmd;
	private Date scsj;
	private Date bccltjsj;
	private String CScjl;
	private String cldzt;
	private String scsccldId;
	private String lcmc;
	private String pgzclb;
	private Date fblsj;
	private Double jzrzmjz;    

	// Constructors

	public Double getZczmyz() {
		return zczmyz;
	}

	public void setZczmyz(Double zczmyz) {
		this.zczmyz = zczmyz;
	}

	/** default constructor */
	public CzPgscZskwhCld() {
	}

	/** full constructor */
	public CzPgscZskwhCld(String liuchengid, String biaoti, String bianhao,
			String jhcd, String nigaoren, String nigaorenxm, String ngbm,
			String ngbmmc, String lxdh, String blbm, String blbmbh, Date ngrq,
			String CBglx, Long lssccs, String pgjg, Date pgjzr, Double pgzz,
			Double zczmjz, Double zjz, Double zjfd, String pgmd, Date scsj,
			Date bccltjsj, String CScjl, String cldzt, String scsccldId,
			String lcmc, String pgzclb, Date fblsj, Double jzrzmjz) {
		this.liuchengid = liuchengid;
		this.biaoti = biaoti;
		this.bianhao = bianhao;
		this.jhcd = jhcd;
		this.nigaoren = nigaoren;
		this.nigaorenxm = nigaorenxm;
		this.ngbm = ngbm;
		this.ngbmmc = ngbmmc;
		this.lxdh = lxdh;
		this.blbm = blbm;
		this.blbmbh = blbmbh;
		this.ngrq = ngrq;
		this.CBglx = CBglx;
		this.lssccs = lssccs;
		this.pgjg = pgjg;
		this.pgjzr = pgjzr;
		this.pgzz = pgzz;
		this.zczmjz = zczmjz;
		this.zjz = zjz;
		this.zjfd = zjfd;
		this.pgmd = pgmd;
		this.scsj = scsj;
		this.bccltjsj = bccltjsj;
		this.CScjl = CScjl;
		this.cldzt = cldzt;
		this.scsccldId = scsccldId;
		this.lcmc = lcmc;
		this.pgzclb = pgzclb;
		this.fblsj = fblsj;
		this.jzrzmjz = jzrzmjz;
	}

	// Property accessors

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getLiuchengid() {
		return this.liuchengid;
	}

	public void setLiuchengid(String liuchengid) {
		this.liuchengid = liuchengid;
	}

	public String getBiaoti() {
		return this.biaoti;
	}

	public void setBiaoti(String biaoti) {
		this.biaoti = biaoti;
	}

	public String getBianhao() {
		return this.bianhao;
	}

	public void setBianhao(String bianhao) {
		this.bianhao = bianhao;
	}

	public String getJhcd() {
		return this.jhcd;
	}

	public void setJhcd(String jhcd) {
		this.jhcd = jhcd;
	}

	public String getNigaoren() {
		return this.nigaoren;
	}

	public void setNigaoren(String nigaoren) {
		this.nigaoren = nigaoren;
	}

	public String getNigaorenxm() {
		return this.nigaorenxm;
	}

	public void setNigaorenxm(String nigaorenxm) {
		this.nigaorenxm = nigaorenxm;
	}

	public String getNgbm() {
		return this.ngbm;
	}

	public void setNgbm(String ngbm) {
		this.ngbm = ngbm;
	}

	public String getNgbmmc() {
		return this.ngbmmc;
	}

	public void setNgbmmc(String ngbmmc) {
		this.ngbmmc = ngbmmc;
	}

	public String getLxdh() {
		return this.lxdh;
	}

	public void setLxdh(String lxdh) {
		this.lxdh = lxdh;
	}

	public String getBlbm() {
		return this.blbm;
	}

	public void setBlbm(String blbm) {
		this.blbm = blbm;
	}

	public String getBlbmbh() {
		return this.blbmbh;
	}

	public void setBlbmbh(String blbmbh) {
		this.blbmbh = blbmbh;
	}

	public Date getNgrq() {
		return this.ngrq;
	}

	public void setNgrq(Date ngrq) {
		this.ngrq = ngrq;
	}

	public String getCBglx() {
		return this.CBglx;
	}

	public void setCBglx(String CBglx) {
		this.CBglx = CBglx;
	}

	public Long getLssccs() {
		return this.lssccs;
	}

	public void setLssccs(Long lssccs) {
		this.lssccs = lssccs;
	}

	public String getPgjg() {
		return this.pgjg;
	}

	public void setPgjg(String pgjg) {
		this.pgjg = pgjg;
	}

	public Date getPgjzr() {
		return this.pgjzr;
	}

	public void setPgjzr(Date pgjzr) {
		this.pgjzr = pgjzr;
	}

	public Double getPgzz() {
		return this.pgzz;
	}

	public void setPgzz(Double pgzz) {
		this.pgzz = pgzz;
	}

	public Double getZczmjz() {
		return this.zczmjz;
	}

	public void setZczmjz(Double zczmjz) {
		this.zczmjz = zczmjz;
	}

	public Double getZjz() {
		return this.zjz;
	}

	public void setZjz(Double zjz) {
		this.zjz = zjz;
	}

	public Double getZjfd() {
		return this.zjfd;
	}

	public void setZjfd(Double zjfd) {
		this.zjfd = zjfd;
	}

	public String getPgmd() {
		return this.pgmd;
	}

	public void setPgmd(String pgmd) {
		this.pgmd = pgmd;
	}

	public Date getScsj() {
		return this.scsj;
	}

	public void setScsj(Date scsj) {
		this.scsj = scsj;
	}

	public Date getBccltjsj() {
		return this.bccltjsj;
	}

	public void setBccltjsj(Date bccltjsj) {
		this.bccltjsj = bccltjsj;
	}

	public String getCScjl() {
		return this.CScjl;
	}

	public void setCScjl(String CScjl) {
		this.CScjl = CScjl;
	}

	public String getCldzt() {
		return this.cldzt;
	}

	public void setCldzt(String cldzt) {
		this.cldzt = cldzt;
	}

	public String getScsccldId() {
		return this.scsccldId;
	}

	public void setScsccldId(String scsccldId) {
		this.scsccldId = scsccldId;
	}

	public String getLcmc() {
		return this.lcmc;
	}

	public void setLcmc(String lcmc) {
		this.lcmc = lcmc;
	}

	public String getPgzclb() {
		return this.pgzclb;
	}

	public void setPgzclb(String pgzclb) {
		this.pgzclb = pgzclb;
	}

	public Date getFblsj() {
		return this.fblsj;
	}

	public void setFblsj(Date fblsj) {
		this.fblsj = fblsj;
	}
	
	public Double getJzrzmjz() {
		return jzrzmjz;
	}

	public void setJzrzmjz(Double jzrzmjz) {
		this.jzrzmjz = jzrzmjz;
	}

	@Override
	public String getMid() {
		return null;
	}

}