package com.tansun.eam2.common.model.orm.bo;

import java.util.Date;

/**
 * CzPgscSjk generated by MyEclipse Persistence Tools
 */

public class CzPgscSjk extends com.tansun.rdp4j.common.web.vo.CommonBO
		implements java.io.Serializable {

	private static final long serialVersionUID = -1776564822063958324L;
	private String id;
	private String lxdh;
	private Date sbsj;
	private String jingbanren;
	private Date bctjrq;
	private String scjl;
	private Date cjsj;
	private String bianhao;
	private String scxm;
	private String scyd;
	private String jtyj;
	private Long yjts;
	private String biaoti;
	private String pgjg;
	private String CBglx;
	private String shengfen;
	private String kpbh;
	private String zcmc;
	private String zclb;
	private Date jizhunri;
	private String mudi;
	private String fangfa;
	private String jzlb;
	private Double jzrzmyz;
	private Double jzrzmjz;
	private Double jzrjzczmz;
	private Double pgz;
	private Double pgzjz;
	private Double zjfd;
	private String spjg;
	private Date spsj;
	private String spwyj;
	private String beizhu;

	// Constructors

	/** default constructor */
	public CzPgscSjk() {
	}

	/** full constructor */
	public CzPgscSjk(String lxdh, Date sbsj, String jingbanren, Date bctjrq,
			String scjl, Date cjsj, String bianhao, String scxm, String scyd,
			String jtyj, Long yjts, String biaoti, String pgjg, String CBglx,
			String shengfen, String kpbh, String zcmc, String zclb,
			Date jizhunri, String mudi, String fangfa, String jzlb,
			Double jzrzmyz, Double jzrzmjz, Double jzrjzczmz, Double pgz,
			Double pgzjz, Double zjfd, String spjg, Date spsj, String spwyj,
			String beizhu) {
		this.lxdh = lxdh;
		this.sbsj = sbsj;
		this.jingbanren = jingbanren;
		this.bctjrq = bctjrq;
		this.scjl = scjl;
		this.cjsj = cjsj;
		this.bianhao = bianhao;
		this.scxm = scxm;
		this.scyd = scyd;
		this.jtyj = jtyj;
		this.yjts = yjts;
		this.biaoti = biaoti;
		this.pgjg = pgjg;
		this.CBglx = CBglx;
		this.shengfen = shengfen;
		this.kpbh = kpbh;
		this.zcmc = zcmc;
		this.zclb = zclb;
		this.jizhunri = jizhunri;
		this.mudi = mudi;
		this.fangfa = fangfa;
		this.jzlb = jzlb;
		this.jzrzmyz = jzrzmyz;
		this.jzrzmjz = jzrzmjz;
		this.jzrjzczmz = jzrjzczmz;
		this.pgz = pgz;
		this.pgzjz = pgzjz;
		this.zjfd = zjfd;
		this.spjg = spjg;
		this.spsj = spsj;
		this.spwyj = spwyj;
		this.beizhu = beizhu;
	}

	// Property accessors

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getLxdh() {
		return this.lxdh;
	}

	public void setLxdh(String lxdh) {
		this.lxdh = lxdh;
	}

	public Date getSbsj() {
		return this.sbsj;
	}

	public void setSbsj(Date sbsj) {
		this.sbsj = sbsj;
	}

	public String getJingbanren() {
		return this.jingbanren;
	}

	public void setJingbanren(String jingbanren) {
		this.jingbanren = jingbanren;
	}

	public Date getBctjrq() {
		return this.bctjrq;
	}

	public void setBctjrq(Date bctjrq) {
		this.bctjrq = bctjrq;
	}

	public String getScjl() {
		return this.scjl;
	}

	public void setScjl(String scjl) {
		this.scjl = scjl;
	}

	public Date getCjsj() {
		return this.cjsj;
	}

	public void setCjsj(Date cjsj) {
		this.cjsj = cjsj;
	}

	public String getBianhao() {
		return this.bianhao;
	}

	public void setBianhao(String bianhao) {
		this.bianhao = bianhao;
	}

	public String getScxm() {
		return this.scxm;
	}

	public void setScxm(String scxm) {
		this.scxm = scxm;
	}

	public String getScyd() {
		return this.scyd;
	}

	public void setScyd(String scyd) {
		this.scyd = scyd;
	}

	public String getJtyj() {
		return this.jtyj;
	}

	public void setJtyj(String jtyj) {
		this.jtyj = jtyj;
	}

	public Long getYjts() {
		return this.yjts;
	}

	public void setYjts(Long yjts) {
		this.yjts = yjts;
	}

	public String getBiaoti() {
		return this.biaoti;
	}

	public void setBiaoti(String biaoti) {
		this.biaoti = biaoti;
	}

	public String getPgjg() {
		return this.pgjg;
	}

	public void setPgjg(String pgjg) {
		this.pgjg = pgjg;
	}

	public String getCBglx() {
		return this.CBglx;
	}

	public void setCBglx(String CBglx) {
		this.CBglx = CBglx;
	}

	public String getShengfen() {
		return this.shengfen;
	}

	public void setShengfen(String shengfen) {
		this.shengfen = shengfen;
	}

	public String getKpbh() {
		return this.kpbh;
	}

	public void setKpbh(String kpbh) {
		this.kpbh = kpbh;
	}

	public String getZcmc() {
		return this.zcmc;
	}

	public void setZcmc(String zcmc) {
		this.zcmc = zcmc;
	}

	public String getZclb() {
		return this.zclb;
	}

	public void setZclb(String zclb) {
		this.zclb = zclb;
	}

	public Date getJizhunri() {
		return this.jizhunri;
	}

	public void setJizhunri(Date jizhunri) {
		this.jizhunri = jizhunri;
	}

	public String getMudi() {
		return this.mudi;
	}

	public void setMudi(String mudi) {
		this.mudi = mudi;
	}

	public String getFangfa() {
		return this.fangfa;
	}

	public void setFangfa(String fangfa) {
		this.fangfa = fangfa;
	}

	public String getJzlb() {
		return this.jzlb;
	}

	public void setJzlb(String jzlb) {
		this.jzlb = jzlb;
	}

	public Double getJzrzmyz() {
		return this.jzrzmyz;
	}

	public void setJzrzmyz(Double jzrzmyz) {
		this.jzrzmyz = jzrzmyz;
	}

	public Double getJzrzmjz() {
		return this.jzrzmjz;
	}

	public void setJzrzmjz(Double jzrzmjz) {
		this.jzrzmjz = jzrzmjz;
	}

	public Double getJzrjzczmz() {
		return this.jzrjzczmz;
	}

	public void setJzrjzczmz(Double jzrjzczmz) {
		this.jzrjzczmz = jzrjzczmz;
	}

	public Double getPgz() {
		return this.pgz;
	}

	public void setPgz(Double pgz) {
		this.pgz = pgz;
	}

	public Double getPgzjz() {
		return this.pgzjz;
	}

	public void setPgzjz(Double pgzjz) {
		this.pgzjz = pgzjz;
	}

	public Double getZjfd() {
		return this.zjfd;
	}

	public void setZjfd(Double zjfd) {
		this.zjfd = zjfd;
	}

	public String getSpjg() {
		return this.spjg;
	}

	public void setSpjg(String spjg) {
		this.spjg = spjg;
	}

	public Date getSpsj() {
		return this.spsj;
	}

	public void setSpsj(Date spsj) {
		this.spsj = spsj;
	}

	public String getSpwyj() {
		return this.spwyj;
	}

	public void setSpwyj(String spwyj) {
		this.spwyj = spwyj;
	}

	public String getBeizhu() {
		return this.beizhu;
	}

	public void setBeizhu(String beizhu) {
		this.beizhu = beizhu;
	}

	@Override
	public String getMid() {
		// TODO Auto-generated method stub
		return null;
	}

}