package com.tansun.eam2.common.model.orm.bo;

import java.util.Date;

/**
 * CzXmja generated by MyEclipse Persistence Tools
 */

public class CzXmja extends com.tansun.rdp4j.common.web.vo.CommonBO implements
		java.io.Serializable {

	private static final long serialVersionUID = -8104409309066160799L;
	private String id;
	private String lcId;
	private String bianhao;
	private String biaoti;
	private String jhcd;
	private String ngbmmc;
	private String ngbm;
	private String ngrxm;
	private String ngr;
	private Date ngrq;
	private String lxdh;
	private String beizhu;

	// Constructors

	/** default constructor */
	public CzXmja() {
	}

	/** full constructor */
	public CzXmja(String lcId, String bianhao, String biaoti, String jhcd,
			String ngbmmc, String ngbm, String ngrxm, String ngr, Date ngrq,
			String lxdh, String beizhu) {
		this.lcId = lcId;
		this.bianhao = bianhao;
		this.biaoti = biaoti;
		this.jhcd = jhcd;
		this.ngbmmc = ngbmmc;
		this.ngbm = ngbm;
		this.ngrxm = ngrxm;
		this.ngr = ngr;
		this.ngrq = ngrq;
		this.lxdh = lxdh;
		this.beizhu = beizhu;
	}

	// Property accessors

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getLcId() {
		return this.lcId;
	}

	public void setLcId(String lcId) {
		this.lcId = lcId;
	}

	public String getBianhao() {
		return this.bianhao;
	}

	public void setBianhao(String bianhao) {
		this.bianhao = bianhao;
	}

	public String getBiaoti() {
		return this.biaoti;
	}

	public void setBiaoti(String biaoti) {
		this.biaoti = biaoti;
	}

	public String getJhcd() {
		return this.jhcd;
	}

	public void setJhcd(String jhcd) {
		this.jhcd = jhcd;
	}

	public String getNgbmmc() {
		return this.ngbmmc;
	}

	public void setNgbmmc(String ngbmmc) {
		this.ngbmmc = ngbmmc;
	}

	public String getNgbm() {
		return this.ngbm;
	}

	public void setNgbm(String ngbm) {
		this.ngbm = ngbm;
	}

	public String getNgrxm() {
		return this.ngrxm;
	}

	public void setNgrxm(String ngrxm) {
		this.ngrxm = ngrxm;
	}

	public String getNgr() {
		return this.ngr;
	}

	public void setNgr(String ngr) {
		this.ngr = ngr;
	}

	public Date getNgrq() {
		return this.ngrq;
	}

	public void setNgrq(Date ngrq) {
		this.ngrq = ngrq;
	}

	public String getLxdh() {
		return this.lxdh;
	}

	public void setLxdh(String lxdh) {
		this.lxdh = lxdh;
	}

	public String getBeizhu() {
		return this.beizhu;
	}

	public void setBeizhu(String beizhu) {
		this.beizhu = beizhu;
	}

	@Override
	public String getMid() {
		// TODO Auto-generated method stub
		return null;
	}

}