package com.tansun.eam2.common.model.orm.bo;

import java.util.Date;

/**
 * CzXmXx generated by MyEclipse Persistence Tools
 */

public class CzXmXx extends com.tansun.rdp4j.common.web.vo.CommonBO implements
		java.io.Serializable {

	private static final long serialVersionUID = 8174177272517530768L;
	private String id;
	private String bianhao;
	private String czxmmc;
	private String hbr;
	private String hbrxm;
	private String jcslxr;
	private String jcslxrxm;
	private String yjhzr;
	private String yjhzrxm;
	private String hyId;
	private String spjl;
	private String sfba;
	private String zhuangtai;
	private String fenlei;
	private String fwwh;
	private String slxh;
	private Date sbrq;
	private String cldId;
	private String xmlsb;
	private String jacldId;
	private String czsx;
	
	// Constructors

	public String getCzsx() {
		return czsx;
	}

	public void setCzsx(String czsx) {
		this.czsx = czsx;
	}

	public String getCldId() {
		return cldId;
	}

	public void setCldId(String cldId) {
		this.cldId = cldId;
	}

	/** default constructor */
	public CzXmXx() {
	}

	/** full constructor */
	public CzXmXx(String bianhao, String czxmmc, String hbr, String hbrxm,
			String jcslxr, String jcslxrxm, String yjhzr, String yjhzrxm,
			String hyId, String spjl, String sfba, String zhuangtai,
			String fenlei, String fwwh, String slxh, Date sbrq,String cldId,
			String xmlsb,String jacldId,String czsx) {
		this.bianhao = bianhao;
		this.czxmmc = czxmmc;
		this.hbr = hbr;
		this.hbrxm = hbrxm;
		this.jcslxr = jcslxr;
		this.jcslxrxm = jcslxrxm;
		this.yjhzr = yjhzr;
		this.yjhzrxm = yjhzrxm;
		this.hyId = hyId;
		this.spjl = spjl;
		this.sfba = sfba;
		this.zhuangtai = zhuangtai;
		this.fenlei = fenlei;
		this.fwwh = fwwh;
		this.slxh = slxh;
		this.sbrq = sbrq;
		this.cldId = cldId;
		this.xmlsb = xmlsb;
		this.jacldId = jacldId;
		this.czsx = czsx;
	}

	// Property accessors

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getBianhao() {
		return this.bianhao;
	}

	public void setBianhao(String bianhao) {
		this.bianhao = bianhao;
	}

	public String getCzxmmc() {
		return this.czxmmc;
	}

	public void setCzxmmc(String czxmmc) {
		this.czxmmc = czxmmc;
	}

	public String getHbr() {
		return this.hbr;
	}

	public void setHbr(String hbr) {
		this.hbr = hbr;
	}

	public String getHbrxm() {
		return this.hbrxm;
	}

	public void setHbrxm(String hbrxm) {
		this.hbrxm = hbrxm;
	}

	public String getJcslxr() {
		return this.jcslxr;
	}

	public void setJcslxr(String jcslxr) {
		this.jcslxr = jcslxr;
	}

	public String getJcslxrxm() {
		return this.jcslxrxm;
	}

	public void setJcslxrxm(String jcslxrxm) {
		this.jcslxrxm = jcslxrxm;
	}

	public String getYjhzr() {
		return this.yjhzr;
	}

	public void setYjhzr(String yjhzr) {
		this.yjhzr = yjhzr;
	}

	public String getYjhzrxm() {
		return this.yjhzrxm;
	}

	public void setYjhzrxm(String yjhzrxm) {
		this.yjhzrxm = yjhzrxm;
	}

	public String getHyId() {
		return this.hyId;
	}

	public void setHyId(String hyId) {
		this.hyId = hyId;
	}

	public String getSpjl() {
		return this.spjl;
	}

	public void setSpjl(String spjl) {
		this.spjl = spjl;
	}

	public String getSfba() {
		return this.sfba;
	}

	public void setSfba(String sfba) {
		this.sfba = sfba;
	}

	public String getZhuangtai() {
		return this.zhuangtai;
	}

	public void setZhuangtai(String zhuangtai) {
		this.zhuangtai = zhuangtai;
	}

	public String getFenlei() {
		return this.fenlei;
	}

	public void setFenlei(String fenlei) {
		this.fenlei = fenlei;
	}

	public String getFwwh() {
		return this.fwwh;
	}

	public void setFwwh(String fwwh) {
		this.fwwh = fwwh;
	}

	public String getSlxh() {
		return this.slxh;
	}

	public void setSlxh(String slxh) {
		this.slxh = slxh;
	}

	public Date getSbrq() {
		return this.sbrq;
	}

	public void setSbrq(Date sbrq) {
		this.sbrq = sbrq;
	}

	@Override
	public String getMid() {
		// TODO Auto-generated method stub
		return null;
	}

	public String getXmlsb() {
		return xmlsb;
	}

	public void setXmlsb(String xmlsb) {
		this.xmlsb = xmlsb;
	}

	public String getJacldId() {
		return jacldId;
	}

	public void setJacldId(String jacldId) {
		this.jacldId = jacldId;
	}

}