package com.tansun.eam2.common.model.orm.bo;

import java.util.Date;

/**
 * CzXmxxLsb generated by MyEclipse Persistence Tools
 */

public class CzXmxxLsb extends com.tansun.rdp4j.common.web.vo.CommonBO
		implements java.io.Serializable {

	private static final long serialVersionUID = -4067994670865520900L;
	private String id;
	private String bianhao;
	private String czxmmc;
	private String hbr;
	private String hbrxm;
	private String jcslxr;
	private String jcslxrxm;
	private String yjhzr;
	private String yjhzrxm;
	private String hyId;
	private String spjl;
	private String sfba;
	private String zhuangtai;
	private String fenlei;
	private String slxh;
	private Date sbrq;
	private Long pxxh;
	private String cldId;
	private String yjhzrbmid;
	private String yjhzrbmmc;
	private String czsx;

	// Constructors

	public String getCzsx() {
		return czsx;
	}

	public void setCzsx(String czsx) {
		this.czsx = czsx;
	}

	/** default constructor */
	public CzXmxxLsb() {
	}

	/** full constructor */
	public CzXmxxLsb(String bianhao, String czxmmc, String hbr, String hbrxm,
			String jcslxr, String jcslxrxm, String yjhzr, String yjhzrxm,
			String hyId, String spjl, String sfba, String zhuangtai,
			String fenlei, String slxh, Date sbrq, Long pxxh, String cldId,
			String yjhzrbmid, String yjhzrbmmc,String czsx) {
		this.bianhao = bianhao;
		this.czxmmc = czxmmc;
		this.hbr = hbr;
		this.hbrxm = hbrxm;
		this.jcslxr = jcslxr;
		this.jcslxrxm = jcslxrxm;
		this.yjhzr = yjhzr;
		this.yjhzrxm = yjhzrxm;
		this.hyId = hyId;
		this.spjl = spjl;
		this.sfba = sfba;
		this.zhuangtai = zhuangtai;
		this.fenlei = fenlei;
		this.slxh = slxh;
		this.sbrq = sbrq;
		this.pxxh = pxxh;
		this.cldId = cldId;
		this.yjhzrbmid = yjhzrbmid;
		this.yjhzrbmmc = yjhzrbmmc;
		this.czsx = czsx;
	}

	// Property accessors

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getBianhao() {
		return this.bianhao;
	}

	public void setBianhao(String bianhao) {
		this.bianhao = bianhao;
	}

	public String getCzxmmc() {
		return this.czxmmc;
	}

	public void setCzxmmc(String czxmmc) {
		this.czxmmc = czxmmc;
	}

	public String getHbr() {
		return this.hbr;
	}

	public void setHbr(String hbr) {
		this.hbr = hbr;
	}

	public String getHbrxm() {
		return this.hbrxm;
	}

	public void setHbrxm(String hbrxm) {
		this.hbrxm = hbrxm;
	}

	public String getJcslxr() {
		return this.jcslxr;
	}

	public void setJcslxr(String jcslxr) {
		this.jcslxr = jcslxr;
	}

	public String getJcslxrxm() {
		return this.jcslxrxm;
	}

	public void setJcslxrxm(String jcslxrxm) {
		this.jcslxrxm = jcslxrxm;
	}

	public String getYjhzr() {
		return this.yjhzr;
	}

	public void setYjhzr(String yjhzr) {
		this.yjhzr = yjhzr;
	}

	public String getYjhzrxm() {
		return this.yjhzrxm;
	}

	public void setYjhzrxm(String yjhzrxm) {
		this.yjhzrxm = yjhzrxm;
	}

	public String getHyId() {
		return this.hyId;
	}

	public void setHyId(String hyId) {
		this.hyId = hyId;
	}

	public String getSpjl() {
		return this.spjl;
	}

	public void setSpjl(String spjl) {
		this.spjl = spjl;
	}

	public String getSfba() {
		return this.sfba;
	}

	public void setSfba(String sfba) {
		this.sfba = sfba;
	}

	public String getZhuangtai() {
		return this.zhuangtai;
	}

	public void setZhuangtai(String zhuangtai) {
		this.zhuangtai = zhuangtai;
	}

	public String getFenlei() {
		return this.fenlei;
	}

	public void setFenlei(String fenlei) {
		this.fenlei = fenlei;
	}

	public String getSlxh() {
		return this.slxh;
	}

	public void setSlxh(String slxh) {
		this.slxh = slxh;
	}

	public Date getSbrq() {
		return this.sbrq;
	}

	public void setSbrq(Date sbrq) {
		this.sbrq = sbrq;
	}

	public Long getPxxh() {
		return this.pxxh;
	}

	public void setPxxh(Long pxxh) {
		this.pxxh = pxxh;
	}

	public String getCldId() {
		return this.cldId;
	}

	public void setCldId(String cldId) {
		this.cldId = cldId;
	}

	public String getYjhzrbmid() {
		return this.yjhzrbmid;
	}

	public void setYjhzrbmid(String yjhzrbmid) {
		this.yjhzrbmid = yjhzrbmid;
	}

	public String getYjhzrbmmc() {
		return this.yjhzrbmmc;
	}

	public void setYjhzrbmmc(String yjhzrbmmc) {
		this.yjhzrbmmc = yjhzrbmmc;
	}

	@Override
	public String getMid() {
		// TODO Auto-generated method stub
		return null;
	}

}