package com.tansun.eam2.common.model.orm.bo;

import java.util.Date;

/**
 * CzXmSpwYj generated by MyEclipse Persistence Tools
 */

public class CzXmSpwYj extends com.tansun.rdp4j.common.web.vo.CommonBO
		implements java.io.Serializable {

	private static final long serialVersionUID = 252322379100973993L;
	private String id;
	private String xmId;
	private String spwy;
	private String spwyxm;
	private String sftjspyj;
	private String spyjjy;
	private String qtqk;
	private Date tyyjsj;
	private String sfwzcr;
	private Long tongyi;
	private Long butongyi;

	// Constructors

	/** default constructor */
	public CzXmSpwYj() {
	}

	/** full constructor */
	public CzXmSpwYj(String xmId, String spwy, String spwyxm, String sftjspyj,
			String spyjjy, String qtqk, Date tyyjsj, String sfwzcr,
			Long tongyi, Long butongyi) {
		this.xmId = xmId;
		this.spwy = spwy;
		this.spwyxm = spwyxm;
		this.sftjspyj = sftjspyj;
		this.spyjjy = spyjjy;
		this.qtqk = qtqk;
		this.tyyjsj = tyyjsj;
		this.sfwzcr = sfwzcr;
		this.tongyi = tongyi;
		this.butongyi = butongyi;
	}

	// Property accessors

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getXmId() {
		return this.xmId;
	}

	public void setXmId(String xmId) {
		this.xmId = xmId;
	}

	public String getSpwy() {
		return this.spwy;
	}

	public void setSpwy(String spwy) {
		this.spwy = spwy;
	}

	public String getSpwyxm() {
		return this.spwyxm;
	}

	public void setSpwyxm(String spwyxm) {
		this.spwyxm = spwyxm;
	}

	public String getSftjspyj() {
		return this.sftjspyj;
	}

	public void setSftjspyj(String sftjspyj) {
		this.sftjspyj = sftjspyj;
	}

	public String getSpyjjy() {
		return this.spyjjy;
	}

	public void setSpyjjy(String spyjjy) {
		this.spyjjy = spyjjy;
	}

	public String getQtqk() {
		return this.qtqk;
	}

	public void setQtqk(String qtqk) {
		this.qtqk = qtqk;
	}

	public Date getTyyjsj() {
		return this.tyyjsj;
	}

	public void setTyyjsj(Date tyyjsj) {
		this.tyyjsj = tyyjsj;
	}

	public String getSfwzcr() {
		return this.sfwzcr;
	}

	public void setSfwzcr(String sfwzcr) {
		this.sfwzcr = sfwzcr;
	}

	public Long getTongyi() {
		return this.tongyi;
	}

	public void setTongyi(Long tongyi) {
		this.tongyi = tongyi;
	}

	public Long getButongyi() {
		return this.butongyi;
	}

	public void setButongyi(Long butongyi) {
		this.butongyi = butongyi;
	}

	@Override
	public String getMid() {
		// TODO Auto-generated method stub
		return null;
	}

}