package com.tansun.eam2.common.model.orm.bo;

/**
 * DicAppAssetState generated by MyEclipse Persistence Tools
 */

public class DicAppAssetState extends com.tansun.rdp4j.common.web.vo.CommonBO
		implements java.io.Serializable {

	private static final long serialVersionUID = -3939077423261030385L;
	private Long pkId;
	private String code;
	private String name;
	private String type;
	private String typeinfo;
	private String parentid;
	private Long typeorder;

	// Constructors

	/** default constructor */
	public DicAppAssetState() {
	}

	/** full constructor */
	public DicAppAssetState(String code, String name, String type,
			String typeinfo, String parentid, Long typeorder) {
		this.code = code;
		this.name = name;
		this.type = type;
		this.typeinfo = typeinfo;
		this.parentid = parentid;
		this.typeorder = typeorder;
	}

	// Property accessors

	public Long getPkId() {
		return this.pkId;
	}

	public void setPkId(Long pkId) {
		this.pkId = pkId;
	}

	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	public String getTypeinfo() {
		return this.typeinfo;
	}

	public void setTypeinfo(String typeinfo) {
		this.typeinfo = typeinfo;
	}

	public String getParentid() {
		return this.parentid;
	}

	public void setParentid(String parentid) {
		this.parentid = parentid;
	}

	public Long getTypeorder() {
		return this.typeorder;
	}

	public void setTypeorder(Long typeorder) {
		this.typeorder = typeorder;
	}

	@Override
	public String getMid() {
		// TODO Auto-generated method stub
		return null;
	}

}