package com.tansun.eam2.common.model.orm.bo;

import java.util.Date;

import com.tansun.rdp4j.common.web.vo.CommonBO;

/**
 * JjzcHtBx generated by MyEclipse Persistence Tools
 */

public class JjzcHtBx extends CommonBO implements
		java.io.Serializable {

	private static final long serialVersionUID = 4812979409971688853L;
	private String id;
	private String cldId;
	private String htbh;
	private String swhtbh;
	private String htlx;
	private String CHtzt;
	private String CYjfh;
	private String bxgsmc;
	private String bxgsdz;
	private String bxgslxr;
	private String lxrdh;
	private String cph;
	private Double syxbf;
	private Date syxksrq;
	private Date syxjsrq;
	private Double jqxbf;
	private Date jqxksrq;
	private Date jqxjsrq;
	private Double ccsje;
	private Double sfhj;
	private Double jiqishxbxfl;
	private Double jiqishxbf;
	private Date jiqixksrq;
	private Date jiqixjsrq;
	private Double ggzrxbxfl;
	private Double ggzrxbf;
	private Date ggzrxksrq;
	private Date ggzrxjsrq;
	private Double ccxbxfl;
	private Double ccxbf;
	private Date ccxksrq;
	private Date ccxjsrq;
	private Date htqsrq;
	private Date htdqrq;
	private String spzt;
	private String zcid;
	private String zcbh;
	private String zcmc;

	// Constructors

	/** default constructor */
	public JjzcHtBx() {
	}

	/** full constructor */
	public JjzcHtBx(String cldId, String htbh, String swhtbh, String htlx,
			String CHtzt, String CYjfh, String bxgsmc, String bxgsdz,
			String bxgslxr, String lxrdh, String cph, Double syxbf,
			Date syxksrq, Date syxjsrq, Double jqxbf, Date jqxksrq,
			Date jqxjsrq, Double ccsje, Double sfhj, Double jiqishxbxfl,
			Double jiqishxbf, Date jiqixksrq, Date jiqixjsrq, Double ggzrxbxfl,
			Double ggzrxbf, Date ggzrxksrq, Date ggzrxjsrq, Double ccxbxfl,
			Double ccxbf, Date ccxksrq, Date ccxjsrq, Date htqsrq, Date htdqrq,
			String spzt, String zcid, String zcbh, String zcmc) {
		this.cldId = cldId;
		this.htbh = htbh;
		this.swhtbh = swhtbh;
		this.htlx = htlx;
		this.CHtzt = CHtzt;
		this.CYjfh = CYjfh;
		this.bxgsmc = bxgsmc;
		this.bxgsdz = bxgsdz;
		this.bxgslxr = bxgslxr;
		this.lxrdh = lxrdh;
		this.cph = cph;
		this.syxbf = syxbf;
		this.syxksrq = syxksrq;
		this.syxjsrq = syxjsrq;
		this.jqxbf = jqxbf;
		this.jqxksrq = jqxksrq;
		this.jqxjsrq = jqxjsrq;
		this.ccsje = ccsje;
		this.sfhj = sfhj;
		this.jiqishxbxfl = jiqishxbxfl;
		this.jiqishxbf = jiqishxbf;
		this.jiqixksrq = jiqixksrq;
		this.jiqixjsrq = jiqixjsrq;
		this.ggzrxbxfl = ggzrxbxfl;
		this.ggzrxbf = ggzrxbf;
		this.ggzrxksrq = ggzrxksrq;
		this.ggzrxjsrq = ggzrxjsrq;
		this.ccxbxfl = ccxbxfl;
		this.ccxbf = ccxbf;
		this.ccxksrq = ccxksrq;
		this.ccxjsrq = ccxjsrq;
		this.htqsrq = htqsrq;
		this.htdqrq = htdqrq;
		this.spzt = spzt;
		this.zcid = zcid;
		this.zcbh = zcbh;
		this.zcmc = zcmc;
	}

	// Property accessors

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getCldId() {
		return this.cldId;
	}

	public void setCldId(String cldId) {
		this.cldId = cldId;
	}

	public String getHtbh() {
		return this.htbh;
	}

	public void setHtbh(String htbh) {
		this.htbh = htbh;
	}

	public String getSwhtbh() {
		return this.swhtbh;
	}

	public void setSwhtbh(String swhtbh) {
		this.swhtbh = swhtbh;
	}

	public String getHtlx() {
		return this.htlx;
	}

	public void setHtlx(String htlx) {
		this.htlx = htlx;
	}

	public String getCHtzt() {
		return this.CHtzt;
	}

	public void setCHtzt(String CHtzt) {
		this.CHtzt = CHtzt;
	}

	public String getCYjfh() {
		return this.CYjfh;
	}

	public void setCYjfh(String CYjfh) {
		this.CYjfh = CYjfh;
	}

	public String getBxgsmc() {
		return this.bxgsmc;
	}

	public void setBxgsmc(String bxgsmc) {
		this.bxgsmc = bxgsmc;
	}

	public String getBxgsdz() {
		return this.bxgsdz;
	}

	public void setBxgsdz(String bxgsdz) {
		this.bxgsdz = bxgsdz;
	}

	public String getBxgslxr() {
		return this.bxgslxr;
	}

	public void setBxgslxr(String bxgslxr) {
		this.bxgslxr = bxgslxr;
	}

	public String getLxrdh() {
		return this.lxrdh;
	}

	public void setLxrdh(String lxrdh) {
		this.lxrdh = lxrdh;
	}

	public String getCph() {
		return this.cph;
	}

	public void setCph(String cph) {
		this.cph = cph;
	}

	public Double getSyxbf() {
		return this.syxbf;
	}

	public void setSyxbf(Double syxbf) {
		this.syxbf = syxbf;
	}

	public Date getSyxksrq() {
		return this.syxksrq;
	}

	public void setSyxksrq(Date syxksrq) {
		this.syxksrq = syxksrq;
	}

	public Date getSyxjsrq() {
		return this.syxjsrq;
	}

	public void setSyxjsrq(Date syxjsrq) {
		this.syxjsrq = syxjsrq;
	}

	public Double getJqxbf() {
		return this.jqxbf;
	}

	public void setJqxbf(Double jqxbf) {
		this.jqxbf = jqxbf;
	}

	public Date getJqxksrq() {
		return this.jqxksrq;
	}

	public void setJqxksrq(Date jqxksrq) {
		this.jqxksrq = jqxksrq;
	}

	public Date getJqxjsrq() {
		return this.jqxjsrq;
	}

	public void setJqxjsrq(Date jqxjsrq) {
		this.jqxjsrq = jqxjsrq;
	}

	public Double getCcsje() {
		return this.ccsje;
	}

	public void setCcsje(Double ccsje) {
		this.ccsje = ccsje;
	}

	public Double getSfhj() {
		return this.sfhj;
	}

	public void setSfhj(Double sfhj) {
		this.sfhj = sfhj;
	}

	public Double getJiqishxbxfl() {
		return this.jiqishxbxfl;
	}

	public void setJiqishxbxfl(Double jiqishxbxfl) {
		this.jiqishxbxfl = jiqishxbxfl;
	}

	public Double getJiqishxbf() {
		return this.jiqishxbf;
	}

	public void setJiqishxbf(Double jiqishxbf) {
		this.jiqishxbf = jiqishxbf;
	}

	public Date getJiqixksrq() {
		return this.jiqixksrq;
	}

	public void setJiqixksrq(Date jiqixksrq) {
		this.jiqixksrq = jiqixksrq;
	}

	public Date getJiqixjsrq() {
		return this.jiqixjsrq;
	}

	public void setJiqixjsrq(Date jiqixjsrq) {
		this.jiqixjsrq = jiqixjsrq;
	}

	public Double getGgzrxbxfl() {
		return this.ggzrxbxfl;
	}

	public void setGgzrxbxfl(Double ggzrxbxfl) {
		this.ggzrxbxfl = ggzrxbxfl;
	}

	public Double getGgzrxbf() {
		return this.ggzrxbf;
	}

	public void setGgzrxbf(Double ggzrxbf) {
		this.ggzrxbf = ggzrxbf;
	}

	public Date getGgzrxksrq() {
		return this.ggzrxksrq;
	}

	public void setGgzrxksrq(Date ggzrxksrq) {
		this.ggzrxksrq = ggzrxksrq;
	}

	public Date getGgzrxjsrq() {
		return this.ggzrxjsrq;
	}

	public void setGgzrxjsrq(Date ggzrxjsrq) {
		this.ggzrxjsrq = ggzrxjsrq;
	}

	public Double getCcxbxfl() {
		return this.ccxbxfl;
	}

	public void setCcxbxfl(Double ccxbxfl) {
		this.ccxbxfl = ccxbxfl;
	}

	public Double getCcxbf() {
		return this.ccxbf;
	}

	public void setCcxbf(Double ccxbf) {
		this.ccxbf = ccxbf;
	}

	public Date getCcxksrq() {
		return this.ccxksrq;
	}

	public void setCcxksrq(Date ccxksrq) {
		this.ccxksrq = ccxksrq;
	}

	public Date getCcxjsrq() {
		return this.ccxjsrq;
	}

	public void setCcxjsrq(Date ccxjsrq) {
		this.ccxjsrq = ccxjsrq;
	}

	public Date getHtqsrq() {
		return this.htqsrq;
	}

	public void setHtqsrq(Date htqsrq) {
		this.htqsrq = htqsrq;
	}

	public Date getHtdqrq() {
		return this.htdqrq;
	}

	public void setHtdqrq(Date htdqrq) {
		this.htdqrq = htdqrq;
	}

	public String getSpzt() {
		return this.spzt;
	}

	public void setSpzt(String spzt) {
		this.spzt = spzt;
	}

	public String getZcid() {
		return this.zcid;
	}

	public void setZcid(String zcid) {
		this.zcid = zcid;
	}

	public String getZcbh() {
		return this.zcbh;
	}

	public void setZcbh(String zcbh) {
		this.zcbh = zcbh;
	}

	public String getZcmc() {
		return this.zcmc;
	}

	public void setZcmc(String zcmc) {
		this.zcmc = zcmc;
	}

	@Override
	public String getMid() {
		// TODO Auto-generated method stub
		return null;
	}

}