package com.tansun.eam2.common.model.orm.bo;

import java.util.Date;

/**
 * JjzcHtJdzjLsb generated by MyEclipse Persistence Tools
 */

public class JjzcHtJdzjLsb extends com.tansun.rdp4j.common.web.vo.CommonBO
		implements java.io.Serializable {

	private static final long serialVersionUID = -4140430894458110327L;
	//ID
	private String id;
	//合同ID
	private String htId;
	//开始日期
	private Date ksrq;
	//结束日期
	private Date jsrq;
	//变动
	private Double biandong;
	//月租金
	private Double yzj;
	// Constructors

	/** default constructor */
	public JjzcHtJdzjLsb() {
	}

	/** full constructor */
	public JjzcHtJdzjLsb(String htId, Date ksrq, Date jsrq, Double biandong,
			Double yzj) {
		this.htId = htId;
		this.ksrq = ksrq;
		this.jsrq = jsrq;
		this.biandong = biandong;
		this.yzj = yzj;
	}

	// Property accessors



	public String getHtId() {
		return this.htId;
	}

	public void setHtId(String htId) {
		this.htId = htId;
	}

	public Date getKsrq() {
		return this.ksrq;
	}

	public void setKsrq(Date ksrq) {
		this.ksrq = ksrq;
	}

	public Date getJsrq() {
		return this.jsrq;
	}

	public void setJsrq(Date jsrq) {
		this.jsrq = jsrq;
	}

	public Double getBiandong() {
		return this.biandong;
	}

	public void setBiandong(Double biandong) {
		this.biandong = biandong;
	}

	public Double getYzj() {
		return this.yzj;
	}

	public void setYzj(Double yzj) {
		this.yzj = yzj;
	}

	@Override
	public String getMid() {
		// TODO Auto-generated method stub
		return null;
	}

	public String getId() {
		return id;
	}

	public void setId(String id) {
		this.id = id;
	}

}