package com.tansun.eam2.common.model.orm.bo;

/**
 * JjzcHtBxzcgx generated by MyEclipse Persistence Tools
 */

public class JjzcHtBxzcgx extends com.tansun.rdp4j.common.web.vo.CommonBO
		implements java.io.Serializable {

	private static final long serialVersionUID = -4185691562709575083L;
	private String id;
	private String zcId;
	private String bxhtId;
	private String spzt;

	// Constructors

	/** default constructor */
	public JjzcHtBxzcgx() {
	}

	/** minimal constructor */
	public JjzcHtBxzcgx(String zcId) {
		this.zcId = zcId;
	}

	/** full constructor */
	public JjzcHtBxzcgx(String zcId, String bxhtId, String spzt) {
		this.zcId = zcId;
		this.bxhtId = bxhtId;
		this.spzt = spzt;
	}

	// Property accessors

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getZcId() {
		return this.zcId;
	}

	public void setZcId(String zcId) {
		this.zcId = zcId;
	}

	public String getBxhtId() {
		return this.bxhtId;
	}

	public void setBxhtId(String bxhtId) {
		this.bxhtId = bxhtId;
	}

	public String getSpzt() {
		return this.spzt;
	}

	public void setSpzt(String spzt) {
		this.spzt = spzt;
	}

	@Override
	public String getMid() {
		// TODO Auto-generated method stub
		return null;
	}

}