package com.tansun.eam2.common.model.orm.bo;

/**
 * JjzcTbgcXx generated by MyEclipse Persistence Tools
 */

public class JjzcTbgcXx extends com.tansun.rdp4j.common.web.vo.CommonBO
		implements java.io.Serializable {

	private static final long serialVersionUID = -1992692367583985422L;
	private String id;
	private String zcId;
	private String gctbId;
	private Double tbje;
	private String spzt;
	private String cldId;
	private String tblb;

	// Constructors

	/** default constructor */
	public JjzcTbgcXx() {
	}

	/** minimal constructor */
	public JjzcTbgcXx(String zcId) {
		this.zcId = zcId;
	}

	/** full constructor */
	public JjzcTbgcXx(String zcId, String gctbId, Double tbje, String spzt,
			String cldId, String tblb) {
		this.zcId = zcId;
		this.gctbId = gctbId;
		this.tbje = tbje;
		this.spzt = spzt;
		this.cldId = cldId;
		this.tblb = tblb;
	}

	// Property accessors

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getZcId() {
		return this.zcId;
	}

	public void setZcId(String zcId) {
		this.zcId = zcId;
	}

	public String getGctbId() {
		return this.gctbId;
	}

	public void setGctbId(String gctbId) {
		this.gctbId = gctbId;
	}

	public Double getTbje() {
		return this.tbje;
	}

	public void setTbje(Double tbje) {
		this.tbje = tbje;
	}

	public String getSpzt() {
		return this.spzt;
	}

	public void setSpzt(String spzt) {
		this.spzt = spzt;
	}

	public String getCldId() {
		return this.cldId;
	}

	public void setCldId(String cldId) {
		this.cldId = cldId;
	}

	@Override
	public String getMid() {
		// TODO Auto-generated method stub
		return null;
	}

	public String getTblb() {
		return tblb;
	}

	public void setTblb(String tblb) {
		this.tblb = tblb;
	}

}