package com.tansun.eam2.common.model.orm.bo;

import java.util.Date;

/**
 * JjzcGctbXx generated by MyEclipse Persistence Tools
 */

public class JjzcGctbXx extends com.tansun.rdp4j.common.web.vo.CommonBO
		implements java.io.Serializable {

	private static final long serialVersionUID = 2672072709162489439L;
	private String id;
	private String cldId;
	private String zcId;
	private String bxgsmc;
	private Double syxbf;
	private Date syxksrq;
	private Date syxjsrq;
	private Double jqxbf;
	private Date jqxksrq;
	private Date jqxjsrq;
	private Double sfhj;
	private Double ccsje;
	private Double pjtbze;
	private Date gctbksrq;
	private Date gctbjsrq;
	private Double ccyqxtbzcze;
	private Double czyqxfl;
	private Double czyqxzk;
	private Double czyqxbf;
	private Double jqshxtbzcze;
	private Double jqshxfl;
	private Double jqshxzk;
	private Double jiqishxbf;
	private Double ggzrxbe;
	private Double ggzrxbxfl;
	private Double ggzrxbf;
	private String spzt;
	private String tblx;
	private Double clqntpje;
	private Double tbze;
	private Double tbzhj;

	// Constructors

	/** default constructor */
	public JjzcGctbXx() {
	}

	/** full constructor */
	public JjzcGctbXx(String cldId, String zcId, String bxgsmc, Double syxbf,
			Date syxksrq, Date syxjsrq, Double jqxbf, Date jqxksrq,
			Date jqxjsrq, Double sfhj, Double ccsje, Double pjtbze,
			Date gctbksrq, Date gctbjsrq, Double ccyqxtbzcze, Double czyqxfl,
			Double czyqxzk, Double czyqxbf, Double jqshxtbzcze, Double jqshxfl,
			Double jqshxzk, Double jiqishxbf, Double ggzrxbe, Double ggzrxbxfl,
			Double ggzrxbf, String spzt, String tblx, Double clqntpje, Double tbze, Double tbzhj) {
		this.cldId = cldId;
		this.zcId = zcId;
		this.bxgsmc = bxgsmc;
		this.syxbf = syxbf;
		this.syxksrq = syxksrq;
		this.syxjsrq = syxjsrq;
		this.jqxbf = jqxbf;
		this.jqxksrq = jqxksrq;
		this.jqxjsrq = jqxjsrq;
		this.sfhj = sfhj;
		this.ccsje = ccsje;
		this.pjtbze = pjtbze;
		this.gctbksrq = gctbksrq;
		this.gctbjsrq = gctbjsrq;
		this.ccyqxtbzcze = ccyqxtbzcze;
		this.czyqxfl = czyqxfl;
		this.czyqxzk = czyqxzk;
		this.czyqxbf = czyqxbf;
		this.jqshxtbzcze = jqshxtbzcze;
		this.jqshxfl = jqshxfl;
		this.jqshxzk = jqshxzk;
		this.jiqishxbf = jiqishxbf;
		this.ggzrxbe = ggzrxbe;
		this.ggzrxbxfl = ggzrxbxfl;
		this.ggzrxbf = ggzrxbf;
		this.spzt = spzt;
		this.tblx = tblx;
		this.clqntpje = clqntpje;
		this.tbze = tbze;
		this.tbzhj = tbzhj;
	}

	// Property accessors

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getCldId() {
		return this.cldId;
	}

	public void setCldId(String cldId) {
		this.cldId = cldId;
	}

	public String getZcId() {
		return this.zcId;
	}

	public void setZcId(String zcId) {
		this.zcId = zcId;
	}

	public String getBxgsmc() {
		return this.bxgsmc;
	}

	public void setBxgsmc(String bxgsmc) {
		this.bxgsmc = bxgsmc;
	}

	public Double getSyxbf() {
		return this.syxbf;
	}

	public void setSyxbf(Double syxbf) {
		this.syxbf = syxbf;
	}

	public Date getSyxksrq() {
		return this.syxksrq;
	}

	public void setSyxksrq(Date syxksrq) {
		this.syxksrq = syxksrq;
	}

	public Date getSyxjsrq() {
		return this.syxjsrq;
	}

	public void setSyxjsrq(Date syxjsrq) {
		this.syxjsrq = syxjsrq;
	}

	public Double getJqxbf() {
		return this.jqxbf;
	}

	public void setJqxbf(Double jqxbf) {
		this.jqxbf = jqxbf;
	}

	public Date getJqxksrq() {
		return this.jqxksrq;
	}

	public void setJqxksrq(Date jqxksrq) {
		this.jqxksrq = jqxksrq;
	}

	public Date getJqxjsrq() {
		return this.jqxjsrq;
	}

	public void setJqxjsrq(Date jqxjsrq) {
		this.jqxjsrq = jqxjsrq;
	}

	public Double getSfhj() {
		return this.sfhj;
	}

	public void setSfhj(Double sfhj) {
		this.sfhj = sfhj;
	}

	public Double getCcsje() {
		return this.ccsje;
	}

	public void setCcsje(Double ccsje) {
		this.ccsje = ccsje;
	}

	public Double getPjtbze() {
		return this.pjtbze;
	}

	public void setPjtbze(Double pjtbze) {
		this.pjtbze = pjtbze;
	}

	public Date getGctbksrq() {
		return this.gctbksrq;
	}

	public void setGctbksrq(Date gctbksrq) {
		this.gctbksrq = gctbksrq;
	}

	public Date getGctbjsrq() {
		return this.gctbjsrq;
	}

	public void setGctbjsrq(Date gctbjsrq) {
		this.gctbjsrq = gctbjsrq;
	}

	public Double getCcyqxtbzcze() {
		return this.ccyqxtbzcze;
	}

	public void setCcyqxtbzcze(Double ccyqxtbzcze) {
		this.ccyqxtbzcze = ccyqxtbzcze;
	}

	public Double getCzyqxfl() {
		return this.czyqxfl;
	}

	public void setCzyqxfl(Double czyqxfl) {
		this.czyqxfl = czyqxfl;
	}

	public Double getCzyqxzk() {
		return this.czyqxzk;
	}

	public void setCzyqxzk(Double czyqxzk) {
		this.czyqxzk = czyqxzk;
	}

	public Double getCzyqxbf() {
		return this.czyqxbf;
	}

	public void setCzyqxbf(Double czyqxbf) {
		this.czyqxbf = czyqxbf;
	}

	public Double getJqshxtbzcze() {
		return this.jqshxtbzcze;
	}

	public void setJqshxtbzcze(Double jqshxtbzcze) {
		this.jqshxtbzcze = jqshxtbzcze;
	}

	public Double getJqshxfl() {
		return this.jqshxfl;
	}

	public void setJqshxfl(Double jqshxfl) {
		this.jqshxfl = jqshxfl;
	}

	public Double getJqshxzk() {
		return this.jqshxzk;
	}

	public void setJqshxzk(Double jqshxzk) {
		this.jqshxzk = jqshxzk;
	}

	public Double getJiqishxbf() {
		return this.jiqishxbf;
	}

	public void setJiqishxbf(Double jiqishxbf) {
		this.jiqishxbf = jiqishxbf;
	}

	public Double getGgzrxbe() {
		return this.ggzrxbe;
	}

	public void setGgzrxbe(Double ggzrxbe) {
		this.ggzrxbe = ggzrxbe;
	}

	public Double getGgzrxbxfl() {
		return this.ggzrxbxfl;
	}

	public void setGgzrxbxfl(Double ggzrxbxfl) {
		this.ggzrxbxfl = ggzrxbxfl;
	}

	public Double getGgzrxbf() {
		return this.ggzrxbf;
	}

	public void setGgzrxbf(Double ggzrxbf) {
		this.ggzrxbf = ggzrxbf;
	}

	public String getSpzt() {
		return this.spzt;
	}

	public void setSpzt(String spzt) {
		this.spzt = spzt;
	}

	public String getTblx() {
		return this.tblx;
	}

	public void setTblx(String tblx) {
		this.tblx = tblx;
	}

	public Double getClqntpje() {
		return this.clqntpje;
	}

	public void setClqntpje(Double clqntpje) {
		this.clqntpje = clqntpje;
	}

	@Override
	public String getMid() {
		return null;
	}

	public Double getTbze() {
		return tbze;
	}

	public void setTbze(Double tbze) {
		this.tbze = tbze;
	}

	public Double getTbzhj() {
		return tbzhj;
	}

	public void setTbzhj(Double tbzhj) {
		this.tbzhj = tbzhj;
	}


}