package com.tansun.eam2.common.model.orm.bo;

import java.util.Date;

/**
 * JjzcHtZlwg generated by MyEclipse Persistence Tools
 */

public class JjzcHtZlwg extends com.tansun.rdp4j.common.web.vo.CommonBO
		implements java.io.Serializable {

	private static final long serialVersionUID = 7222281389085484968L;
	private String id;
	private String zcid;
	private String zcbh;
	private String zcmc;
	private String swhtbh;
	private String CHtlx;
	private String htbh;
	private String CHtzt;
	private String czr;
	private String CCzrxz;
	private String czlxr;
	private String czflxdh;
	private String jbrlxdh;
	private String jydx;
	private Double czsl;
	private Double yzj;
	private String zjsfhwyf;
	private String zjsfhsdf;
	private Double zjjg;
	private String jsfs;
	private String CZjjsfs;
	private Double ddtlfwzjjg;
	private Double ljzj;
	private Double yajin;
	private Double ysyj;
	private Double wyj;
	private Double yswyj;
	private Date htqsrq;
	private Date htdqrq;
	private Date mzqsrq;
	private Date mzdqrq;
	private Date scqsrq;
	private Double zlqstzje;
	private Date scqsjzrq;
	private String czrdz;
	private String czrfddz;
	private String zlyt;
	private Double zjsycbl;
	private String lrr;
	private Date lrrq;
	private String wghtbz;
	private String CYjfh;
	private String CWtgldw;
	private Double wtglyz;
	private Double wtfybi;
	private Double wtgljg;
	private Double wtglsl;
	private Double ywtglf;
	private Double ljsswgf;
	private Double ljyswgf;
	private String dldw;
	private String kpbh;
	private String htsftqzz;
	private Date htzzrq;
	private String zzblsm;
	private String CZzyy;
	private String bodyidlock;

	// Constructors

	/** default constructor */
	public JjzcHtZlwg() {
	}

	/** full constructor */
	public JjzcHtZlwg(String zcid, String zcbh, String zcmc, String swhtbh,
			String CHtlx, String htbh, String CHtzt, String czr, String CCzrxz,
			String czlxr, String czflxdh, String jbrlxdh, String jydx,
			Double czsl, Double yzj, String zjsfhwyf, String zjsfhsdf,
			Double zjjg, String jsfs, String CZjjsfs, Double ddtlfwzjjg,
			Double ljzj, Double yajin, Double ysyj, Double wyj, Double yswyj,
			Date htqsrq, Date htdqrq, Date mzqsrq, Date mzdqrq, Date scqsrq,
			Double zlqstzje, Date scqsjzrq, String czrdz, String czrfddz,
			String zlyt, Double zjsycbl, String lrr, Date lrrq, String wghtbz,
			String CYjfh, String CWtgldw, Double wtglyz, Double wtfybi,
			Double wtgljg, Double wtglsl, Double ywtglf, Double ljsswgf,
			Double ljyswgf, String dldw, String kpbh, String htsftqzz,
			Date htzzrq, String zzblsm, String CZzyy,String bodyidlock) {
		this.zcid = zcid;
		this.zcbh = zcbh;
		this.zcmc = zcmc;
		this.swhtbh = swhtbh;
		this.CHtlx = CHtlx;
		this.htbh = htbh;
		this.CHtzt = CHtzt;
		this.czr = czr;
		this.CCzrxz = CCzrxz;
		this.czlxr = czlxr;
		this.czflxdh = czflxdh;
		this.jbrlxdh = jbrlxdh;
		this.jydx = jydx;
		this.czsl = czsl;
		this.yzj = yzj;
		this.zjsfhwyf = zjsfhwyf;
		this.zjsfhsdf = zjsfhsdf;
		this.zjjg = zjjg;
		this.jsfs = jsfs;
		this.CZjjsfs = CZjjsfs;
		this.ddtlfwzjjg = ddtlfwzjjg;
		this.ljzj = ljzj;
		this.yajin = yajin;
		this.ysyj = ysyj;
		this.wyj = wyj;
		this.yswyj = yswyj;
		this.htqsrq = htqsrq;
		this.htdqrq = htdqrq;
		this.mzqsrq = mzqsrq;
		this.mzdqrq = mzdqrq;
		this.scqsrq = scqsrq;
		this.zlqstzje = zlqstzje;
		this.scqsjzrq = scqsjzrq;
		this.czrdz = czrdz;
		this.czrfddz = czrfddz;
		this.zlyt = zlyt;
		this.zjsycbl = zjsycbl;
		this.lrr = lrr;
		this.lrrq = lrrq;
		this.wghtbz = wghtbz;
		this.CYjfh = CYjfh;
		this.CWtgldw = CWtgldw;
		this.wtglyz = wtglyz;
		this.wtfybi = wtfybi;
		this.wtgljg = wtgljg;
		this.wtglsl = wtglsl;
		this.ywtglf = ywtglf;
		this.ljsswgf = ljsswgf;
		this.ljyswgf = ljyswgf;
		this.dldw = dldw;
		this.kpbh = kpbh;
		this.htsftqzz = htsftqzz;
		this.htzzrq = htzzrq;
		this.zzblsm = zzblsm;
		this.CZzyy = CZzyy;
		this.bodyidlock = bodyidlock;
	}

	// Property accessors

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getZcid() {
		return this.zcid;
	}

	public void setZcid(String zcid) {
		this.zcid = zcid;
	}

	public String getZcbh() {
		return this.zcbh;
	}

	public void setZcbh(String zcbh) {
		this.zcbh = zcbh;
	}

	public String getZcmc() {
		return this.zcmc;
	}

	public void setZcmc(String zcmc) {
		this.zcmc = zcmc;
	}

	public String getSwhtbh() {
		return this.swhtbh;
	}

	public void setSwhtbh(String swhtbh) {
		this.swhtbh = swhtbh;
	}

	public String getCHtlx() {
		return this.CHtlx;
	}

	public void setCHtlx(String CHtlx) {
		this.CHtlx = CHtlx;
	}

	public String getHtbh() {
		return this.htbh;
	}

	public void setHtbh(String htbh) {
		this.htbh = htbh;
	}

	public String getCHtzt() {
		return this.CHtzt;
	}

	public void setCHtzt(String CHtzt) {
		this.CHtzt = CHtzt;
	}

	public String getCzr() {
		return this.czr;
	}

	public void setCzr(String czr) {
		this.czr = czr;
	}

	public String getCCzrxz() {
		return this.CCzrxz;
	}

	public void setCCzrxz(String CCzrxz) {
		this.CCzrxz = CCzrxz;
	}

	public String getCzlxr() {
		return this.czlxr;
	}

	public void setCzlxr(String czlxr) {
		this.czlxr = czlxr;
	}

	public String getCzflxdh() {
		return this.czflxdh;
	}

	public void setCzflxdh(String czflxdh) {
		this.czflxdh = czflxdh;
	}

	public String getJbrlxdh() {
		return this.jbrlxdh;
	}

	public void setJbrlxdh(String jbrlxdh) {
		this.jbrlxdh = jbrlxdh;
	}

	public String getJydx() {
		return this.jydx;
	}

	public void setJydx(String jydx) {
		this.jydx = jydx;
	}

	public Double getCzsl() {
		return this.czsl;
	}

	public void setCzsl(Double czsl) {
		this.czsl = czsl;
	}

	public Double getYzj() {
		return this.yzj;
	}

	public void setYzj(Double yzj) {
		this.yzj = yzj;
	}

	public String getZjsfhwyf() {
		return this.zjsfhwyf;
	}

	public void setZjsfhwyf(String zjsfhwyf) {
		this.zjsfhwyf = zjsfhwyf;
	}

	public String getZjsfhsdf() {
		return this.zjsfhsdf;
	}

	public void setZjsfhsdf(String zjsfhsdf) {
		this.zjsfhsdf = zjsfhsdf;
	}

	public Double getZjjg() {
		return this.zjjg;
	}

	public void setZjjg(Double zjjg) {
		this.zjjg = zjjg;
	}

	public String getJsfs() {
		return this.jsfs;
	}

	public void setJsfs(String jsfs) {
		this.jsfs = jsfs;
	}

	public String getCZjjsfs() {
		return this.CZjjsfs;
	}

	public void setCZjjsfs(String CZjjsfs) {
		this.CZjjsfs = CZjjsfs;
	}

	public Double getDdtlfwzjjg() {
		return this.ddtlfwzjjg;
	}

	public void setDdtlfwzjjg(Double ddtlfwzjjg) {
		this.ddtlfwzjjg = ddtlfwzjjg;
	}

	public Double getLjzj() {
		return this.ljzj;
	}

	public void setLjzj(Double ljzj) {
		this.ljzj = ljzj;
	}

	public Double getYajin() {
		return this.yajin;
	}

	public void setYajin(Double yajin) {
		this.yajin = yajin;
	}

	public Double getYsyj() {
		return this.ysyj;
	}

	public void setYsyj(Double ysyj) {
		this.ysyj = ysyj;
	}

	public Double getWyj() {
		return this.wyj;
	}

	public void setWyj(Double wyj) {
		this.wyj = wyj;
	}

	public Double getYswyj() {
		return this.yswyj;
	}

	public void setYswyj(Double yswyj) {
		this.yswyj = yswyj;
	}

	public Date getHtqsrq() {
		return this.htqsrq;
	}

	public void setHtqsrq(Date htqsrq) {
		this.htqsrq = htqsrq;
	}

	public Date getHtdqrq() {
		return this.htdqrq;
	}

	public void setHtdqrq(Date htdqrq) {
		this.htdqrq = htdqrq;
	}

	public Date getMzqsrq() {
		return this.mzqsrq;
	}

	public void setMzqsrq(Date mzqsrq) {
		this.mzqsrq = mzqsrq;
	}

	public Date getMzdqrq() {
		return this.mzdqrq;
	}

	public void setMzdqrq(Date mzdqrq) {
		this.mzdqrq = mzdqrq;
	}

	public Date getScqsrq() {
		return this.scqsrq;
	}

	public void setScqsrq(Date scqsrq) {
		this.scqsrq = scqsrq;
	}

	public Double getZlqstzje() {
		return this.zlqstzje;
	}

	public void setZlqstzje(Double zlqstzje) {
		this.zlqstzje = zlqstzje;
	}

	public Date getScqsjzrq() {
		return this.scqsjzrq;
	}

	public void setScqsjzrq(Date scqsjzrq) {
		this.scqsjzrq = scqsjzrq;
	}

	public String getCzrdz() {
		return this.czrdz;
	}

	public void setCzrdz(String czrdz) {
		this.czrdz = czrdz;
	}

	public String getCzrfddz() {
		return this.czrfddz;
	}

	public void setCzrfddz(String czrfddz) {
		this.czrfddz = czrfddz;
	}

	public String getZlyt() {
		return this.zlyt;
	}

	public void setZlyt(String zlyt) {
		this.zlyt = zlyt;
	}

	public Double getZjsycbl() {
		return this.zjsycbl;
	}

	public void setZjsycbl(Double zjsycbl) {
		this.zjsycbl = zjsycbl;
	}

	public String getLrr() {
		return this.lrr;
	}

	public void setLrr(String lrr) {
		this.lrr = lrr;
	}

	public Date getLrrq() {
		return this.lrrq;
	}

	public void setLrrq(Date lrrq) {
		this.lrrq = lrrq;
	}

	public String getWghtbz() {
		return this.wghtbz;
	}

	public void setWghtbz(String wghtbz) {
		this.wghtbz = wghtbz;
	}

	public String getCYjfh() {
		return this.CYjfh;
	}

	public void setCYjfh(String CYjfh) {
		this.CYjfh = CYjfh;
	}

	public String getCWtgldw() {
		return this.CWtgldw;
	}

	public void setCWtgldw(String CWtgldw) {
		this.CWtgldw = CWtgldw;
	}

	public Double getWtglyz() {
		return this.wtglyz;
	}

	public void setWtglyz(Double wtglyz) {
		this.wtglyz = wtglyz;
	}

	public Double getWtfybi() {
		return this.wtfybi;
	}

	public void setWtfybi(Double wtfybi) {
		this.wtfybi = wtfybi;
	}

	public Double getWtgljg() {
		return this.wtgljg;
	}

	public void setWtgljg(Double wtgljg) {
		this.wtgljg = wtgljg;
	}

	public Double getWtglsl() {
		return this.wtglsl;
	}

	public void setWtglsl(Double wtglsl) {
		this.wtglsl = wtglsl;
	}

	public Double getYwtglf() {
		return this.ywtglf;
	}

	public void setYwtglf(Double ywtglf) {
		this.ywtglf = ywtglf;
	}

	public Double getLjsswgf() {
		return this.ljsswgf;
	}

	public void setLjsswgf(Double ljsswgf) {
		this.ljsswgf = ljsswgf;
	}

	public Double getLjyswgf() {
		return this.ljyswgf;
	}

	public void setLjyswgf(Double ljyswgf) {
		this.ljyswgf = ljyswgf;
	}

	public String getDldw() {
		return this.dldw;
	}

	public void setDldw(String dldw) {
		this.dldw = dldw;
	}

	public String getKpbh() {
		return this.kpbh;
	}

	public void setKpbh(String kpbh) {
		this.kpbh = kpbh;
	}

	public String getHtsftqzz() {
		return this.htsftqzz;
	}

	public void setHtsftqzz(String htsftqzz) {
		this.htsftqzz = htsftqzz;
	}

	public Date getHtzzrq() {
		return this.htzzrq;
	}

	public void setHtzzrq(Date htzzrq) {
		this.htzzrq = htzzrq;
	}

	public String getZzblsm() {
		return this.zzblsm;
	}

	public void setZzblsm(String zzblsm) {
		this.zzblsm = zzblsm;
	}

	public String getCZzyy() {
		return this.CZzyy;
	}

	public void setCZzyy(String CZzyy) {
		this.CZzyy = CZzyy;
	}

	@Override
	public String getMid() {
		// TODO Auto-generated method stub
		return null;
	}

	public String getBodyidlock() {
		return bodyidlock;
	}

	public void setBodyidlock(String bodyidlock) {
		this.bodyidlock = bodyidlock;
	}

}