package com.tansun.eam2.common.model.orm.bo;

import java.util.Date;

/**
 * JyzcHtqxBody generated by MyEclipse Persistence Tools
 * 合同清算表体
 */

public class JyzcHtqxBody extends com.tansun.rdp4j.common.web.vo.CommonBO
		implements java.io.Serializable {

	private static final long serialVersionUID = 3066993546615965645L;
	//ID
	private long id;
	//处理单ID
	private long cldId;
	//合同ID
	private long htId;
	//合同编号
	private String htbh;
	//资产ID
	private String zcId;
	//资产编号
	private String zcbh;
	//资产名称
	private String zcmc;
	//资产类型
	private String CZclx;
	//清算起始日期
	private Date qsksrq;
	//清算截止日期
	private Date qsjzrq;
	//应收租金
	private Double yszj;
	//修改后应收租金
	private Double xghyszj;
	//应收修改原因
	private String ysxgyy;
	//实收租金
	private Double sszj;
	//上次变动金额
	private Double scbdje;
	//本次变动金额
	private Double bcbdje;
	//清算调整金额
	private Double qstzje;
	//调整原因
	private String tzyy;
	//备注
	private String memo;
	//审批状态
	private String spzt;
	//清算批次
	private String qspc;
	
	// Constructors

	/** default constructor */
	public JyzcHtqxBody() {
	}

	/** full constructor */
	public JyzcHtqxBody(Long cldId, Long htId, String htbh, String zcId,
			String zcbh, String zcmc, String CZclx, Date qsksrq, Date qsjzrq,
			Double yszj, Double xghyszj, String ysxgyy, Double sszj,
			Double scbdje, Double bcbdje, Double qstzje, String tzyy,
			String memo, String spzt, String qspc) {
		this.cldId = cldId;
		this.htId = htId;
		this.htbh = htbh;
		this.zcId = zcId;
		this.zcbh = zcbh;
		this.zcmc = zcmc;
		this.CZclx = CZclx;
		this.qsksrq = qsksrq;
		this.qsjzrq = qsjzrq;
		this.yszj = yszj;
		this.xghyszj = xghyszj;
		this.ysxgyy = ysxgyy;
		this.sszj = sszj;
		this.scbdje = scbdje;
		this.bcbdje = bcbdje;
		this.qstzje = qstzje;
		this.tzyy = tzyy;
		this.memo = memo;
		this.spzt = spzt;
		this.qspc = qspc;
	}

	// Property accessors

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public Long getCldId() {
		return this.cldId;
	}

	public void setCldId(Long cldId) {
		this.cldId = cldId;
	}

	public Long getHtId() {
		return this.htId;
	}

	public void setHtId(Long htId) {
		this.htId = htId;
	}

	public String getHtbh() {
		return this.htbh;
	}

	public void setHtbh(String htbh) {
		this.htbh = htbh;
	}

	public String getZcId() {
		return this.zcId;
	}

	public void setZcId(String zcId) {
		this.zcId = zcId;
	}

	public String getZcbh() {
		return this.zcbh;
	}

	public void setZcbh(String zcbh) {
		this.zcbh = zcbh;
	}

	public String getZcmc() {
		return this.zcmc;
	}

	public void setZcmc(String zcmc) {
		this.zcmc = zcmc;
	}

	public String getCZclx() {
		return this.CZclx;
	}

	public void setCZclx(String CZclx) {
		this.CZclx = CZclx;
	}

	public Date getQsksrq() {
		return this.qsksrq;
	}

	public void setQsksrq(Date qsksrq) {
		this.qsksrq = qsksrq;
	}

	public Date getQsjzrq() {
		return this.qsjzrq;
	}

	public void setQsjzrq(Date qsjzrq) {
		this.qsjzrq = qsjzrq;
	}

	public Double getYszj() {
		return this.yszj;
	}

	public void setYszj(Double yszj) {
		this.yszj = yszj;
	}

	public Double getXghyszj() {
		return this.xghyszj;
	}

	public void setXghyszj(Double xghyszj) {
		this.xghyszj = xghyszj;
	}

	public String getYsxgyy() {
		return this.ysxgyy;
	}

	public void setYsxgyy(String ysxgyy) {
		this.ysxgyy = ysxgyy;
	}

	public Double getSszj() {
		return this.sszj;
	}

	public void setSszj(Double sszj) {
		this.sszj = sszj;
	}

	public Double getScbdje() {
		return this.scbdje;
	}

	public void setScbdje(Double scbdje) {
		this.scbdje = scbdje;
	}

	public Double getBcbdje() {
		return this.bcbdje;
	}

	public void setBcbdje(Double bcbdje) {
		this.bcbdje = bcbdje;
	}

	public Double getQstzje() {
		return this.qstzje;
	}

	public void setQstzje(Double qstzje) {
		this.qstzje = qstzje;
	}

	public String getTzyy() {
		return this.tzyy;
	}

	public void setTzyy(String tzyy) {
		this.tzyy = tzyy;
	}

	public String getMemo() {
		return this.memo;
	}

	public void setMemo(String memo) {
		this.memo = memo;
	}

	public String getSpzt() {
		return this.spzt;
	}

	public void setSpzt(String spzt) {
		this.spzt = spzt;
	}

	public String getQspc() {
		return this.qspc;
	}

	public void setQspc(String qspc) {
		this.qspc = qspc;
	}

	@Override
	public String getMid() {
		// TODO Auto-generated method stub
		return null;
	}

}