package com.tansun.eam2.common.model.orm.bo;

import java.util.Date;

/**
 * JyzcJyzlHead generated by MyEclipse Persistence Tools
 */

public class JyzcJyzlHead extends com.tansun.rdp4j.common.web.vo.CommonBO
		implements java.io.Serializable {

	private static final long serialVersionUID = -63967078519308220L;
	private String id;
	private String lcId;
	private String biaoti;
	private String chengsong;
	private String bianhao;
	private String jhcd;
	private Date ngrq;
	private String ngbm;
	private String ngbmmc;
	private String ngr;
	private String ngrmc;
	private String lxdh;
	private String ywlx;
	private String hqbm;
	private String fjbt;
	private String beizhu;

	private String sheettype;
	
	private String hqbmid;
	private String syhqbm;
	private String syhqbmid;
	private String cldZt;
	// Constructors

	/** default constructor */
	public JyzcJyzlHead() {
	}

	/** full constructor */
	public JyzcJyzlHead(String lcId, String biaoti, String chengsong,
			String bianhao, String jhcd, Date ngrq, String ngbm, String ngbmmc,
			String ngr, String ngrmc, String lxdh, String ywlx, String hqbm,
			String fjbt, String beizhu,String cldZt) {
		this.lcId = lcId;
		this.biaoti = biaoti;
		this.chengsong = chengsong;
		this.bianhao = bianhao;
		this.jhcd = jhcd;
		this.ngrq = ngrq;
		this.ngbm = ngbm;
		this.ngbmmc = ngbmmc;
		this.ngr = ngr;
		this.ngrmc = ngrmc;
		this.lxdh = lxdh;
		this.ywlx = ywlx;
		this.hqbm = hqbm;
		this.fjbt = fjbt;
		this.beizhu = beizhu;
		this.cldZt=cldZt;
	}

	// Property accessors

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getLcId() {
		return this.lcId;
	}

	public void setLcId(String lcId) {
		this.lcId = lcId;
	}

	public String getBiaoti() {
		return this.biaoti;
	}

	public void setBiaoti(String biaoti) {
		this.biaoti = biaoti;
	}

	public String getChengsong() {
		return this.chengsong;
	}

	public void setChengsong(String chengsong) {
		this.chengsong = chengsong;
	}

	public String getBianhao() {
		return this.bianhao;
	}

	public void setBianhao(String bianhao) {
		this.bianhao = bianhao;
	}

	public String getJhcd() {
		return this.jhcd;
	}

	public void setJhcd(String jhcd) {
		this.jhcd = jhcd;
	}

	public Date getNgrq() {
		return this.ngrq;
	}

	public void setNgrq(Date ngrq) {
		this.ngrq = ngrq;
	}

	public String getNgbm() {
		return this.ngbm;
	}

	public void setNgbm(String ngbm) {
		this.ngbm = ngbm;
	}

	public String getNgbmmc() {
		return this.ngbmmc;
	}

	public void setNgbmmc(String ngbmmc) {
		this.ngbmmc = ngbmmc;
	}

	public String getNgr() {
		return this.ngr;
	}

	public void setNgr(String ngr) {
		this.ngr = ngr;
	}

	public String getNgrmc() {
		return this.ngrmc;
	}

	public void setNgrmc(String ngrmc) {
		this.ngrmc = ngrmc;
	}

	public String getLxdh() {
		return this.lxdh;
	}

	public void setLxdh(String lxdh) {
		this.lxdh = lxdh;
	}

	public String getYwlx() {
		return this.ywlx;
	}

	public void setYwlx(String ywlx) {
		this.ywlx = ywlx;
	}

	public String getHqbm() {
		return this.hqbm;
	}

	public void setHqbm(String hqbm) {
		this.hqbm = hqbm;
	}

	public String getFjbt() {
		return this.fjbt;
	}

	public void setFjbt(String fjbt) {
		this.fjbt = fjbt;
	}

	public String getBeizhu() {
		return this.beizhu;
	}

	public void setBeizhu(String beizhu) {
		this.beizhu = beizhu;
	}

	
	public String getSheettype() {
		return sheettype;
	}

	public void setSheettype(String sheettype) {
		this.sheettype = sheettype;
	}

	
	
	public String getHqbmid() {
		return hqbmid;
	}

	public void setHqbmid(String hqbmid) {
		this.hqbmid = hqbmid;
	}

	public String getSyhqbm() {
		return syhqbm;
	}

	public void setSyhqbm(String syhqbm) {
		this.syhqbm = syhqbm;
	}

	public String getSyhqbmid() {
		return syhqbmid;
	}

	public void setSyhqbmid(String syhqbmid) {
		this.syhqbmid = syhqbmid;
	}

	@Override
	public String getMid() {
		
		return null;
	}

	public String getCldZt() {
		return cldZt;
	}

	public void setCldZt(String cldZt) {
		this.cldZt = cldZt;
	}

}