package com.tansun.eam2.common.model.orm.bo;

import java.lang.reflect.InvocationTargetException;
import java.util.Date;

import org.apache.commons.beanutils.BeanUtils;

/**
 * JyzcXxLsb generated by MyEclipse Persistence Tools
 */

public class JyzcXxLsb extends com.tansun.rdp4j.common.web.vo.CommonBO
		implements java.io.Serializable {

	private static final long serialVersionUID = 8647484174127118301L;
	//ID
	private String id; 
	//处理单ID
	private String cldId;
	//资产种类编码
	private String CZczlbm;
	//资产类型
	private String CZclx;
	//资产地区
	private String CZcdq;
	//资产编号
	private String zcbh;
	//资产名称
	private String zcmc;
	//经营分类
	private String CJyfl;
	//详细地址
	private String xxdz;
	//用途
	private String CYt;
	//经办单位
	private String jbdw;
	//增加方式
	private String CZjfs;
	//权属情况
	private String qsqk;
	//周围环境
	private String zwhj;
	//资产状态
	private String CZczc;
	//开始使用日期
	private Date kssyrq;
	//二级地区
	private String ejdq;
	//一级委托机构
	private String CYjwtjg;
	//二级委托机构
	private String CErwtjg;
	//录入日期
	private Date lrrq;
	//录入人
	private String lrr;
	//建成日期
	private Date jcrq;
	//房屋结构
	private String fwjg;
	//檐高
	private String yangao;
	//标准层高
	private String bzcg;
	//总层数
	private String zcs;
	//坐落在第几层
	private String zlzdjc;
	//房间号
	private String fjh;
	//建筑面积
	private String jzmj;
	//成本单价
	private String cbdj;
	//房地分离房屋
	private String fdflfw;
	//有无土地
	private String CYwtd;
	//房产证所有权人
	private String fczsyqr;
	//房产证号
	private String fczh;
	//房产证替代文件
	private String fcztdwj;
	//房产证无有效文件
	private String fczwyxwj;
	//房屋已办证
	private String fwybz;
	//	房产证办理时间
	private String fczblsj;
	//空地
	private String kongdi;
	//	用地性质
	private String CYdxz;
	//	土地面积
	private String tdmj;
	//	取得日期
	private String qdrq;
	//准用年限
	private String zynx;
	//剩余使用年限
	private String sysynx;
	//开发程度
	private String kfcd;
	//房地分离土地
	private String fdfltd;
	//	土地证使用权人
	private String tdzsyqr;
	//土地证号
	private String tdzh;
	//土地证替代文件
	private String tdztdwj;
	//土地无有效文件
	private String tdwyxwj;
	//土地已办证
	private String tdybz;
	//	土地证办理日期
	private Date tdzblsj;
	//结构
	private String gzwjg;
	//规格尺寸
	private String ggcc;
	//计量单位
	private String jldw;
	//	构筑物数量
	private Long gzwsl;
	//构筑物成本单价
	private Double gzwcbdj;
	//构筑物建成时间
	private String gzwjcsj;
	//	房地合一
	private String fdhy;
	//房地合一已办证
	private String fdhyybz;
	//房地合一权证号
	private String fdhyqzh;
	//特殊类型
	private String tslx;
	//无法办证原因
	private String wfbzyy;
	//两证全未办
	private String lzqwb;
	//车辆牌号
	private String clph;
	//车辆行驶证所有人
	private String clxszsyr;
	//车辆名称及型号规格
	private String clmcjggxh;
	//购置日期
	private String gzrq;
	//启用日期
	private String qyrq;
	//已行驶里程
	private Double yxslc;
	//设备名称
	private String sbmc;
	//规格型号
	private String ggxh;
	//生产厂家
	private String sccj;
	//设备计量单位
	private String CJldw;
	//设备数量
	private Long sbsl;
	//审批状态
	private String spzt;
	//经办行
	private String CJbhbh;
	//二级分行
	private String CEjfhbh;
	//费用种类
	private String CFyzl;
	//办理说明
	private String blsm;
	//发送erp序列号
	private String xlid;
	//已使用年限
	private String ysynx;
	//尚可使用年限
	private String sksynx;
	// Constructors

	private String CZcqs;
	private String wtrmc;
	private Double sjhf; 
	//结算方式
	private String CJsfs;
	//币种
	private String CBz;
	// Constructors

	/** default constructor */
	public JyzcXxLsb() {
	}

	/** full constructor */
	public JyzcXxLsb(String cldId, String CZczlbm, String CZclx, String CZcdq,
			String zcbh, String zcmc, String CJyfl, String xxdz, String CYt,
			String jbdw, String CZjfs, String qsqk, String zwhj, String CZczc,
			Date kssyrq, String ejdq, String CYjwtjg, String CErwtjg,
			Date lrrq, String lrr, Date jcrq, String fwjg, String yangao,
			String bzcg, String zcs, String zlzdjc, String fjh, String jzmj,
			String cbdj, String fdflfw, String CYwtd, String fczsyqr,
			String fczh, String fcztdwj, String fczwyxwj, String fwybz,
			String fczblsj, String kongdi, String CYdxz, String tdmj,
			String qdrq, String zynx, String sysynx, String kfcd,
			String fdfltd, String tdzsyqr, String tdzh, String tdztdwj,
			String tdwyxwj, String tdybz, Date tdzblsj, String gzwjg,
			String ggcc, String jldw, Long gzwsl, Double gzwcbdj,
			String gzwjcsj, String fdhy, String fdhyybz, String fdhyqzh,
			String tslx, String wfbzyy, String lzqwb, String clph,
			String clxszsyr, String clmcjggxh, String gzrq, String qyrq,
			Double yxslc, String sbmc, String ggxh, String sccj, String CJldw,
			Long sbsl, String spzt, String CJbhbh, String CEjfhbh,
			String CFyzl, String blsm, String xlid, String ysynx,
			String sksynx, String CZcqs, String wtrmc,Double sjhf,
			String CJsfs,String CBz) {
		this.cldId = cldId;
		this.CZczlbm = CZczlbm;
		this.CZclx = CZclx;
		this.CZcdq = CZcdq;
		this.zcbh = zcbh;
		this.zcmc = zcmc;
		this.CJyfl = CJyfl;
		this.xxdz = xxdz;
		this.CYt = CYt;
		this.jbdw = jbdw;
		this.CZjfs = CZjfs;
		this.qsqk = qsqk;
		this.zwhj = zwhj;
		this.CZczc = CZczc;
		this.kssyrq = kssyrq;
		this.ejdq = ejdq;
		this.CYjwtjg = CYjwtjg;
		this.CErwtjg = CErwtjg;
		this.lrrq = lrrq;
		this.lrr = lrr;
		this.jcrq = jcrq;
		this.fwjg = fwjg;
		this.yangao = yangao;
		this.bzcg = bzcg;
		this.zcs = zcs;
		this.zlzdjc = zlzdjc;
		this.fjh = fjh;
		this.jzmj = jzmj;
		this.cbdj = cbdj;
		this.fdflfw = fdflfw;
		this.CYwtd = CYwtd;
		this.fczsyqr = fczsyqr;
		this.fczh = fczh;
		this.fcztdwj = fcztdwj;
		this.fczwyxwj = fczwyxwj;
		this.fwybz = fwybz;
		this.fczblsj = fczblsj;
		this.kongdi = kongdi;
		this.CYdxz = CYdxz;
		this.tdmj = tdmj;
		this.qdrq = qdrq;
		this.zynx = zynx;
		this.sysynx = sysynx;
		this.kfcd = kfcd;
		this.fdfltd = fdfltd;
		this.tdzsyqr = tdzsyqr;
		this.tdzh = tdzh;
		this.tdztdwj = tdztdwj;
		this.tdwyxwj = tdwyxwj;
		this.tdybz = tdybz;
		this.tdzblsj = tdzblsj;
		this.gzwjg = gzwjg;
		this.ggcc = ggcc;
		this.jldw = jldw;
		this.gzwsl = gzwsl;
		this.gzwcbdj = gzwcbdj;
		this.gzwjcsj = gzwjcsj;
		this.fdhy = fdhy;
		this.fdhyybz = fdhyybz;
		this.fdhyqzh = fdhyqzh;
		this.tslx = tslx;
		this.wfbzyy = wfbzyy;
		this.lzqwb = lzqwb;
		this.clph = clph;
		this.clxszsyr = clxszsyr;
		this.clmcjggxh = clmcjggxh;
		this.gzrq = gzrq;
		this.qyrq = qyrq;
		this.yxslc = yxslc;
		this.sbmc = sbmc;
		this.ggxh = ggxh;
		this.sccj = sccj;
		this.CJldw = CJldw;
		this.sbsl = sbsl;
		this.spzt = spzt;
		this.CJbhbh = CJbhbh;
		this.CEjfhbh = CEjfhbh;
		this.CFyzl = CFyzl;
		this.blsm = blsm;
		this.xlid = xlid;
		this.ysynx = ysynx;
		this.sksynx = sksynx;
		this.CZcqs = CZcqs;
		this.wtrmc = wtrmc;
		this.sjhf=sjhf;
		this.CJsfs = CJsfs;
		this.CBz = CBz;
	}

	// Property accessors

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getXlid() {
		return xlid;
	}

	public void setXlid(String xlid) {
		this.xlid = xlid;
	}
	public String getCldId() {
		return this.cldId;
	}

	public void setCldId(String cldId) {
		this.cldId = cldId;
	}

	public String getCZczlbm() {
		return this.CZczlbm;
	}

	public void setCZczlbm(String CZczlbm) {
		this.CZczlbm = CZczlbm;
	}

	public String getCZclx() {
		return this.CZclx;
	}

	public void setCZclx(String CZclx) {
		this.CZclx = CZclx;
	}

	public String getCZcdq() {
		return this.CZcdq;
	}

	public void setCZcdq(String CZcdq) {
		this.CZcdq = CZcdq;
	}

	public String getZcbh() {
		return this.zcbh;
	}

	public void setZcbh(String zcbh) {
		this.zcbh = zcbh;
	}

	public String getZcmc() {
		return this.zcmc;
	}

	public void setZcmc(String zcmc) {
		this.zcmc = zcmc;
	}

	public String getCJyfl() {
		return this.CJyfl;
	}

	public void setCJyfl(String CJyfl) {
		this.CJyfl = CJyfl;
	}

	public String getXxdz() {
		return this.xxdz;
	}

	public void setXxdz(String xxdz) {
		this.xxdz = xxdz;
	}

	public String getCYt() {
		return this.CYt;
	}

	public void setCYt(String CYt) {
		this.CYt = CYt;
	}

	public String getJbdw() {
		return this.jbdw;
	}

	public void setJbdw(String jbdw) {
		this.jbdw = jbdw;
	}

	public String getCZjfs() {
		return this.CZjfs;
	}

	public void setCZjfs(String CZjfs) {
		this.CZjfs = CZjfs;
	}

	public String getQsqk() {
		return this.qsqk;
	}

	public void setQsqk(String qsqk) {
		this.qsqk = qsqk;
	}

	public String getZwhj() {
		return this.zwhj;
	}

	public void setZwhj(String zwhj) {
		this.zwhj = zwhj;
	}

	public String getCZczc() {
		return this.CZczc;
	}

	public void setCZczc(String CZczc) {
		this.CZczc = CZczc;
	}

	public Date getKssyrq() {
		return this.kssyrq;
	}

	public void setKssyrq(Date kssyrq) {
		this.kssyrq = kssyrq;
	}

	public String getEjdq() {
		return this.ejdq;
	}

	public void setEjdq(String ejdq) {
		this.ejdq = ejdq;
	}

	public String getCYjwtjg() {
		return this.CYjwtjg;
	}

	public void setCYjwtjg(String CYjwtjg) {
		this.CYjwtjg = CYjwtjg;
	}

	public String getCErwtjg() {
		return this.CErwtjg;
	}

	public void setCErwtjg(String CErwtjg) {
		this.CErwtjg = CErwtjg;
	}

	public Date getLrrq() {
		return this.lrrq;
	}

	public void setLrrq(Date lrrq) {
		this.lrrq = lrrq;
	}

	public String getLrr() {
		return this.lrr;
	}

	public void setLrr(String lrr) {
		this.lrr = lrr;
	}

	public Date getJcrq() {
		return this.jcrq;
	}

	public void setJcrq(Date jcrq) {
		this.jcrq = jcrq;
	}

	public String getFwjg() {
		return this.fwjg;
	}

	public void setFwjg(String fwjg) {
		this.fwjg = fwjg;
	}

	public String getYangao() {
		return this.yangao;
	}

	public void setYangao(String yangao) {
		this.yangao = yangao;
	}

	public String getBzcg() {
		return this.bzcg;
	}

	public void setBzcg(String bzcg) {
		this.bzcg = bzcg;
	}

	public String getZcs() {
		return this.zcs;
	}

	public void setZcs(String zcs) {
		this.zcs = zcs;
	}

	public String getZlzdjc() {
		return this.zlzdjc;
	}

	public void setZlzdjc(String zlzdjc) {
		this.zlzdjc = zlzdjc;
	}

	public String getFjh() {
		return this.fjh;
	}

	public void setFjh(String fjh) {
		this.fjh = fjh;
	}

	public String getJzmj() {
		return this.jzmj;
	}

	public void setJzmj(String jzmj) {
		this.jzmj = jzmj;
	}

	public String getCbdj() {
		return this.cbdj;
	}

	public void setCbdj(String cbdj) {
		this.cbdj = cbdj;
	}

	public String getFdflfw() {
		return this.fdflfw;
	}

	public void setFdflfw(String fdflfw) {
		this.fdflfw = fdflfw;
	}

	public String getCYwtd() {
		return this.CYwtd;
	}

	public void setCYwtd(String CYwtd) {
		this.CYwtd = CYwtd;
	}

	public String getFczsyqr() {
		return this.fczsyqr;
	}

	public void setFczsyqr(String fczsyqr) {
		this.fczsyqr = fczsyqr;
	}

	public String getFczh() {
		return this.fczh;
	}

	public void setFczh(String fczh) {
		this.fczh = fczh;
	}

	public String getFcztdwj() {
		return this.fcztdwj;
	}

	public void setFcztdwj(String fcztdwj) {
		this.fcztdwj = fcztdwj;
	}

	public String getFczwyxwj() {
		return this.fczwyxwj;
	}

	public void setFczwyxwj(String fczwyxwj) {
		this.fczwyxwj = fczwyxwj;
	}

	public String getFwybz() {
		return this.fwybz;
	}

	public void setFwybz(String fwybz) {
		this.fwybz = fwybz;
	}

	public String getFczblsj() {
		return this.fczblsj;
	}

	public void setFczblsj(String fczblsj) {
		this.fczblsj = fczblsj;
	}

	public String getKongdi() {
		return this.kongdi;
	}

	public void setKongdi(String kongdi) {
		this.kongdi = kongdi;
	}

	public String getCYdxz() {
		return this.CYdxz;
	}

	public void setCYdxz(String CYdxz) {
		this.CYdxz = CYdxz;
	}

	public String getTdmj() {
		return this.tdmj;
	}

	public void setTdmj(String tdmj) {
		this.tdmj = tdmj;
	}

	public String getQdrq() {
		return this.qdrq;
	}

	public void setQdrq(String qdrq) {
		this.qdrq = qdrq;
	}

	public String getZynx() {
		return this.zynx;
	}

	public void setZynx(String zynx) {
		this.zynx = zynx;
	}

	public String getSysynx() {
		return this.sysynx;
	}

	public void setSysynx(String sysynx) {
		this.sysynx = sysynx;
	}

	public String getKfcd() {
		return this.kfcd;
	}

	public void setKfcd(String kfcd) {
		this.kfcd = kfcd;
	}

	public String getFdfltd() {
		return this.fdfltd;
	}

	public void setFdfltd(String fdfltd) {
		this.fdfltd = fdfltd;
	}

	public String getTdzsyqr() {
		return this.tdzsyqr;
	}

	public void setTdzsyqr(String tdzsyqr) {
		this.tdzsyqr = tdzsyqr;
	}

	public String getTdzh() {
		return this.tdzh;
	}

	public void setTdzh(String tdzh) {
		this.tdzh = tdzh;
	}

	public String getTdztdwj() {
		return this.tdztdwj;
	}

	public void setTdztdwj(String tdztdwj) {
		this.tdztdwj = tdztdwj;
	}

	public String getTdwyxwj() {
		return this.tdwyxwj;
	}

	public void setTdwyxwj(String tdwyxwj) {
		this.tdwyxwj = tdwyxwj;
	}

	public String getTdybz() {
		return this.tdybz;
	}

	public void setTdybz(String tdybz) {
		this.tdybz = tdybz;
	}

	public Date getTdzblsj() {
		return this.tdzblsj;
	}

	public void setTdzblsj(Date tdzblsj) {
		this.tdzblsj = tdzblsj;
	}

	public String getGzwjg() {
		return this.gzwjg;
	}

	public void setGzwjg(String gzwjg) {
		this.gzwjg = gzwjg;
	}

	public String getGgcc() {
		return this.ggcc;
	}

	public void setGgcc(String ggcc) {
		this.ggcc = ggcc;
	}

	public String getJldw() {
		return this.jldw;
	}

	public void setJldw(String jldw) {
		this.jldw = jldw;
	}

	public Long getGzwsl() {
		return this.gzwsl;
	}

	public void setGzwsl(Long gzwsl) {
		this.gzwsl = gzwsl;
	}

	public String getGzwjcsj() {
		return this.gzwjcsj;
	}

	public void setGzwjcsj(String gzwjcsj) {
		this.gzwjcsj = gzwjcsj;
	}

	public String getFdhy() {
		return this.fdhy;
	}

	public void setFdhy(String fdhy) {
		this.fdhy = fdhy;
	}

	public String getFdhyybz() {
		return this.fdhyybz;
	}

	public void setFdhyybz(String fdhyybz) {
		this.fdhyybz = fdhyybz;
	}

	public String getFdhyqzh() {
		return this.fdhyqzh;
	}

	public void setFdhyqzh(String fdhyqzh) {
		this.fdhyqzh = fdhyqzh;
	}

	public String getTslx() {
		return this.tslx;
	}

	public void setTslx(String tslx) {
		this.tslx = tslx;
	}

	public String getWfbzyy() {
		return this.wfbzyy;
	}

	public void setWfbzyy(String wfbzyy) {
		this.wfbzyy = wfbzyy;
	}

	public String getLzqwb() {
		return this.lzqwb;
	}

	public void setLzqwb(String lzqwb) {
		this.lzqwb = lzqwb;
	}

	public String getClph() {
		return this.clph;
	}

	public void setClph(String clph) {
		this.clph = clph;
	}

	public String getClxszsyr() {
		return this.clxszsyr;
	}

	public void setClxszsyr(String clxszsyr) {
		this.clxszsyr = clxszsyr;
	}

	public String getClmcjggxh() {
		return this.clmcjggxh;
	}

	public void setClmcjggxh(String clmcjggxh) {
		this.clmcjggxh = clmcjggxh;
	}

	public String getGzrq() {
		return this.gzrq;
	}

	public void setGzrq(String gzrq) {
		this.gzrq = gzrq;
	}

	public String getQyrq() {
		return this.qyrq;
	}

	public void setQyrq(String qyrq) {
		this.qyrq = qyrq;
	}

	public Double getYxslc() {
		return this.yxslc;
	}

	public void setYxslc(Double yxslc) {
		this.yxslc = yxslc;
	}

	public String getSbmc() {
		return this.sbmc;
	}

	public void setSbmc(String sbmc) {
		this.sbmc = sbmc;
	}

	public String getGgxh() {
		return this.ggxh;
	}

	public void setGgxh(String ggxh) {
		this.ggxh = ggxh;
	}

	public String getSccj() {
		return this.sccj;
	}

	public void setSccj(String sccj) {
		this.sccj = sccj;
	}

	public String getCJldw() {
		return this.CJldw;
	}

	public void setCJldw(String CJldw) {
		this.CJldw = CJldw;
	}

	public Long getSbsl() {
		return this.sbsl;
	}

	public void setSbsl(Long sbsl) {
		this.sbsl = sbsl;
	}

	public String getSpzt() {
		return this.spzt;
	}

	public void setSpzt(String spzt) {
		this.spzt = spzt;
	}

	public String getCJbhbh() {
		return this.CJbhbh;
	}

	public void setCJbhbh(String CJbhbh) {
		this.CJbhbh = CJbhbh;
	}

	public String getCEjfhbh() {
		return this.CEjfhbh;
	}

	public void setCEjfhbh(String CEjfhbh) {
		this.CEjfhbh = CEjfhbh;
	}

	public String getCFyzl() {
		return this.CFyzl;
	}

	public void setCFyzl(String CFyzl) {
		this.CFyzl = CFyzl;
	}

	public String getBlsm() {
		return this.blsm;
	}

	public void setBlsm(String blsm) {
		this.blsm = blsm;
	}

	@Override
	public String getMid() {
		return null;
	}

	public void copyProperties(JyzcXx jyzcXx){
		try {
			BeanUtils.copyProperties(this, jyzcXx);
		} catch (IllegalAccessException e) {
			e.printStackTrace();
		} catch (InvocationTargetException e) {
			e.printStackTrace();
		}
	}

	public String getYsynx() {
		return ysynx;
	}

	public void setYsynx(String ysynx) {
		this.ysynx = ysynx;
	}

	public String getSksynx() {
		return sksynx;
	}

	public void setSksynx(String sksynx) {
		this.sksynx = sksynx;
	}

	public Double getGzwcbdj() {
		return gzwcbdj;
	}

	public void setGzwcbdj(Double gzwcbdj) {
		this.gzwcbdj = gzwcbdj;
	}

	public String getCZcqs() {
		return CZcqs;
	}

	public void setCZcqs(String zcqs) {
		CZcqs = zcqs;
	}

	public String getWtrmc() {
		return wtrmc;
	}

	public void setWtrmc(String wtrmc) {
		this.wtrmc = wtrmc;
	}

	public Double getSjhf() {
		return sjhf;
	}

	public void setSjhf(Double sjhf) {
		this.sjhf = sjhf;
	}

	public String getCJsfs() {
		return CJsfs;
	}

	public void setCJsfs(String jsfs) {
		CJsfs = jsfs;
	}

	public String getCBz() {
		return CBz;
	}

	public void setCBz(String bz) {
		CBz = bz;
	}
	
	
}