package com.tansun.eam2.common.model.orm.bo;

import java.util.Date;

/**
 * JyzcHtqsBody generated by MyEclipse Persistence Tools
 */

public class JyzcHtqsBody extends com.tansun.rdp4j.common.web.vo.CommonBO
		implements java.io.Serializable {

	// Fields

	/**
	 * 
	 */
	private static final long serialVersionUID = 780323462698240704L;
	private String id;
	private String cldId;
	private String htId;
	private String htbh;
	private String zcId;
	private String zcbh;
	private String zcmc;
	private String CZclx;
	private Date qsksrq;
	private Date qsjzrq;
	private Double yszj;
	private Double xghyszj;
	private String ysxgyy;
	private Double sszj;
	private Double scbdje;
	private Double bcbdje;
	private Double qstzje;
	private String tzyy;
	private String memo;
	private String spzt;
	private String qspc;
	private String CHtlx;
	private String mzq;

	// Constructors

	/** default constructor */
	public JyzcHtqsBody() {
	}

	/** full constructor */
	public JyzcHtqsBody(String cldId, String htId, String htbh, String zcId,
			String zcbh, String zcmc, String CZclx, Date qsksrq, Date qsjzrq,
			Double yszj, Double xghyszj, String ysxgyy, Double sszj,
			Double scbdje, Double bcbdje, Double qstzje, String tzyy,
			String memo, String spzt, String qspc, String CHtlx,String mzq) {
		this.cldId = cldId;
		this.htId = htId;
		this.htbh = htbh;
		this.zcId = zcId;
		this.zcbh = zcbh;
		this.zcmc = zcmc;
		this.CZclx = CZclx;
		this.qsksrq = qsksrq;
		this.qsjzrq = qsjzrq;
		this.yszj = yszj;
		this.xghyszj = xghyszj;
		this.ysxgyy = ysxgyy;
		this.sszj = sszj;
		this.scbdje = scbdje;
		this.bcbdje = bcbdje;
		this.qstzje = qstzje;
		this.tzyy = tzyy;
		this.memo = memo;
		this.spzt = spzt;
		this.qspc = qspc;
		this.CHtlx = CHtlx;
		this.mzq = mzq;
	}

	// Property accessors

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getCldId() {
		return this.cldId;
	}

	public void setCldId(String cldId) {
		this.cldId = cldId;
	}

	public String getHtId() {
		return this.htId;
	}

	public void setHtId(String htId) {
		this.htId = htId;
	}

	public String getHtbh() {
		return this.htbh;
	}

	public void setHtbh(String htbh) {
		this.htbh = htbh;
	}

	public String getZcId() {
		return this.zcId;
	}

	public void setZcId(String zcId) {
		this.zcId = zcId;
	}

	public String getZcbh() {
		return this.zcbh;
	}

	public void setZcbh(String zcbh) {
		this.zcbh = zcbh;
	}

	public String getZcmc() {
		return this.zcmc;
	}

	public void setZcmc(String zcmc) {
		this.zcmc = zcmc;
	}

	public String getCZclx() {
		return this.CZclx;
	}

	public void setCZclx(String CZclx) {
		this.CZclx = CZclx;
	}

	public Date getQsksrq() {
		return this.qsksrq;
	}

	public void setQsksrq(Date qsksrq) {
		this.qsksrq = qsksrq;
	}

	public Date getQsjzrq() {
		return this.qsjzrq;
	}

	public void setQsjzrq(Date qsjzrq) {
		this.qsjzrq = qsjzrq;
	}

	public Double getYszj() {
		return this.yszj;
	}

	public void setYszj(Double yszj) {
		this.yszj = yszj;
	}

	public Double getXghyszj() {
		return this.xghyszj;
	}

	public void setXghyszj(Double xghyszj) {
		this.xghyszj = xghyszj;
	}

	public String getYsxgyy() {
		return this.ysxgyy;
	}

	public void setYsxgyy(String ysxgyy) {
		this.ysxgyy = ysxgyy;
	}

	public Double getSszj() {
		return this.sszj;
	}

	public void setSszj(Double sszj) {
		this.sszj = sszj;
	}

	public Double getScbdje() {
		return this.scbdje;
	}

	public void setScbdje(Double scbdje) {
		this.scbdje = scbdje;
	}

	public Double getBcbdje() {
		return this.bcbdje;
	}

	public void setBcbdje(Double bcbdje) {
		this.bcbdje = bcbdje;
	}

	public Double getQstzje() {
		return this.qstzje;
	}

	public void setQstzje(Double qstzje) {
		this.qstzje = qstzje;
	}

	public String getTzyy() {
		return this.tzyy;
	}

	public void setTzyy(String tzyy) {
		this.tzyy = tzyy;
	}

	public String getMemo() {
		return this.memo;
	}

	public void setMemo(String memo) {
		this.memo = memo;
	}

	public String getSpzt() {
		return this.spzt;
	}

	public void setSpzt(String spzt) {
		this.spzt = spzt;
	}

	public String getQspc() {
		return this.qspc;
	}

	public void setQspc(String qspc) {
		this.qspc = qspc;
	}

	public String getCHtlx() {
		return this.CHtlx;
	}

	public void setCHtlx(String CHtlx) {
		this.CHtlx = CHtlx;
	}

	@Override
	public String getMid() {
		// TODO Auto-generated method stub
		return null;
	}

	public String getMzq() {
		return mzq;
	}

	public void setMzq(String mzq) {
		this.mzq = mzq;
	}

}