package com.tansun.eam2.common.model.orm.bo;

import java.util.Date;

/**
 * KpRzkmDzb generated by MyEclipse Persistence Tools
 */

public class KpRzkmDzb extends com.tansun.rdp4j.common.web.vo.CommonBO
		implements java.io.Serializable {

	// Fields

	private static final long serialVersionUID = 720148573730383200L;
	private String id;
	private String kmbh;
	private String rzkm;
	private String sfcj;
	private String lbmc;
	private Date qyrq;
	private Date tyrq;
	private String dqzt;

	// Constructors

	/** default constructor */
	public KpRzkmDzb() {
	}

	/** full constructor */
	public KpRzkmDzb(String kmbh, String rzkm, String sfcj, String lbmc,
			Date qyrq, Date tyrq, String dqzt) {
		this.kmbh = kmbh;
		this.rzkm = rzkm;
		this.sfcj = sfcj;
		this.lbmc = lbmc;
		this.qyrq = qyrq;
		this.tyrq = tyrq;
		this.dqzt = dqzt;
	}

	// Property accessors

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getKmbh() {
		return this.kmbh;
	}

	public void setKmbh(String kmbh) {
		this.kmbh = kmbh;
	}

	public String getRzkm() {
		return this.rzkm;
	}

	public void setRzkm(String rzkm) {
		this.rzkm = rzkm;
	}

	public String getSfcj() {
		return this.sfcj;
	}

	public void setSfcj(String sfcj) {
		this.sfcj = sfcj;
	}

	public String getLbmc() {
		return this.lbmc;
	}

	public void setLbmc(String lbmc) {
		this.lbmc = lbmc;
	}

	public Date getQyrq() {
		return this.qyrq;
	}

	public void setQyrq(Date qyrq) {
		this.qyrq = qyrq;
	}

	public Date getTyrq() {
		return this.tyrq;
	}

	public void setTyrq(Date tyrq) {
		this.tyrq = tyrq;
	}

	public String getDqzt() {
		return this.dqzt;
	}

	public void setDqzt(String dqzt) {
		this.dqzt = dqzt;
	}

	@Override
	public String getMid() {
		// TODO Auto-generated method stub
		return null;
	}

}