package com.tansun.eam2.common.model.orm.bo;

import java.util.Date;

/**
 * Recordhistory generated by MyEclipse Persistence Tools
 */

public class Recordhistory extends com.tansun.rdp4j.common.web.vo.CommonBO
		implements java.io.Serializable {

	// Fields

	private static final long serialVersionUID = -5253695435180905691L;
	private String id;
	private String name;
	private String before;
	private String after;
	private String wfCode;
	private String pkId;
	private String zcId;
	private String zcType;
	private String elementid;
	private String changetype;
	private String changestate;
	private String changeinfoid;
	private Date changedate;
	private String changeperson;
	private String biaoming;
	private String changepersonId;
	private String zhuangTai;

	// Constructors

	/** default constructor */
	public Recordhistory() {
	}

	/** full constructor */
	public Recordhistory(String name, String before, String after,
			String wfCode, String pkId, String zcId, String zcType,
			String elementid, String changetype, String changestate,
			String changeinfoid, Date changedate, String changeperson,
			String biaoming,String changepersonId,String zhuangTai) {
		this.name = name;
		this.before = before;
		this.after = after;
		this.wfCode = wfCode;
		this.pkId = pkId;
		this.zcId = zcId;
		this.zcType = zcType;
		this.elementid = elementid;
		this.changetype = changetype;
		this.changestate = changestate;
		this.changeinfoid = changeinfoid;
		this.changedate = changedate;
		this.changeperson = changeperson;
		this.biaoming = biaoming;
		this.changepersonId = changepersonId;
		this.zhuangTai = zhuangTai;
	}

	// Property accessors

	public String getChangepersonId() {
		return changepersonId;
	}

	public void setChangepersonId(String changepersonId) {
		this.changepersonId = changepersonId;
	}

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getBefore() {
		return this.before;
	}

	public void setBefore(String before) {
		this.before = before;
	}

	public String getAfter() {
		return this.after;
	}

	public void setAfter(String after) {
		this.after = after;
	}

	public String getWfCode() {
		return this.wfCode;
	}

	public void setWfCode(String wfCode) {
		this.wfCode = wfCode;
	}

	public String getPkId() {
		return this.pkId;
	}

	public void setPkId(String pkId) {
		this.pkId = pkId;
	}

	public String getZcId() {
		return this.zcId;
	}

	public void setZcId(String zcId) {
		this.zcId = zcId;
	}

	public String getZcType() {
		return this.zcType;
	}

	public void setZcType(String zcType) {
		this.zcType = zcType;
	}

	public String getElementid() {
		return this.elementid;
	}

	public void setElementid(String elementid) {
		this.elementid = elementid;
	}

	public String getChangetype() {
		return this.changetype;
	}

	public void setChangetype(String changetype) {
		this.changetype = changetype;
	}

	public String getChangestate() {
		return this.changestate;
	}

	public void setChangestate(String changestate) {
		this.changestate = changestate;
	}

	public String getChangeinfoid() {
		return this.changeinfoid;
	}

	public void setChangeinfoid(String changeinfoid) {
		this.changeinfoid = changeinfoid;
	}

	public Date getChangedate() {
		return this.changedate;
	}

	public void setChangedate(Date changedate) {
		this.changedate = changedate;
	}

	public String getChangeperson() {
		return this.changeperson;
	}

	public void setChangeperson(String changeperson) {
		this.changeperson = changeperson;
	}

	public String getBiaoming() {
		return this.biaoming;
	}

	public void setBiaoming(String biaoming) {
		this.biaoming = biaoming;
	}

	public String getZhuangTai() {
		return zhuangTai;
	}

	public void setZhuangTai(String zhuangTai) {
		this.zhuangTai = zhuangTai;
	}

	@Override
	public String getMid() {
		// TODO Auto-generated method stub
		return null;
	}

}