package com.tansun.eam2.common.model.orm.bo;

import java.util.Date;

/**
 * StGlbt generated by MyEclipse Persistence Tools
 */

public class StGlbt extends com.tansun.rdp4j.common.web.vo.CommonBO implements Cloneable,
		java.io.Serializable {

	private static final long serialVersionUID = 7939907886740067031L;
	private String id;
	private String cldId;
	private String stId;
	private String gzgw;
	private String CXueli;
	private String zzyq;
	private String CXingbie;
	private String gongling;
	private Long renshu;
	private String qtxx;
	private String CSqsxlx;
	private Double sqje;
	private String sqsm;
	private Double sdje;
	private String sqxmmc;
	private String frbh;
	private Long sffrdb;
	private String xingming;
	private Long nianling;
	private String sfzh;
	private String CHyzk;
	private String minzu;
	private String jiguan;
	private Date csny;
	private String CZhiwu;
	private String byxx;
	private String bysj;
	private String zhuanye;
	private String shouji;
	private String jtzz;
	private String yzbm;
	private String dianhua;
	private String dzyx;
	private String xinzi;
	private String gyqx;
	private Double shouru;
	private String gzffdw;
	private String rylx;
	private String dacfdw;
	private String gysm;
	private String tzfs;
	private Double tzje;
	private String czfs;
	private Double czje;
	private String fyzl;
	private String fymc;
	private Double bxfy;
	private Double sjfy;
	private String spzt;
	private String fzyzgqk;

	// Constructors

	/** default constructor */
	public StGlbt() {
	}

	/** full constructor */
	public StGlbt(String cldId, String stId, String gzgw, String CXueli,
			String zzyq, String CXingbie, String gongling, Long renshu,
			String qtxx, String CSqsxlx, Double sqje, String sqsm, Double sdje,
			String sqxmmc, String frbh, Long sffrdb, String xingming,
			Long nianling, String sfzh, String CHyzk, String minzu,
			String jiguan, Date csny, String CZhiwu, String byxx, String bysj,
			String zhuanye, String shouji, String jtzz, String yzbm,
			String dianhua, String dzyx, String xinzi, String gyqx,
			Double shouru, String gzffdw, String rylx, String dacfdw,
			String gysm, String tzfs, Double tzje, String czfs, Double czje,
			String fyzl, String fymc, Double bxfy, Double sjfy, String spzt, String fzyzgqk) {
		this.cldId = cldId;
		this.stId = stId;
		this.gzgw = gzgw;
		this.CXueli = CXueli;
		this.zzyq = zzyq;
		this.CXingbie = CXingbie;
		this.gongling = gongling;
		this.renshu = renshu;
		this.qtxx = qtxx;
		this.CSqsxlx = CSqsxlx;
		this.sqje = sqje;
		this.sqsm = sqsm;
		this.sdje = sdje;
		this.sqxmmc = sqxmmc;
		this.frbh = frbh;
		this.sffrdb = sffrdb;
		this.xingming = xingming;
		this.nianling = nianling;
		this.sfzh = sfzh;
		this.CHyzk = CHyzk;
		this.minzu = minzu;
		this.jiguan = jiguan;
		this.csny = csny;
		this.CZhiwu = CZhiwu;
		this.byxx = byxx;
		this.bysj = bysj;
		this.zhuanye = zhuanye;
		this.shouji = shouji;
		this.jtzz = jtzz;
		this.yzbm = yzbm;
		this.dianhua = dianhua;
		this.dzyx = dzyx;
		this.xinzi = xinzi;
		this.gyqx = gyqx;
		this.shouru = shouru;
		this.gzffdw = gzffdw;
		this.rylx = rylx;
		this.dacfdw = dacfdw;
		this.gysm = gysm;
		this.tzfs = tzfs;
		this.tzje = tzje;
		this.czfs = czfs;
		this.czje = czje;
		this.fyzl = fyzl;
		this.fymc = fymc;
		this.bxfy = bxfy;
		this.sjfy = sjfy;
		this.spzt = spzt;
		this.fzyzgqk = fzyzgqk;
	}

	public StGlbt clone(StGlbt sf){
		try {
			return (StGlbt) sf.clone();
		} catch (CloneNotSupportedException e) {
			e.printStackTrace();
			return null;
		}
	}
	
	// Property accessors

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getCldId() {
		return this.cldId;
	}

	public void setCldId(String cldId) {
		this.cldId = cldId;
	}

	public String getStId() {
		return this.stId;
	}

	public void setStId(String stId) {
		this.stId = stId;
	}

	public String getGzgw() {
		return this.gzgw;
	}

	public void setGzgw(String gzgw) {
		this.gzgw = gzgw;
	}

	public String getCXueli() {
		return this.CXueli;
	}

	public void setCXueli(String CXueli) {
		this.CXueli = CXueli;
	}

	public String getZzyq() {
		return this.zzyq;
	}

	public void setZzyq(String zzyq) {
		this.zzyq = zzyq;
	}

	public String getCXingbie() {
		return this.CXingbie;
	}

	public void setCXingbie(String CXingbie) {
		this.CXingbie = CXingbie;
	}

	public String getGongling() {
		return this.gongling;
	}

	public void setGongling(String gongling) {
		this.gongling = gongling;
	}

	public Long getRenshu() {
		return this.renshu;
	}

	public void setRenshu(Long renshu) {
		this.renshu = renshu;
	}

	public String getQtxx() {
		return this.qtxx;
	}

	public void setQtxx(String qtxx) {
		this.qtxx = qtxx;
	}

	public String getCSqsxlx() {
		return this.CSqsxlx;
	}

	public void setCSqsxlx(String CSqsxlx) {
		this.CSqsxlx = CSqsxlx;
	}

	public Double getSqje() {
		return this.sqje;
	}

	public void setSqje(Double sqje) {
		this.sqje = sqje;
	}

	public String getSqsm() {
		return this.sqsm;
	}

	public void setSqsm(String sqsm) {
		this.sqsm = sqsm;
	}

	public Double getSdje() {
		return this.sdje;
	}

	public void setSdje(Double sdje) {
		this.sdje = sdje;
	}

	public String getSqxmmc() {
		return this.sqxmmc;
	}

	public void setSqxmmc(String sqxmmc) {
		this.sqxmmc = sqxmmc;
	}

	public String getFrbh() {
		return this.frbh;
	}

	public void setFrbh(String frbh) {
		this.frbh = frbh;
	}

	public Long getSffrdb() {
		return this.sffrdb;
	}

	public void setSffrdb(Long sffrdb) {
		this.sffrdb = sffrdb;
	}

	public String getXingming() {
		return this.xingming;
	}

	public void setXingming(String xingming) {
		this.xingming = xingming;
	}

	public Long getNianling() {
		return this.nianling;
	}

	public void setNianling(Long nianling) {
		this.nianling = nianling;
	}

	public String getSfzh() {
		return this.sfzh;
	}

	public void setSfzh(String sfzh) {
		this.sfzh = sfzh;
	}

	public String getCHyzk() {
		return this.CHyzk;
	}

	public void setCHyzk(String CHyzk) {
		this.CHyzk = CHyzk;
	}

	public String getMinzu() {
		return this.minzu;
	}

	public void setMinzu(String minzu) {
		this.minzu = minzu;
	}

	public String getJiguan() {
		return this.jiguan;
	}

	public void setJiguan(String jiguan) {
		this.jiguan = jiguan;
	}

	public Date getCsny() {
		return this.csny;
	}

	public void setCsny(Date csny) {
		this.csny = csny;
	}

	public String getCZhiwu() {
		return this.CZhiwu;
	}

	public void setCZhiwu(String CZhiwu) {
		this.CZhiwu = CZhiwu;
	}

	public String getByxx() {
		return this.byxx;
	}

	public void setByxx(String byxx) {
		this.byxx = byxx;
	}

	public String getBysj() {
		return this.bysj;
	}

	public void setBysj(String bysj) {
		this.bysj = bysj;
	}

	public String getZhuanye() {
		return this.zhuanye;
	}

	public void setZhuanye(String zhuanye) {
		this.zhuanye = zhuanye;
	}

	public String getShouji() {
		return this.shouji;
	}

	public void setShouji(String shouji) {
		this.shouji = shouji;
	}

	public String getJtzz() {
		return this.jtzz;
	}

	public void setJtzz(String jtzz) {
		this.jtzz = jtzz;
	}

	public String getYzbm() {
		return this.yzbm;
	}

	public void setYzbm(String yzbm) {
		this.yzbm = yzbm;
	}

	public String getDianhua() {
		return this.dianhua;
	}

	public void setDianhua(String dianhua) {
		this.dianhua = dianhua;
	}

	public String getDzyx() {
		return this.dzyx;
	}

	public void setDzyx(String dzyx) {
		this.dzyx = dzyx;
	}

	public String getXinzi() {
		return this.xinzi;
	}

	public void setXinzi(String xinzi) {
		this.xinzi = xinzi;
	}

	public String getGyqx() {
		return this.gyqx;
	}

	public void setGyqx(String gyqx) {
		this.gyqx = gyqx;
	}

	public Double getShouru() {
		return this.shouru;
	}

	public void setShouru(Double shouru) {
		this.shouru = shouru;
	}

	public String getGzffdw() {
		return this.gzffdw;
	}

	public void setGzffdw(String gzffdw) {
		this.gzffdw = gzffdw;
	}

	public String getRylx() {
		return this.rylx;
	}

	public void setRylx(String rylx) {
		this.rylx = rylx;
	}

	public String getDacfdw() {
		return this.dacfdw;
	}

	public void setDacfdw(String dacfdw) {
		this.dacfdw = dacfdw;
	}

	public String getGysm() {
		return this.gysm;
	}

	public void setGysm(String gysm) {
		this.gysm = gysm;
	}

	public String getTzfs() {
		return this.tzfs;
	}

	public void setTzfs(String tzfs) {
		this.tzfs = tzfs;
	}

	public Double getTzje() {
		return this.tzje;
	}

	public void setTzje(Double tzje) {
		this.tzje = tzje;
	}

	public String getCzfs() {
		return this.czfs;
	}

	public void setCzfs(String czfs) {
		this.czfs = czfs;
	}

	public Double getCzje() {
		return this.czje;
	}

	public void setCzje(Double czje) {
		this.czje = czje;
	}

	public String getFyzl() {
		return this.fyzl;
	}

	public void setFyzl(String fyzl) {
		this.fyzl = fyzl;
	}

	public String getFymc() {
		return this.fymc;
	}

	public void setFymc(String fymc) {
		this.fymc = fymc;
	}

	public Double getBxfy() {
		return this.bxfy;
	}

	public void setBxfy(Double bxfy) {
		this.bxfy = bxfy;
	}

	public Double getSjfy() {
		return this.sjfy;
	}

	public void setSjfy(Double sjfy) {
		this.sjfy = sjfy;
	}

	public String getSpzt() {
		return this.spzt;
	}

	public void setSpzt(String spzt) {
		this.spzt = spzt;
	}

	public String getFzyzgqk() {
		return fzyzgqk;
	}

	public void setFzyzgqk(String fzyzgqk) {
		this.fzyzgqk = fzyzgqk;
	}
	
	public String setFzyzgqkString(String[] zsmc,String[] fzsj,String[] fzjg, String[] zsbh){
		StringBuffer sb = new StringBuffer();
		for (int i = 0; i<zsmc.length; i++){
			if((zsbh[i]== null||"".equals(zsbh[i]))&&(zsmc[i] == null||"".equals(zsmc[i]))&&(fzsj[i] == null||"".equals(fzsj[i]))
				&&(fzjg[i] == null||"".equals(fzjg[i]))){
				
			}else{
				if(zsbh[i]==null||"".equals(zsbh[i])){
					sb.append("&nbsp;").append("#%#");	
				}else{
					sb.append(zsbh[i]).append("#%#");	
				}
				if(zsmc[i]==null||"".equals(zsmc[i])){
					sb.append("&nbsp;").append("#%#");
				}else{
					sb.append(zsmc[i]).append("#%#");
				}
				if(fzsj[i]==null||"".equals(fzsj[i])){
					sb.append("&nbsp;").append("#%#");
				}else{
					sb.append(fzsj[i]).append("#%#");
				}
				if(fzjg[i]==null||"".equals(fzjg[i])){
					sb.append("&nbsp;");
				}else{
					sb.append(fzjg[i]);
				}
				if(i<zsmc.length-1){
					sb.append("<#>");
				}
			}
		}
		return sb.toString();
	}
	
	
	public String getFzyzgqkString(String zyzgqk){
		
		StringBuffer sb = new StringBuffer();
		if(!(zyzgqk == null || "".equals(zyzgqk))){
			String[] zyzgqkArr = zyzgqk.split("<#>");
			for(String zyzgqks : zyzgqkArr){
				String[] zyDetail = zyzgqks.split("#%#");
				if(zyDetail.length == 0) return "";
				sb.append("<tr>")
				  .append("<td >")
				  .append("证书名称:").append("</td>")
				  .append("<td>").append("<input name='zsmc' value='").append(zyDetail[0]).append("'/></td>")
				  .append("<td>").append("证书编号:").append("</td>")
				  .append("<td>").append("<input name='zsbh' value='").append(zyDetail[1]).append("'/></td></tr>");
				sb.append("<tr>")
				  .append("<td>").append("发证时间:").append("</td>")
				  .append("<td>").append("<input name='fzsj' value='").append(zyDetail[2]).append("'/></td>")
				  .append("<td>").append("发证机构:").append("</td>")
				  .append("<td>").append("<input name='fzjg' value='").append(zyDetail[3]).append("'/></td></tr>");
			}
		}
		return sb.toString();
	}
	@Override
	public String getMid() {
		// TODO Auto-generated method stub
		return null;
	}


}