package com.tansun.eam2.common.model.orm.bo;

import java.util.Date;

/**
 * StHead generated by MyEclipse Persistence Tools
 */

public class StHead extends com.tansun.rdp4j.common.web.vo.CommonBO implements Cloneable,
		java.io.Serializable {

	private static final long serialVersionUID = -2234621590525226148L;
	private String id;
	private String lcId;
	private String biaoti;
	private String chengsong;
	private String bianhao;
	private String jhcd;
	private String ngr;
	private String ngrxm;
	private String lxdh;
	private Date ngrq;
	private String ngbm;
	private String ngbmmc;
	private String ywlx;
	private String hqbm;
	private String hqbmid;
	private String syhqbm;
	private String syhqbmid;
	private String bz;
	private String lcmc;
	private Long jhxzrs;
	private String spzt;
	private String sfsjfy;
	private String stId;
	private String zcbh;
	private String stzwmc;
	private String diqu;
	private String gqgc;
	private String zzqk;
	private String bgdz;
	private Long strs;
	private String zmtz;
	private String CWtgljg;
	private String CGlbm;
	private String czygsnsqk;
	private String zyyw;
	private Double zzc;
	private Double fuzhai;
	private String guben;
	private Double jzc;
	private Double stsr;
	private Double jlr;
	private String zixuntype;
	private Double sqjehj;
	private Double sdjehj;
	public StHead clone(StHead sf){
		try {
			return (StHead) sf.clone();
		} catch (CloneNotSupportedException e) {
			e.printStackTrace();
			return null;
		}
	}
	
	public String getId() {
		return id;
	}
	public void setId(String id) {
		this.id = id;
	}
	public String getLcId() {
		return lcId;
	}
	public void setLcId(String lcId) {
		this.lcId = lcId;
	}
	public String getBiaoti() {
		return biaoti;
	}
	public void setBiaoti(String biaoti) {
		this.biaoti = biaoti;
	}
	public String getChengsong() {
		return chengsong;
	}
	public void setChengsong(String chengsong) {
		this.chengsong = chengsong;
	}
	public String getBianhao() {
		return bianhao;
	}
	public void setBianhao(String bianhao) {
		this.bianhao = bianhao;
	}
	public String getJhcd() {
		return jhcd;
	}
	public void setJhcd(String jhcd) {
		this.jhcd = jhcd;
	}
	public String getNgr() {
		return ngr;
	}
	public void setNgr(String ngr) {
		this.ngr = ngr;
	}
	public String getNgrxm() {
		return ngrxm;
	}
	public void setNgrxm(String ngrxm) {
		this.ngrxm = ngrxm;
	}
	public String getLxdh() {
		return lxdh;
	}
	public void setLxdh(String lxdh) {
		this.lxdh = lxdh;
	}
	public Date getNgrq() {
		return ngrq;
	}
	public void setNgrq(Date ngrq) {
		this.ngrq = ngrq;
	}
	public String getNgbm() {
		return ngbm;
	}
	public void setNgbm(String ngbm) {
		this.ngbm = ngbm;
	}
	public String getNgbmmc() {
		return ngbmmc;
	}
	public void setNgbmmc(String ngbmmc) {
		this.ngbmmc = ngbmmc;
	}
	public String getYwlx() {
		return ywlx;
	}
	public void setYwlx(String ywlx) {
		this.ywlx = ywlx;
	}
	public String getHqbm() {
		return hqbm;
	}
	public void setHqbm(String hqbm) {
		this.hqbm = hqbm;
	}
	public String getHqbmid() {
		return hqbmid;
	}
	public void setHqbmid(String hqbmid) {
		this.hqbmid = hqbmid;
	}
	public String getSyhqbm() {
		return syhqbm;
	}
	public void setSyhqbm(String syhqbm) {
		this.syhqbm = syhqbm;
	}
	public String getSyhqbmid() {
		return syhqbmid;
	}
	public void setSyhqbmid(String syhqbmid) {
		this.syhqbmid = syhqbmid;
	}
	public String getBz() {
		return bz;
	}
	public void setBz(String bz) {
		this.bz = bz;
	}
	public String getLcmc() {
		return lcmc;
	}
	public void setLcmc(String lcmc) {
		this.lcmc = lcmc;
	}
	public Long getJhxzrs() {
		return jhxzrs;
	}
	public void setJhxzrs(Long jhxzrs) {
		this.jhxzrs = jhxzrs;
	}
	public String getSpzt() {
		return spzt;
	}
	public void setSpzt(String spzt) {
		this.spzt = spzt;
	}
	public String getSfsjfy() {
		return sfsjfy;
	}
	public void setSfsjfy(String sfsjfy) {
		this.sfsjfy = sfsjfy;
	}
	public String getStId() {
		return stId;
	}
	public void setStId(String stId) {
		this.stId = stId;
	}
	public String getZcbh() {
		return zcbh;
	}
	public void setZcbh(String zcbh) {
		this.zcbh = zcbh;
	}
	public String getStzwmc() {
		return stzwmc;
	}
	public void setStzwmc(String stzwmc) {
		this.stzwmc = stzwmc;
	}
	public String getDiqu() {
		return diqu;
	}
	public void setDiqu(String diqu) {
		this.diqu = diqu;
	}
	public String getGqgc() {
		return gqgc;
	}
	public void setGqgc(String gqgc) {
		this.gqgc = gqgc;
	}
	public String getZzqk() {
		return zzqk;
	}
	public void setZzqk(String zzqk) {
		this.zzqk = zzqk;
	}
	public String getBgdz() {
		return bgdz;
	}
	public void setBgdz(String bgdz) {
		this.bgdz = bgdz;
	}
	public Long getStrs() {
		return strs;
	}
	public void setStrs(Long strs) {
		this.strs = strs;
	}
	public String getZmtz() {
		return zmtz;
	}
	public void setZmtz(String zmtz) {
		this.zmtz = zmtz;
	}
	public String getCWtgljg() {
		return CWtgljg;
	}
	public void setCWtgljg(String wtgljg) {
		CWtgljg = wtgljg;
	}
	public String getCGlbm() {
		return CGlbm;
	}
	public void setCGlbm(String glbm) {
		CGlbm = glbm;
	}
	public String getCzygsnsqk() {
		return czygsnsqk;
	}
	public void setCzygsnsqk(String czygsnsqk) {
		this.czygsnsqk = czygsnsqk;
	}
	public String getZyyw() {
		return zyyw;
	}
	public void setZyyw(String zyyw) {
		this.zyyw = zyyw;
	}
	public Double getZzc() {
		return zzc;
	}
	public void setZzc(Double zzc) {
		this.zzc = zzc;
	}
	public Double getFuzhai() {
		return fuzhai;
	}
	public void setFuzhai(Double fuzhai) {
		this.fuzhai = fuzhai;
	}
	public String getGuben() {
		return guben;
	}
	public void setGuben(String guben) {
		this.guben = guben;
	}
	public Double getJzc() {
		return jzc;
	}
	public void setJzc(Double jzc) {
		this.jzc = jzc;
	}
	public Double getStsr() {
		return stsr;
	}
	public void setStsr(Double stsr) {
		this.stsr = stsr;
	}
	public Double getJlr() {
		return jlr;
	}
	public void setJlr(Double jlr) {
		this.jlr = jlr;
	}
	public String getZixuntype() {
		return zixuntype;
	}
	public void setZixuntype(String zixuntype) {
		this.zixuntype = zixuntype;
	}
	public Double getSqjehj() {
		return sqjehj;
	}
	public void setSqjehj(Double sqjehj) {
		this.sqjehj = sqjehj;
	}
	public Double getSdjehj() {
		return sdjehj;
	}
	public void setSdjehj(Double sdjehj) {
		this.sdjehj = sdjehj;
	}
	public static long getSerialVersionUID() {
		return serialVersionUID;
	}
	public StHead(String id, String lcId, String biaoti, String chengsong,
			String bianhao, String jhcd, String ngr, String ngrxm, String lxdh,
			Date ngrq, String ngbm, String ngbmmc, String ywlx, String hqbm,
			String hqbmid, String syhqbm, String syhqbmid, String bz,
			String lcmc, Long jhxzrs, String spzt, String sfsjfy, String stId,
			String zcbh, String stzwmc, String diqu, String gqgc, String zzqk,
			String bgdz, Long strs, String zmtz, String wtgljg, String glbm,
			String czygsnsqk, String zyyw, Double zzc, Double fuzhai,
			String guben, Double jzc, Double stsr, Double jlr,
			String zixuntype, Double sqjehj, Double sdjehj) {
		super();
		this.id = id;
		this.lcId = lcId;
		this.biaoti = biaoti;
		this.chengsong = chengsong;
		this.bianhao = bianhao;
		this.jhcd = jhcd;
		this.ngr = ngr;
		this.ngrxm = ngrxm;
		this.lxdh = lxdh;
		this.ngrq = ngrq;
		this.ngbm = ngbm;
		this.ngbmmc = ngbmmc;
		this.ywlx = ywlx;
		this.hqbm = hqbm;
		this.hqbmid = hqbmid;
		this.syhqbm = syhqbm;
		this.syhqbmid = syhqbmid;
		this.bz = bz;
		this.lcmc = lcmc;
		this.jhxzrs = jhxzrs;
		this.spzt = spzt;
		this.sfsjfy = sfsjfy;
		this.stId = stId;
		this.zcbh = zcbh;
		this.stzwmc = stzwmc;
		this.diqu = diqu;
		this.gqgc = gqgc;
		this.zzqk = zzqk;
		this.bgdz = bgdz;
		this.strs = strs;
		this.zmtz = zmtz;
		CWtgljg = wtgljg;
		CGlbm = glbm;
		this.czygsnsqk = czygsnsqk;
		this.zyyw = zyyw;
		this.zzc = zzc;
		this.fuzhai = fuzhai;
		this.guben = guben;
		this.jzc = jzc;
		this.stsr = stsr;
		this.jlr = jlr;
		this.zixuntype = zixuntype;
		this.sqjehj = sqjehj;
		this.sdjehj = sdjehj;
	}
	public StHead() {
		super();
	}
	@Override
	public String getMid() {
		return this.id;
	}
}