package com.tansun.eam2.common.model.orm.bo;

/**
 * StSkjnXx generated by MyEclipse Persistence Tools
 */

public class StSkjnXx extends com.tansun.rdp4j.common.web.vo.CommonBO implements Cloneable,
		java.io.Serializable {

	private static final long serialVersionUID = -3172619169624862744L;
	private String id;
	private String stId;
	//税款名称
	private String skmc;
	//是否按时交纳0：否1：是
	private String sfasjn;
	//拖欠税款数额
	private Double tqskse;
	//拖欠时间
	private String tqsj;
	//税务机关是否可以减免0：否1：是
	private String swjgsfkjm;
	/**
	 * 是否保存    1 ：保存   
	 */
	private String sfbc;
	private String beizhu;

	// Constructors

	public StSkjnXx(String id, String stId, String skmc, String sfasjn,
			Double tqskse, String tqsj, String swjgsfkjm, String sfbc,String beizhu) {
		super();
		this.id = id;
		this.stId = stId;
		this.skmc = skmc;
		this.sfasjn = sfasjn;
		this.tqskse = tqskse;
		this.tqsj = tqsj;
		this.swjgsfkjm = swjgsfkjm;
		this.sfbc = sfbc;
		this.beizhu = beizhu;
	}
	public StSkjnXx clone(StSkjnXx sf){
		try {
			return (StSkjnXx) sf.clone();
		} catch (CloneNotSupportedException e) {
			e.printStackTrace();
			return null;
		}
	}
	/** default constructor */
	public StSkjnXx() {
	}

	/** full constructor */

	// Property accessors

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getStId() {
		return this.stId;
	}

	public void setStId(String stId) {
		this.stId = stId;
	}

	public String getSkmc() {
		return this.skmc;
	}

	public void setSkmc(String skmc) {
		this.skmc = skmc;
	}

	public String getSfasjn() {
		return this.sfasjn;
	}

	public void setSfasjn(String sfasjn) {
		this.sfasjn = sfasjn;
	}

	public Double getTqskse() {
		return this.tqskse;
	}

	public void setTqskse(Double tqskse) {
		this.tqskse = tqskse;
	}

	public String getTqsj() {
		return this.tqsj;
	}

	public void setTqsj(String tqsj) {
		this.tqsj = tqsj;
	}

	public String getSwjgsfkjm() {
		return this.swjgsfkjm;
	}

	public void setSwjgsfkjm(String swjgsfkjm) {
		this.swjgsfkjm = swjgsfkjm;
	}

	@Override
	public String getMid() {
		// TODO Auto-generated method stub
		return null;
	}

	public String getSfbc() {
		return sfbc;
	}

	public void setSfbc(String sfbc) {
		this.sfbc = sfbc;
	}
	public String getBeizhu() {
		return beizhu;
	}
	public void setBeizhu(String beizhu) {
		this.beizhu = beizhu;
	}

}